### ISSUE TITLE
Using 0 base index for currentSlideNumber but 1 base index for goToSlide

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#100]
the currentSlideNumber variable in args starts at 0 for the first slide. But gotoslide thinks 1 means the first slide. Only one convention should be used across the project concerning what the starting index is.

Not sure what other places this is different, only noticed this one so far.

**Comment by iosscripts** [comment]
I will be moving everything over to a 1 based system. Easier for the inexperienced user that way.

**Comment by ColColonCleaner** [comment]
Sounds good, i will update by mods accordingly. I expect merging them with your 1.1 code will be a bear already, lol, haven't tried yet :)

**Comment by iosscripts** [comment]
Added in v1.1.7.
