### ISSUE TITLE
Question: Under what conditions does autoSlide pause?

### ISSUE THREAD

**Issue by daegloe** [iosscripts/iosslider#102]
I've noticed that, at times, it can take some mouse activity over the slider for the autoSlide to begin after initialization. And other times is seems to noticeably pause while the mouse cursor is over the slider, although this is not consistent. I've been able to reproduce this behavior in Safari and Chrome.

**Comment by iosscripts** [comment]
That's odd. Autoslide should begin immediately, but pause on hover. Do you have a test case of it not starting on page load when autoslide: true?

**Comment by daegloe** [comment]
I do not have a test case that I can share, unfortunately.

However, I believe this is due to a known Webkit issue. Webkit for some reason gives the cursor a virtual position of 1,1 when a page finishes loading. This goes away once the mouse moves over the viewpoint. I could work around it by setting the top position of the slider to 2, but that isn't ideal since we want it flush with the top of the viewport.
