### ISSUE TITLE
part of content doesn't animate in webkit browsers

### ISSUE THREAD

**Issue by ololoTrololo** [iosscripts/iosslider#104]
Hi! First of all, thank you for this amazing slider! It's really very nice!
I've tried lot's of sliders and this one i like most of all. 
But i found a bug in it, just like in other sliders on webkit browsers :(

I have three slider's items, and I have some content inside them, which I don't want to display before click on one of the button's. After that click  it should slide down. It work's perfect in Firefox and Opera, but nothing seem's to happen in Chrome, untill I'll change css in firebug. 

I saw similar issue <a href="http://forum.jquery.com/topic/text-doesn-t-display-in-iosslider-plugin-on-webkit-browsers"> here</a> , but it didn't help me much.

here is my code:

``` js
$(document).ready(function() {

    $('.iosSlider').iosSlider({
        snapToChildren: true,
        desktopClickDrag: true,
        keyboardControls: true,
        infiniteSlider: true,
        onSliderLoaded: sliderTest,
        onSlideStart: sliderTest,
        onSlideComplete: slideComplete,
        navNextSelector: $('.next'),
        navPrevSelector: $('.prev'),
    });
    $('.addInfoSlide').css('display', 'none');
    $('#item7').click(function(){
        $('.addInfoSlide').slideDown("slow");
    });

});

function sliderTest(args) {
    console.log(args.targetSliderOffset);
}

function slideComplete(args) {

    $('.next, .prev').removeClass('unselectable');

    if(args.currentSlideNumber == 0) {

        $('.prev').addClass('unselectable');

    } else if(args.currentSliderOffset == args.data.sliderMax) {

        $('.next').addClass('unselectable');

    }

}
```

``` html
<div class = 'sliderContainer'>
    <div class = 'iosSlider'>
      <ul class="slider">
        <li class = 'item'>                                     
                <img src="" width="100%" height="200" alt="" />

            <div class="addInfoSlide">
               SomeText, which is not displayed untill click
            </div>
        </li>
                                       <li class = 'item'>                                      
                <img src="" width="100%" height="200" alt="" />

            <div class="addInfoSlide">
               SomeText, which is not displayed untill click
            </div>
        </li>
                                         <li class = 'item'>                                        
                <img src="" width="100%" height="200" alt="" />

            <div class="addInfoSlide">
               SomeText, which is not displayed untill click
            </div>
        </li>                                                            
      </ul>                               
    </div>
    <a class="prev unselectable" href="javascript:void(0);"></a>
    <a class="next" href="javascript:void(0);"></a>
</div>
```

Thank you!

**Comment by ololoTrololo** [comment]
Hi again! I've solved it with a hack :)
I removed "display:none" from my content and set smaller height (240px)  to .iosSlider and "overflow:hidden", though content became not visible, then I added such code :

$('#item7').click(function(){
                    $('.iosSlider').animate({height : "455px"},2000,function());
                });

thanks again for your slider :)

**Comment by iosscripts** [comment]
Yes, it's not a bug actually but a behavior of display: none. When an element is set to none, the width/height are calculated as 0, so when the iosSlider is loaded and the width of the slides is 0, all the calculations break down.

Sorry I wasn't able to get back to you in time to help you out. :)
