### ISSUE TITLE
Tabbing through slides on Firefox overrides the SnapTo

### ISSUE THREAD

**Issue by Batmensch** [iosscripts/iosslider#106]
Here's an example: 

http://devenv61-temp.aldon.com/slider-test/

If I tab through these slides with Firefox snapToChildren seems to be ignored; instead the end of the text in the "a" element gets lined up with the edge of the slider window.  This is also true on IE 9.  On Chrome it works as expected.

To test, load the page and then start tabbing until you get to a slide that isn't viewable by default; the slides no longer snap.

**Comment by iosscripts** [comment]
I'm not sure I understand what you mean by tabbing. How do you tab through slides in the slider?

**Comment by Batmensch** [comment]
Open the page in a browser, and hit your tab key.  It should step through each slide.

**Comment by Batmensch** [comment]
Why was this closed?  I just downloaded iosslider  1.1.15 and it has the same problem?

**Comment by iosscripts** [comment]
The script isn't even loading in IE9 actually. There is a JS error in the demo provided.

**Comment by Batmensch** [comment]
Please try again.  Works for me in IE 9.

**Comment by iosscripts** [comment]
Error I see in IE9 developer tools:

Expected identifier, string or number 
slider-test.js, line 6 character 4

**Comment by Batmensch** [comment]
Here is the contents of slider-test.js:

$(document).ready(function() {
   $('.iosSlider-1').iosSlider({
      snapToChildren: true,
      scrollbar: false,
      desktopClickDrag: true,
   });
});

I am not able to get it to fail, with IE 9 or any other browser I have.

**Comment by iosscripts** [comment]
desktopClickDrag: true, 

Drop the , at the end of this line.

**Comment by Batmensch** [comment]
Done.

**Comment by iosscripts** [comment]
Now it's working for me as expected. Is it clean for you?

**Comment by Batmensch** [comment]
Works fine for me.  But it always did ;)

**Comment by iosscripts** [comment]
But what about the original "tabbing" issue? I haven't been able to reproduce it.

Either way, tabbing through slides is not really supported by this script anyway, so maybe I'll just leave it at that.

**Comment by Batmensch** [comment]
If our customer hits the "tab" key to go through the slides (as in the example), the slides don't auto-center (or whatever you call it) on Firefox or IE.  On Chrome they do what you expect and the slides stay lined up, that is, you don't see half a slide showing.

**Comment by Batmensch** [comment]
In other words, snapToChildren doesn't seem to work properly on IE and Firefox if you tab through the slides.

**Comment by iosscripts** [comment]
I still don't see anything happening at all when I hit tab.

If something is happening when you are tabbing then it's purely a coincidence. I haven't programmed any tab functionality into the script so nothing should be happening. 

I will log this as a feature request and decide if tabbing is something I want to support down the road. I will close this request and create a new one for the potential feature.

**Comment by Batmensch** [comment]
Hmm, I wonder how our functionality can be so different?  In any case, thanks for the consideration!
