### ISSUE TITLE
Populating many slides is very slow

### ISSUE THREAD

**Issue by PapaSimons** [iosscripts/iosslider#111]
I am using this wonderful library for an application where the users flip through many slides.. When I initiate or update the slider there is a long pause (~10-20 seconds) where all other js processes are paused.

I tried another swipe library where it initializes much much faster, however iosSlider is so much better in terms of responsiveness I can't give it up so easily.

Any ideas are much appreciated.
And thanks for the great library!

**Comment by iosscripts** [comment]
Hmmm. A lot of slides is still something I'm working through. Can you email me a link to the issue in question? I will try and find a way to improve the performance.

My email is contact@iosscripts.com. Thanks.

**Comment by iosscripts** [comment]
Related feature request: issue #2

**Comment by iosscripts** [comment]
Thanks for the demo. Very helpful. My comp loads it up in around half a second. My iPad 1 takes 20. Slower computers/devices would be worse obviously.

Let me do some more testing. I will look at the initialization again and see if I can slim down a few of those loops.

**Comment by iosscripts** [comment]
I was able to rebuild a test case and reproduce your performance lag issue. I then ran it against v1.0.35 (from your test case) and v1.1.14 (new iosSlider version). I found that v1.1.14 ran the test in ~2-3 seconds vs ~10-12 using v1.0.35.

Let me know if v1.1.14 doesn't show considerable improvement on your end.

**Comment by PapaSimons** [comment]
Thanks Marc, you are the man! :)

I also did some optimizing this morning on the code and I found the culprit
to be the : " $(slideNodes).each(function(j) { " loops.

I made the following changes to your code:
- minimized the number of loops
- moved it to a cached loop as advised in this discussion:
  http://stackoverflow.com/questions/1883611/should-i-use-jquery-each
- minimized the amount of  " $(this).outerWidth(true) " calculations
- some other code trimmings (should not affect the rest of the code)

Its much much faster now on many slides.
I am attaching the changed file to this mail with my changes on lines
1016-1113, let me know if it goes through

Gideon

On Tue, Oct 9, 2012 at 8:54 AM, Marc Whitbread notifications@github.comwrote:

> I was able to rebuild a test case and reproduce your performance lag
> issue. I then ran it against v1.0.35 (from your test case) and v1.1.14 (new
> iosSlider version). I found that v1.1.14 ran the test in ~2-3 seconds vs
> ~10-12 using v1.0.35.
> 
> Let me know if v1.1.14 doesn't show considerable improvement on your end.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iosscripts/iosSlider/issues/111#issuecomment-9245668.

## 

Gideon

**Comment by sonalishahi20** [comment]
Hi 
If you don't mind can you share your amended file because i am also facing a same issue. 
Thanks

**Comment by iosscripts** [comment]
@sonalishahi20 I added example 11 in the master branch under _demos/_examples/11-.../

**Comment by sonalishahi20** [comment]
Thanks a ton!! I really appreciate your prompt reply.
Great work done!

**Comment by PapaSimons** [comment]
@sonalishahi20  , give me an email address and I'll send you the optimized version (its considerably faster).

**Comment by isemog** [comment]
I'm also facing the same issue, version  v1.1.15, it takes 1 second in chrome to init 9 slides with some html inside . when I try it in ipad it takes 5 seconds... PapaSimons can you send me your version?

**Comment by PapaSimons** [comment]
sure i am happy to send it to you, or perhaps there is a better "github" way to post my changes?

**Comment by iosscripts** [comment]
@PapaSimons I would recommend just emailing them over to him first. We aren't sure that your performance improvements to initialization will work for his case. :S

Or, if your updates haven't changed much since you sent them over to me before, I can review them and add them to my updated init code?

Or, just fork it!

**Comment by PapaSimons** [comment]
Thanks Marc @iosscripts! I think better for others that its all here than I fork it.

My changes haven't changed since I sent them to you but I'll send it to you again just in case.

As you suggest I'll be happy to send it over to anyone, and since it may not work for other people here are the main things I changed in case it helps others who want to dig in:

I did some optimizing on the code and I found the culprit to be the : " $(slideNodes).each(function(j) { " loops.

I made the following changes to the code:
- minimized the number of loops 
- moved it to a cached loop as advised in this discussion: http://stackoverflow.com/questions/1883611/should-i-use-jquery-each
- minimized the amount of  " $(this).outerWidth(true) " calculations 
- some other code trimmings (should not affect the rest of the code)

**Comment by isemog** [comment]
I solved my performance issue (without touching the lib) by changing the way I was generating the slides. First I was generating all the slides with a lot of HTML inside, image, text, etc, and all this html inside was slowing down the process of creating the slider, even with just 9~11 slides. 

Now I create the slider with empty divs and its super fast (0,1second on iPad2) and just after the onSliderLoaded I inject the HTML for each slide.

**Comment by iosscripts** [comment]
@isemog glad to hear you worked it all out. I would prefer not to have to force users to do this though. Would you mind providing one of your slide's HTML contents that caused the performance lag?
