### ISSUE TITLE
Add callback for target slide number to args.

### ISSUE THREAD

**Issue by iosscripts** [iosscripts/iosslider#113]
Add a variable called 'targetSlideNumber' to the args array for all callbacks representing the slide number the current movement will come to a stop on.

**Comment by matthewwithanm** [comment]
I'm not sure if 78c75e5 was supposed to complete this feature or is just a start, but I'm getting `undefined` for `targetSlideNumber`.

Also, related feature request: targetSlideObject (:

**Comment by iosscripts** [comment]
Nope. Just testing :).

**Comment by iosscripts** [comment]
targetSlideObject/targetSlideNumber added to callbacks.
