### ISSUE TITLE
Autoslide Pause/Resume Methods

### ISSUE THREAD

**Issue by daegloe** [iosscripts/iosslider#114]
It would be great if there were programmatic pause/resume methods for when autoSlide is true.

**Comment by iosscripts** [comment]
I agree. I will definitely add these public methods in a future release.

**Comment by qfreddie** [comment]
I agree on this one too.

Plus i know that there is an 'autoSlideToggleSelector' now added, but this does not work - in my case at least, even when autoslide is set to true.

Anybody has similar issues?

**Comment by marcwhitbread** [comment]
Not working at all? Might be a bug. I will take a look at it.

**Comment by qfreddie** [comment]
Hmm, this might help you:
Might be something to due with the Double Slider version (Ex nr 5). I am using this one, and i edited the original example for no interference with my scripts, and the bug is present.

BTW my element is: < div id = "autoScrollToggle" > Start < / div >

**Comment by marcwhitbread** [comment]
What does your JS iosSlider initialization code look like? I want to make sure your using it correctly.

**Comment by qfreddie** [comment]
Well last time i used this in your example from the package i downloaded, so should be correct. I just added the selector name, and created the object in the source end.

```
            $('.doubleSlider-1').iosSlider({
                scrollbar: true,
                snapToChildren: true,
                desktopClickDrag: true,
                infiniteSlider: true,
                autoSlideToggleSelector: $('#autoScrollToggle'),
                autoSlide: true,
                navPrevSelector: $('.doubleSliderPrevButton'),
                navNextSelector: $('.doubleSliderNextButton'),
                scrollbarHeight: '2',
                scrollbarBorderRadius: '0',
                scrollbarOpacity: '0.5',
                onSliderLoaded: doubleSlider2Load,
                onSlideChange: doubleSlider2Load
            });
```

And i forgot to mention, that the selector and init is correct, as cursor:pointer is added to it automatically. The action however ... is another story :)

**Comment by marcwhitbread** [comment]
Ok, thanks. Just covering the basics before I dive into it. Let me get back to you with a fix.

**Comment by marcwhitbread** [comment]
Added public methods: autoSlidePlay, autoSlidePause to v1.1.66. Enjoy :)
