### ISSUE TITLE
Please keep master stable

### ISSUE THREAD

**Issue by lukewilde** [iosscripts/iosslider#115]
Hi there, the current state of master is very unstable. I had to spend a while digging through the history to locate a usable version.  The current HEAD on master contains numerous console.logs(). Version 1.1.8 (on the plugin's website) also suffers from a number of bugs.

**Comment by iosscripts** [comment]
Hi Luke, 

v1.0.35 is stable. v1.1+ had some major changes to core functions and are at the root of these issues.

I admit I screwed up badly rolling out some heavily updated code hoping I would be able to fix minor issues on the fly. I'm considering rolling back a month and a half of code if I can't get it back to the quality/stability of v1.0.35 in the next few days.

> Version 1.1.8 (on the plugin's website) also suffers from a number of bugs.
> 
> Can you share the ones you've found? I'm trying to clean them all up.

Thanks, 

Marc

**Comment by lukewilde** [comment]
Ahh excellent, I'll bear that in mind. I'm currently using v1.0.39 which seems pretty solid.

Where I was switching versions rapidly I've forgotten most of the issues I saw. I'll report what I remember though. 

Thanks for getting back to me.

**Comment by lukewilde** [comment]
I'm guessing that you changed args.currentSlideNumber to be 1 based instead of 0 based. If true, it would explain a lot of the issues I was having with the more recent versions.

**Comment by iosscripts** [comment]
> I'm guessing that you changed args.currentSlideNumber to be 1 based instead of 0 based. If true, it would explain a lot of the issues I was having with the more recent versions.
> 
> Yes. I had a discrepancy with goToSlide accepting a 1 based slide number but all the callbacks returning a zero based slide number. For consistency, everything is 1 based now.
