### ISSUE TITLE
Next and Previous arrows are too slow

### ISSUE THREAD

**Issue by lukewilde** [iosscripts/iosslider#116]
Pressing the next and previous arrows has a severe delay on mobile devices. This can be mitigated by instead triggering the event by listening for a 'touchstart'.

**Comment by iosscripts** [comment]
Not sure why I didn't do this a long time ago. I will add it an upcoming release. 

I will change click to touchstart for next/prev and slideSelector buttons.

**Comment by iosscripts** [comment]
Added in v1.1.11. Let me know if that's the functionality you had in mind.
