### ISSUE TITLE
Android tablet Full width doesn't resize on orientation change

### ISSUE THREAD

**Issue by sc0ttman** [iosscripts/iosslider#117]
Basically if you run Example 9 (Full-Width-Responsive-Height) on a Samsung Galaxy Tab or Kindle Fire and then change orientation, the image doesn't resize to the full width of the screen.
Know of any quick workarounds for this?

Thanks

**Comment by ColColonCleaner** [comment]
Marc, do you want me to submit problems with android too? Haven't been since you didn't say it was supported. Let me know :)

**Comment by iosscripts** [comment]
@sc0ttman Which browser? There is an orientation issue caused by a browser bug not reporting window width/height properly on resize/orientation change. I've tried to find suitable workarounds but with no successful results.

@cobeliga Sure, I fully support Firefox, Chrome, and Opera for Android. The only browser not fully supported is the "out-of-box" browser that ships with the above mentioned bug. If you find other issues, let me know :)

Related issue: #9

**Comment by sc0ttman** [comment]
Hey Marc. On the Galaxy I'm just using "Browser" and on Kindle fire it's just the basic Web Browser app they have.
Upon further investigation, the orientation change event is being called fine, but for some reason your "stageWidth" value will always return "600px" (or "800 in Tab) after the first orientation change. (even though the width is 1024 or 1280 in the Tab). So, it gets it right when it starts up in landscape, but once you make one change it will always return the portrait width.

**Comment by iosscripts** [comment]
> but for some reason your "stageWidth" value will always return "600px" (or "800 in Tab) after the first orientation change

That is the browser bug I'm talking about. In the Android browser called "browser" (or "internet" as mine is called on the SGS2), the width/height reported back to the JS on orientation change is incorrect.

If you try creating your own event and alert() the $(window).width(); when the event fires, you will see the bug. 

Not much the iosSlider script can do about a browser bug :S. 

The only workaround I can think of might be using a setTimeout(function() {}, delay); function within a custom orientationchange event which calls $('.iosSlider').iosSlider('update'); to try the calculations again with a delay applied.

**Comment by sc0ttman** [comment]
Okay yea, that seems to be a good enough fix for me for now. I will look around for some code to detect the browsers that have this bug. Thanks @iosscripts

**Comment by iosscripts** [comment]
No problem. I will take a look at the status of the issue around the net. Maybe some programmatic headway has been made since I last checked with a workaround.

**Comment by jaf0** [comment]
(not necessarily related to this package) i've had to use a 500ms delay before getting the dimensions for android 4.x (confirmed on Galaxy S3 (4.0.4))

**Comment by nicmare** [comment]
same problem with my Acer Iconia Tablet B1-A71. when i change orientation, document.width returns me the OLD width. in landscape it shows me portraitwidth and in portraitwidth it shows me landscapewidth?! LOL… with settimeout event i can wordaround this. thanks
