### ISSUE TITLE
'startatslide' set to number close to end of slides broken

### ISSUE THREAD

**Issue by sonalishahi20** [iosscripts/iosslider#118]
I have implemented a double slider in my project ( thumbnail one). Let me tell you my problem in detail. Suppose if there are 20 odd slides and you select 17th one out of 20 then thumbnail slider will cease to work. You can the simulate the issue in chrome for better clarity, assuming there are 20 images and you pass variable 'startatslide' as 17 then thumbnail slider will not work. 
Let me know the workaround for the same. Also, how to optimize the code if want to populate 120 slides as it is taking too long now. 
Really appreciate your help.

**Comment by iosscripts** [comment]
> 'startatslide' as 17 then thumbnail slider will not work. 

That is a bug I think. Do you have a test case or example that I can look at?

> Let me know the workaround for the same. Also, how to optimize the code if want to populate 120 slides as it is taking too long now. 

120 slides is too many slides for this script for this to the handle. There is a feature request (#111) which will hopefully increase the amount of slides which the script can handle.

**Comment by sonalishahi20** [comment]
Will share an example in a while.

**Comment by sonalishahi20** [comment]
Shared a demo file for issue no. 118.

Regards,
Sonali Shahi

**Comment by iosscripts** [comment]
Fixed in v1.1.17.

startAtSlide is now bulletproofed to start at a max offset even if the startAtSlide offset is set to initialize at a higher offset than reachable by the slider.

**Comment by sonalishahi20** [comment]
Thanks a ton Marc, will check it for sure!!
