### ISSUE TITLE
onSlideComplete isn't always fired.

### ISSUE THREAD

**Issue by sc0ttman** [iosscripts/iosslider#119]
On Chrome for Mac, if I drag a slide just past halfway and release, it will animate to the next slide, but not call the "onSlideComplete" callback function.

**Comment by iosscripts** [comment]
Good catch. Should be an easy fix. Give me a few hours to sort it out.

**Comment by sc0ttman** [comment]
Sounds good. I've noticed it not always being called on Android tablet devices as well. Mainly, Kindle Fire. Although, I think it's all part of the same issue. Just not always firing in general.

**Comment by iosscripts** [comment]
Resolved in v1.1.15
