### ISSUE TITLE
Next and Prev not working in Chrome

### ISSUE THREAD

**Issue by svpandae** [iosscripts/iosslider#120]
They are working fine in FF, IE, and Safari. Touch-screen works in Chrome, but the prev and next buttons are not. Any ideas?

**Comment by iosscripts** [comment]
Which OS are you testing Chrome on to reproduce the error? Which iosSlider version?

**Comment by svpandae** [comment]
Windows 7 SP1, Chrome v22, ios version 1.1.14

Settings and JS as follows:

$(document).ready(function() {

```
$('.iosSlider').iosSlider({
    desktopClickDrag: true,
    snapToChildren: true,
    navPrevSelector: '.prev',
    navNextSelector: '.next',
    autoSlide: true,
    infiniteSlider: true,
});
```

});

**Comment by iosscripts** [comment]
Thanks for the info. Does it work if you use $('.prev') and $('.next') in stead? 

Is in one of my demo's or a piece you built? Can you copy/paste your next/prev elements from your HTML? Thanks.

**Comment by svpandae** [comment]
I copied from your demo - 10-Multislide-Visible-Next-Prev.

I am new to jquery, so not sure how to call this using $('prev') and $('next'). Was hoping to try setting an "onClick" in a div to call a function to change the slide, but not sure how to do that...

<DIV CLASS='prev' style="position: absolute; top: 170px; left: 40px;"><IMG SRC=/images/slideLeftArrow.png BORDER=0></DIV>

<DIV CLASS='next' style="position: absolute; top: 170px; left: 865px;"><IMG SRC=/images/slideRightArrow.png BORDER=0></DIV>

**Comment by svpandae** [comment]
I pasted in the DIV elements above, but they appear to be rendering as HTML. Here they are again.

``` html
<DIV CLASS='prev' style="position: absolute; top: 170px; left: 40px;"></div>

<DIV CLASS='next' style="position: absolute; top: 170px; left: 865px;"></div>
```

**Comment by svpandae** [comment]
Just noticed - not working for me in Chrome in the example on iosscripts.com either (here it is not next and prev, but rather the little nav boxes at the bottom left).

On the other hand, it is working on my wife's computer - same OS and Chrome version. Perhaps there is something wrong with my browser. Will try to reinstall.

**Comment by svpandae** [comment]
After reinstall of OS and browser, all is working. Sorry for the distraction.

**Comment by svpandae** [comment]
Hmm. Not working again, this on top of a fresh OS install. It was working before, but now that I have re-installed most of my other applications, the problem has returned. Clearly not a general problem, but there is something causing this beyond just a bad install, I think.

**Comment by iosscripts** [comment]
Very interesting. Ary you using any browser addons/plugins?

**Comment by svpandae** [comment]
According to Chrome, no "extensions" have been installed.

I uninstalled WebEx and Adobe Acrobat v6 and rebooted. Still not working, but both of these could potentially have an impact on the browser behavior.

Other potential culprits include:
1. Java
2. Flash
3. .NET framework

Nothing else strikes me as likely to have any impact on Chrome.

**Comment by svpandae** [comment]
One other possibility - my lap top has a touch screen. Could be that there is some interference due to that. I am able to move the slides forward and back using the touch screen in Chrome and FF, but not IE.

**Comment by iosscripts** [comment]
That is definitely the problem. The script checks if the browser has touch enabled, and then falls back to click if it doesn't have it. 

Seeing as this is a very special case (a device with both mouse and touch support). Can I get you to open up jquery.iosslider.js and make a quick change?

Line 993: var clickEvent = isTouch ? 'touchstart.iosSliderEvent' : 'click.iosSliderEvent';

Change to: var clickEvent = 'click.iosSliderEvent';

**Comment by svpandae** [comment]
Beautiful. It works. Code change was at line 980, fyi.

**Comment by iosscripts** [comment]
Fantastic. Sorry, I think it's line 993 in v1.1.17. Either way, if it works then great! Let me know if you run into any new issues. I will close this issue.

**Comment by svpandae** [comment]
One new issue, it seems. Now in IE, if I click on the slide, prev and next stop working. I will experiment with this a bit before opening a new issue.

**Comment by svpandae** [comment]
Turned off desktopClickDrag, which seems to have solved the IE problem.
