### ISSUE TITLE
_site-demo - Slide number for selector should be -1?

### ISSUE THREAD

**Issue by alancwoo** [iosscripts/iosslider#121]
Hi Marc,
Not sure if this is correct but I noticed in the site demo and in my attempts that the slide selector is not working until I subtract 1 from `currentSlideNumber`

For example, in the [site demo](https://github.com/iosscripts/iosSlider/blob/master/_demos/_site-demo/index.html) it seems that line 45 should read:

`$('.sliderContainer .slideSelectors .item:eq(' + (args.currentSlideNumber-1) + ')').addClass('selected');`

Or have I done something wrong?

**Comment by iosscripts** [comment]
My fault. You're right. I will fix the demo.

**Comment by iosscripts** [comment]
Resolved in v1.1.15
