### ISSUE TITLE
Infinite slide

### ISSUE THREAD

**Issue by Morkesjelen** [iosscripts/iosslider#123]
Hi. Great plugin :)
I have to use the slider with 100% width
http://trisvart.host56.com/
As you can see here when I use the infiniteSlide method I have a blank space to either side of the slides.
What I'm trying to achieve is a loop that will fill the entire page, cloning the existing boxes.
How can I do that? I'm doing something wrong or the plugin doesn't support this feature?
Thanks :)

**Comment by iosscripts** [comment]
Hmmm. For infinite scrolling, the slides do not clone, they sort of leap frog each other as you move in both directions. So you will need to double/triple the slides being put into the slider to make sure they span the maximum width you are working with.

I found an oddity in the script that leaves some empty slides to the left of the slider on load when I tried it. I will need to patch that before it works 100%. Shouldn't take too long to fix. :S

**Comment by Morkesjelen** [comment]
Thanks for the quick response!
I tried to multiply the slides I have into the cycle but even If i do that I have blank spaces.

<img src='http://imageshack.us/a/img195/1748/schermata20121012a15355.png' >

**Comment by iosscripts** [comment]
Yep, to achieve that you will need to duplicate the slides manually like so: 

1 | 2 | 3 | 4 | 1 | 2 | 3 | 4 | 1 | 2 | 3 | 4

But as I said above, when I tried that I got a blank space to the left on initialization. The slides should automatically reorganize to put slide 1 in the center. I will need some time to fix that bug.

**Comment by iosscripts** [comment]
I added a fix in v1.1.16 for this issue. Check out _demo/_examples/7-Centered-Slides/3-Short-Slides/ for a working demo. Let me know if you are still experiencing issues.
