### ISSUE TITLE
Thanks for making such an awesome plugin!

### ISSUE THREAD

**Issue by tim-peterson** [iosscripts/iosslider#124]
Obviously this is not an issue but I just wanted to say thanks for making such an awesome plugin! It is really beautiful and exactly what I was looking for.

best regards,
tim

**Comment by iosscripts** [comment]
Thanks! and thank you for using it! :)

Do you have any cool projects you have used it on that you wouldn't mind sharing? I like to see how people are using it.

**Comment by tim-peterson** [comment]
I'm getting there, i'm making a media store and I'm hoping to use it for showing screenshots and for preview video or audio as iTunes and the App store do it.

will keep you posted

tim
