### ISSUE TITLE
Feature Request: Public method to get current slide.

### ISSUE THREAD

**Issue by sc0ttman** [iosscripts/iosslider#126]
Is there a way to do something like this?

```
var slideNum = $('div').iosSlider('getCurrentSlide');
```

**Comment by ColColonCleaner** [comment]
Not directly. as far as i know. It would be a good thing to consider though.

There is a different way of doing it though. use sliders onslidechange callback

``` js
function sliderChangeFunction(args)
{
    $.sliderPosition = args.currentSlideNumber;
}
//var now available at $.sliderPosition
```

and a different way without global var usage

``` js
function sliderChangeFunction(args)
{
    $(args.sliderObject).data('sliderPosition') = args.currentSlideNumber;
}
//var now available at $('yourSlider').data('sliderPosition');
```

Take note this will only update after the slider has been moved, if it hasn't these vals will be undefined, set them manually for starters.

**Comment by sc0ttman** [comment]
Thanks @cobeliga , I will use something like that for now.

**Comment by nicooprat** [comment]
+1 for this feature !

**Comment by kostja-me** [comment]
+1 for this feature!

**Comment by iosscripts** [comment]
v1.1.31 now supports this. All the data stored in the args array for callbacks is now available via $('.iosSlider').data('args');. 

So for the current slide: $('.iosSlider').data('args').currentSlideNumber;

Let me know if you run into any issues. Thanks for the feature request :).

**Comment by nicooprat** [comment]
Good news ! But cCalling the variable "args", a very common name, might cause some conflicts with other plugins, don't you think ?

**Comment by iosscripts** [comment]
Anything is possible I guess. I will be consolidating the jQuery.data() to one object eventually. 'iosslider' will be the name.

**Comment by ghost** [comment]
I am trying to attach a class name to the active slide but can't seem to get it to work. Anyone with ideas on how to pull this off?

**Comment by marcwhitbread** [comment]
@creativehub I presume you are trying to do it in a callback function?

``` js
$('.iosSlider').iosSlider({
    onSlideChange: function(args) {

        $(args.currentSlideObject).addClass('someClass');   

    }
});
```
