### ISSUE TITLE
Scrollbar problem

### ISSUE THREAD

**Issue by ghost** [iosscripts/iosslider#127]
Hello,

So I have a problem with the scrollbar, hopefully this isn't a real issue, I am a nooby with jquery.

Here is the problem: when used to scroll to the first slide, it makes everything dissapear. The scrollbar is contained in another div with a set width.

I uploaded everything so you can see the problem (hover firstimage than click to activate the slider).

http://sebastien-crapoulet.com/ca/

Cheers !

**Comment by iosscripts** [comment]
Thanks for the link.

This is a bug I think. Let me take a look at the code and I will get back to you with a fix. 

Sorry about that.

**Comment by ghost** [comment]
Hey, no problem of course ! It might also come from me.

Great work on this plugin.

**Comment by ghost** [comment]
Hey, I'm back again, doing more testing, and randomly for no reason, now when you click on the slider it goes back to the beginning, so its doesn't scroll properly.

Same link ( http://sebastien-crapoulet.com/ca/ old version can be seen here: http://sebastien-crapoulet.com/ca/old/ ), thought I'd metion it in case it's related.

**Comment by iosscripts** [comment]
@sebastien-crapoulet Hey, it looks like you've got some other jQuery issues going on that are unrelated to iosSlider. Every time I click on the slider, it's reloading via AJAX, so that can't be right.

**Comment by ghost** [comment]
Ah yep, just saw that, my bad !

2012/10/18 Marc Whitbread notifications@github.com

> @sebastien-crapoulet https://github.com/sebastien-crapoulet Hey, it
> looks like you've got some other jQuery issues going on that are unrelated
> to iosSlider. Every time I click on the slider, it's reloading via AJAX, so
> that can't be right.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iosscripts/iosSlider/issues/127#issuecomment-9564788.

## 

Sébastien Crapoulet

**Comment by sebastienrocks** [comment]
Has this ended up being fixed ? Cheers

**Comment by marcwhitbread** [comment]
@sebastiendesign not yet sorry. I got caught up in some other stuff and this got sidelined. I will re-prioritize it and take another look.

**Comment by ghost** [comment]
No problem, thanks a lot.

2012/12/17 Marc Whitbread notifications@github.com

> @sebastiendesign https://github.com/sebastiendesign not yet sorry. I
> got caught up in some other stuff and this got sidelined. I will
> re-prioritize it and take another look.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iosscripts/iosSlider/issues/127#issuecomment-11443286.

## 

Sébastien Crapoulet

**Comment by iosscripts** [comment]
@sebastiendesign Can you upload the demo again? I would like to take another look at the source.

**Comment by iosscripts** [comment]
v1.1.51 should have a fix for the drag gable scrollbar issue when snapSlideCenter is true. Sorry this took so long, it was a hard one to pinpoint.
