### ISSUE TITLE
slider snaps slides to left when you click on one 

### ISSUE THREAD

**Issue by Batmensch** [iosscripts/iosslider#128]
The slider is set up to display 3 slides out of N.  There are only two slides in it presently.  When loaded both slides are flush left.  When you click on either slide they both jump to flush right.  This doesn't seem to happen with 1 slide only.  

I've tested this with chrome and firefox, and with jquery 1.4 and jquery 1.8.2.  iosslider 1.1.15.

Example:

http://devenv61-temp.aldon.com/slider-2slide/
1. load page
2. mouse-click on either slide
3. slides jump to right

**Comment by iosscripts** [comment]
Sort of a bug. When the combined slide widths are shorter than the width of the iosSlider div, odd things can happen. 

What should be happening is the slider should be disabled because the content does not need to slide.

**Comment by Batmensch** [comment]
Unfortunately if we just disable the slider the 2nd slide becomes invisible.  Do we need to maintain two separate ways to display them?

**Comment by iosscripts** [comment]
No, you shouldn't need to disable it manually. The script should still display the items properly either way, but the touch/click interaction will be disabled due to lack of content. 

This is a bug. I will take care of it.

**Comment by Batmensch** [comment]
merci!

**Comment by mishimu** [comment]
Hello, I am having the exact same problem with my slider. Have you made a fix for this yet?

Thanks.

**Comment by iosscripts** [comment]
@mishimu Not yet. Today some time probably.

**Comment by iosscripts** [comment]
@mishimu @Batmensch Fix applied in v1.1.19. You can download the latest version from the master branch here:  https://github.com/iosscripts/iosSlider/zipball/master

I will reopen if either of you are still experiencing issues.

**Comment by mishimu** [comment]
Thank you! That's perfect. I also have another small issue - should I start a new thread?

**Comment by iosscripts** [comment]
@mishimu If it's not related to this one, create a new issue. Thanks.

**Comment by Batmensch** [comment]
Looks good to me, thanks!
