### ISSUE TITLE
Navigation Selector (pagination) - selects unwanted slide when dragging 

### ISSUE THREAD

**Issue by mishimu** [iosscripts/iosslider#130]
Hi, I've looked through all previously raise issues and didn't come across anything similar. But apologies if it's already been mentioned!

So in Demo 5-Double-Slider-Gallery if you try and drag the pagination across, it selects the thumbnail you happened to click on and slides to that image.

Is there a way of making it so that it just moves the pagination and doesn't select the slide?

I hope that made sense, thanks.

**Comment by iosscripts** [comment]
Thanks for submitting this issue :)

This issue is related to issue #133. Take a look at my last comments to see which jQuery versions are able to support this feature. v1.1.22 now works as expected.
