### ISSUE TITLE
Navigation Selector (pagination) - always keep selected thumbnail in view

### ISSUE THREAD

**Issue by mishimu** [iosscripts/iosslider#131]
In the demo 5-Double-Slider-Gallery is it possible to have the selected thumbnail always in view? At the moment as you scroll through all the big images in the slideshow, it highlights the correct thumbnail however it goes out of view in the pagination. The user then has to scroll the pagination to find out where they are.

**Comment by iosscripts** [comment]
Thanks for submitting this issue. I disagree that this is an issue with the iosSlider functionality specifically. Some custom JavaScript in conjunction with iosSlider callback functions (onSlideChange/Complete) should be sufficient to get this working as desired.

It would be valuable to update this demo with this customized functionality added. I will add it.

**Comment by iosscripts** [comment]
In the _demos/_examples/5-.../ folder of the download package. There is an example of this.
