### ISSUE TITLE
Feature Request: onSlideEnd

### ISSUE THREAD

**Issue by sc0ttman** [iosscripts/iosslider#132]
Essentially the opposite of onSlideStart.

The reason this would be needed is that I would like to set a slide's opacity to something when a user has started moving the carousel, the problem is that if they let the slide snap back to their original position, then the onComplete callback doesnt fire, but I have no way of setting the original slide's opacity back to 100%. There is no callback for onAnimationEnd.

I would like a callback for when the slider has stopped moving, or when a user has stopped dragging. 

Is this possible?

Thanks

**Comment by iosscripts** [comment]
onSlideComplete should be firing either way. So if it isn't, then you found a bug. Which version are you running?

**Comment by sc0ttman** [comment]
I'm using 1.1.18

Yea, onSlideComplete doesn't seem to fire unless the slide is different. If it could always fire, that way I could check if the slide has changed myself.

Thanks

**Comment by iosscripts** [comment]
onSlideComplete now fires whether a slide is changed or not.

Added new variable to callback array: slideChanged (boolean). Value will be true if changed and false if released on same slide. This wont apply to your situation but will be valuable for a situation like the iosscripts.com homepage where I only want to animate the text when the slide is changed.
