### ISSUE TITLE
Drag fires click on links

### ISSUE THREAD

**Issue by nicooprat** [iosscripts/iosslider#133]
On desktop, when dragging the slider with the mouse, a click event is fired on the target element, which is not the expected behavior. The click event should only be fired when no drag has started.

I wrote a quick fix :

```
var sliding = false;

$('#popular_recipes').bind('dragstart touchmove',function(e)
{
    sliding = true;
});

$('#popular_recipes').bind('dragend touchend',function(e)
{
    if( sliding ) e.preventDefault();

    sliding = false;
});
```

(Btw, it would be cool to have the possibility to access some kind of a "isSliding" public property of an iosSlider object.)

Edit: looks like my trick doesn't work very well... It seems like there's a part in your code that should prevent click in certain case, but I'm wondering if it really still works ?

**Comment by iosscripts** [comment]
> looks like my trick doesn't work very well... It seems like there's a part in your code that should prevent click in certain case, but I'm wondering if it really still works ?

Yes, your right. I'll take a look at my code. It's actually not as easy as you suggest above. You need to account for click bound inline (onclick = ''"), using jQuery bind(), and anchor tags. Quite tricky actually. I thought I had it working but perhaps I broke something :S.

**Comment by iosscripts** [comment]
I have a solution for anchor links and inline onclick events. 

Events attached via jQuery.bind() or the like seem to be giving me some trouble. I can't seem to find a way to track the events bound to an object. I'll keep digging :S.

**Comment by iosscripts** [comment]
v1.1.22 now handles jQuery bound events as well. The only restriction is that this function was only accessible jQuery v1.6 and later. Let me know if you are still seeing issues with the new version.

**Comment by nicooprat** [comment]
Hi,

Sorry I don't know why but I didn't received any Github notifications ! Thanks for your reactivity though.

I'm afraid but the bug still occurs. I'm using jQuery 1.8.2 and iosSlider 1.1.28.

<a href="http://bit.ly/TZQTZJ" rel="nofollow">You can see it live here.</a> (The "les recettes récentes" slider on the home).

I'm having this issue on both desktop (click) and mobile (touch) devices.

My code is very simple :

```
            $('#popular_recipes .iosSlider').iosSlider({
                snapToChildren: true,
                desktopClickDrag: true,
                snapSlideCenter: false,
                startAtSlide: 2,
                stageCSS: { overflow: 'visible' }
            });
```

Any idea ?

**Comment by nicooprat** [comment]
To be more precise I did some more tests :
- on desktop the link is not fired if I don't release the mouse over the element (even if the click started on it) : not so bad :/
- on iPhone simulator on Mac the link is fired even if the mouse is released somewhere else : bad :(
- on a real iPhone it just works as expected : good :)

**Comment by mishimu** [comment]
Hi, 

Thanks for taking a look at that for us! However I'm experiencing the same problems as nicooprat - the link is still fired on iPads.

I'd really appreciate it if you could reassess this issue again please!

**Comment by nicooprat** [comment]
One more precision : apparently, I'm having this issue on Chrome (desktop) only if the console is opened (with "emulate touch controls" on). I was sure to have checked it without console opened... but it looks like I didn't. Weird.

**Comment by nicooprat** [comment]
@mishimu Did you test it on a real iPad or on the emulator ?

**Comment by iosscripts** [comment]
@mishimu How are you binding the click event? Which iosSlider version? Which browser? Can you give me a link to a demo of the issue in quesiton?

**Comment by mishimu** [comment]
Hi, here are the answers to your questions:
1. Yes I tested it on a real iPad
2. Here is the code:
   
     $('.iosSlider').iosSlider({
             snapToChildren: true,
             desktopClickDrag: true,
                 keyboardControls: true,
             navSlideSelector: $('.slider .button'),
             onSlideChange: slideChange,
             responsiveSlides: true,
             responsiveSlideContainerHeight: true,
             responsiveSlideContainer: true
     });
   
     $('.doubleSlider-2').iosSlider({
             desktopClickDrag: true,
             snapToChildren: true,
             stageCSS:{ position: 'fixed', bottom: '0', top: 'auto', left: '0', overflow: 'hidden', zIndex: 1 }
     });
3. The latest iosSlider version with jQuery 1.7.
4. Browsers: on Chrome and iPads - the two I need to get it to work on.
5. Demo: Could you tell me where I can upload my code please? 

Thanks,

Mina

**Comment by iosscripts** [comment]
Thanks for the info. That will really help.

> Demo: Could you tell me where I can upload my code please?
> zip and email it over to contact@iosscripts.com

**Comment by iosscripts** [comment]
Found workaround to issue with navSlideSelector firing on drag. Found immediate workaround by using goToSlide bound by jQuery.bind() manually in stead.

**Comment by theloveofcode** [comment]
Put me down as having this problem as well.

**Comment by mrse** [comment]
Having issues with this slider on iPhone.  I only have 1 image in the slider which is a clickable/linked image.  When the image is clicked, you should be taken to the specific product.  However, on iPhone, when image is clicked, the image just bounces and reloads without taking you to product page.  Please help!
