### ISSUE TITLE
Blurry image on retina displays in Safari

### ISSUE THREAD

**Issue by techee** [iosscripts/iosslider#135]
I have an issue with blurry images in the slider on "retina" displays under Safari. This is both iPhone/iPad retina displays and MacBook Pro retina. This issue appears only in Safari, not Chrome, but since I develop iOS apps, I need the web pages to look good on iPhones and iPad where only Mobile Safari is permitted. I've tried your sample pages but all of them exhibit the same issue so I don't think there's something wrong with my page.

Here's the comparison of Chrome/Safari rendering

https://www.dropbox.com/s/h42y1ad4l8hgbox/comparison.png

and here's the page:

http://www.techet.net/sysstat/

**Comment by iosscripts** [comment]
The blurriness can sometimes be caused by ram issues sometimes.

Take a look at this: http://stackoverflow.com/a/8841704/1027897 

Basically, the above link will tell you to close open processes (double tap home button and press minus sign on each) and close browser tabs. Can you confirm that the issue is still occurring after doing this?

Also, can you provide me your iOS version and iPad/iPhone version?

I have been able to fix this issue before by adding this to the head:

``` html
<meta name = "viewport" content = "width=device-width, minimum-scale=1, maximum-scale=1">
```

This only works in some cases.

**Comment by techee** [comment]
No, this isn't the case - I've tried what you propose but it doesn't fix the issue. My testing devices are iPod Touch with iOS 5.1.1, iPad 3 with iOS 6 and Retina MacBook Pro with Mac OS X 10.8.2. 

Just to clarify - I use images with double resolution i.e. for images which are displayed as 320x320 I use 640x640 images. On non-retina display they are scaled to 320x320, on retina displays the resolution stays, just the density of the pixels is, or should be doubled. This is actually where I think the problem lies - that during the transformations you do, the 2x resolution is lost (it looks the same way as if is scaled down the 320x320 image and then upscaled it back to 640x640). In other words, it looks as if I was displaying 320x320 images upscaled twice instead of displaying 640x640 images.

Have you tested your library with @2x images?

**Comment by techee** [comment]
Found the problem - it's this:

http://stackoverflow.com/questions/10841198/setting-webkit-perspective-blurs-ipad3-screen

I've checked your code and at several places you set

'webkitPerspective': 1000

After removing it, the blurry image issue is fixed. What's the purpose of this settings in your code?

**Comment by iosscripts** [comment]
Interesting. I had put it in to resolve issues surrounding a display "flickering" when moving around the slider. I found the solution here: http://stackoverflow.com/questions/2946748/iphone-webkit-css-animations-cause-flicker

When I applied webkitPerspective: 1000 it fixes the problem.

Can you confirm that it fixes the blur with any other values? As in this issue: https://github.com/iosscripts/iosSlider/issues/97

**Comment by techee** [comment]
I confirm 1.1.25 fixes the problem. Thanks!
