### ISSUE TITLE
Unexpected behavior on drag evenr with few items.

### ISSUE THREAD

**Issue by VitalyPankin** [iosscripts/iosslider#137]
Slider is going crazy, when total width of all items less then container width.

**Comment by iosscripts** [comment]
I recently patched that in a version that is only available on github at the moment. Try this and let me know if you are still seeing issues. https://github.com/iosscripts/iosSlider/zipball/master

**Comment by VitalyPankin** [comment]
It's okay, but I need to center it. I made a addon script to make it true,
but i find out an another problem.
here the page,meratech.ru/ricco/catalog.htmfile:///O:/Backup/Ricco-style/html/catalog1.htm
after
resize window something goes wrong and it need to click twice to call event
handler(not always, try for a while to detect the bug). problem part of
code somewhere in mouseup hadler(the exact problem code below). What for is
this code for, can you please tell me? i try to remove it and it seems like
workable.

if(parseFloat($().jquery) >= 1.8) {
 allScrollerNodeChildren.each(function() {
 var clickObject = $._data(this, 'events');
 if(clickObject != undefined) {
if(clickObject.click != undefined) {

if(clickObject.click[0].namespace != 'iosSliderEvent') {
 if(!xScrollStarted) {
return false;
}
 $(this).one('click.disableClick', helpers.preventClick);
var handlers = $._data(this, 'events').click;
var handler = handlers.pop();
handlers.splice(0, 0, handler);
 }
 }
}
 });

} else if(parseFloat($().jquery) >= 1.6) {

allScrollerNodeChildren.each(function() {
 var clickObject = $(this).data('events');
 if(clickObject != undefined) {
if(clickObject.click != undefined) {

if(clickObject.click[0].namespace != 'iosSliderEvent') {
 if(!xScrollStarted) {
return false;
}
 $(this).one('click.disableClick', helpers.preventClick);
var handlers = $(this).data('events').click;
var handler = handlers.pop();
handlers.splice(0, 0, handler);
 }
 }
}
 });

} else {
}
2012/10/23 Marc Whitbread notifications@github.com
