### ISSUE TITLE
Make the scrollbar draggable

### ISSUE THREAD

**Issue by iosscripts** [iosscripts/iosslider#14]
Add an option to be able to drag the scrollbar.

**Comment by TheDesignSmith** [comment]
Would love for this to be implemented.

**Comment by iosscripts** [comment]
It's a good idea actually. I could probably put something together to get this working. Might require some testing though.

**Comment by dwehrmann** [comment]
Why not make it scrollable as well? I'd love to be able to scroll through the slides using the mouse wheel (without having the pesky scrollbars of course)

**Comment by marcwhitbread** [comment]
I've had the mouse-wheel event requested a few times. Would this only apply to mice that have wheels that can scroll horizontally?

**Comment by dwehrmann** [comment]
actually not. I think the best solution would be to translate the y-axis to the x-axis so that also users without horizontal mouse wheels can use the horizontal version. I've seen this somewhere in another script but can't remember where it was.

**Comment by marcwhitbread** [comment]
Sounds good to me. I'll open the mouse-wheel feature up in a new issue.

**Comment by dwehrmann** [comment]
Great, thanks. Also thank you for your help with issue #54. Great work.

**Comment by TheDesignSmith** [comment]
That would be great! Thanks, Marc.

On Sun, Jul 15, 2012 at 12:48 PM, Marc Whitbread
reply@reply.github.com
wrote:

> It's a good idea actually. I could probably put something together to get this working. Might require some testing though.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iosscripts/iosSlider/issues/14#issuecomment-6993462

## 

Jeremy Smith
www.jeremysmithdesign.com
847.452.0756

**Comment by iosscripts** [comment]
I have the basic functionality in now. Using the new option 'dragScrollbar: true' in your iosSlider call will make the scrollbar dragable. I added a new test case in the _demos/_benchmarks/_general/index.html

I need to polish up some of the physics still and maybe the desktop events... but it's workable :). If you end up trying it out, let me know what you like/don't like about it.

**Comment by TheDesignSmith** [comment]
Nice! I'll try it out.

**Comment by levischooley** [comment]
I'm trying to use the draggable scrollbar functionality in iosSlider, but it doesn't seem to be working for me. I've opened the _demos\_benchmarks\_general\index.html file, and tested this functionality in IE9, Firefox 19, and Chrome 25 with iosSlider version 1.2.0 and it doesn't seem to be working.

**Comment by marcwhitbread** [comment]
Your right, it doesn't seem to be working for me either. Let me get a fix out.

**Comment by marcwhitbread** [comment]
I seem to have broke functionality during some code consolidation in v1.1.60. I have fixed the bug in v1.2.1
