### ISSUE TITLE
Issue with chrome 

### ISSUE THREAD

**Issue by naeluh** [iosscripts/iosslider#142]
Hi, 

I am trying to use the ios slider to create an html slider I was able to create a stable version in firefox but it is acting weird in chrome. Here is the url http://www.theconfluencegroup.com/newtcg/#news I am not sure why it would work in firefox but not in chrome. I altered the themeing slightly but I was planning on altering it more but got hung at this point. Please let me provide any info that would help fix this error so I can continue working. 

thanks 

Nick

**Comment by naeluh** [comment]
I mean basically it just jumps to the next slide instead of using the pull and drag motion. 

thanks

**Comment by iosscripts** [comment]
Can you elaborate on what you mean by it just jumps to the next slide? you have autoSlide enabled so it will move between slides automatically.

**Comment by naeluh** [comment]
Thanks for the quick response. When I try to click the slide, to create the click and drag motion on chrome it just jumps to the next slide very quickly not allowing me to click and drag to the next slide. If you go the page and try and click the slide you will see it happen. I will try disabling autoslide and see if that does anything but basically I cant click the div without it jumping to the next slide. thanks again

**Comment by iosscripts** [comment]
When you click/drag and release in the direction of the next/prev slide, if the velocity when released is beyond a velocity threshold, it will snap in that direction.

Are you testing desktop or mobile chrome? Which version? 

Which iosSlider version?

**Comment by naeluh** [comment]
Thanks again for the quick response. Yes ok that makes sense. I guess I could adjust the velocity but the thing is that it works in firefox desktop 
I am using desktop chrome for testing and Version: v1.1.15 (10/10/2012) of ios slider. 

thanks again

**Comment by iosscripts** [comment]
Ok. Actually both browsers are doing the same thing, but Chrome/Safari register more drag events because they tend to run more efficiently. This can cause a difference in the velocity calculated, and therefore possibly a different snapping result when released.

**Comment by naeluh** [comment]
Thanks ! So how can I change the velocity for those specific browsers ? 

thanks

**Comment by nyquizt** [comment]
I have kind of the same problem in Chrome. Suddenly it started to jump 2 slides instead of one. Worked perfect before, and it's the same problem on 2 different websites where I use the slider. 
Works perfect in FF and Safari. Not in IE tho..

**Comment by nyquizt** [comment]
NVM, updating to the latest version of jquery.iosslider.js fixed it! Thanks.

**Comment by iosscripts** [comment]
@Morkesjelen this issue is closed. Please create a new issue describing your issue specifically, with a demo if possible. And which browsers it's working/not working in.

**Comment by naeluh** [comment]
Yeah its weird cause I have got it to work and then it came back again but  velocity is weird onclick in webkit still Id create a new issue so we can get this resolved thanks
