### ISSUE TITLE
Scroller drag issue

### ISSUE THREAD

**Issue by sc0ttman** [iosscripts/iosslider#143]
When scroller is hidden initially because the content is smaller than the slider width, and then the window is shrunk down, the scroller appears but doesn't function.

I noticed that when you try add the drag event to the slider when it is initially hidden, it isn't finding the node properly.

```
// line 1550
if(settings.scrollbarDrag) {
  console.log("Add scrollbar drag", scrollbarBlockNode)
  touchSelection = touchSelection.add(scrollbarNode);
  touchSelectionMove = touchSelectionMove.add(scrollbarBlockNode);
}
```

scrollbarBlockNode is undefined.

**Comment by iosscripts** [comment]
Thanks for finding that. It's now fixed in v1.1.28.
