### ISSUE TITLE
Width & height issue

### ISSUE THREAD

**Issue by patriklund** [iosscripts/iosslider#144]
Hi. I would like to set the height & width of my slider to 100%, and not i pixel. But when i set the width and height to 100% my page becomes blank.

Why is that? According to the documentation setting the height and width in pixel is optional.?

/Patrik

**Comment by iosscripts** [comment]
Can you provide the CSS of your slider?

**Comment by patriklund** [comment]
Here it is. It works with this code, height and weight in pixel, but if i change my values to 100% my page goes blank.

.iosSlider, .slide {
    width:800px;
    height:400px;
}

#wrapper {
    position:absolute; z-index:1;
    top:1px; bottom:1px; left:0;
    width:100%;
    background:#fff;
    overflow:auto;
}

#scroller {
    position:absolute; z-index:1;
    -webkit-touch-callout:none;
    -webkit-tap-highlight-color:rgba(0,0,0,0);
    width:100%;
    padding:0;
}

.scroller {
    position:absolute;
    -webkit-tap-highlight-color:rgba(0,0,0,0);
    width:100%;
    padding:8px 0px 12px 8px;
    font-weight:normal;
    text-shadow: 0px 0px 0px;
    color:#fff;
}

.scrollable {
    background:#434b5c;background:-webkit-gradient(linear,left top,left bottom,from(#434b5c),to(#394152));
    position: absolute;
    padding:8px 0px 12px 8px;
    top: 0px;
    left: 0px;
    right: 0px;
    bottom: 0px;
}

**Comment by iosscripts** [comment]
Hmmm. I'm not sure how you've done it, but here's my HTML/CSS.

``` js
.container {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
}

.container .iosSlider {
    overflow: hidden;
    width: 100%;
    height: 100%;
}

.container .iosSlider .slider {
    width: 100%;
    height: 100%;
}

container .iosSlider .slider .item {
    width: 100%;
    height: 100%;
}
```

``` html
<div class = 'container'>
    <div class = 'iosSlider'>

        <div class = 'slider'>

            <div class = 'item item1'></div>
            <div class = 'item item2'></div>
            <div class = 'item item3'></div>
            <div class = 'item item4'></div>
            <div class = 'item item5'></div>

        </div>

    </div>
</div>
```

**Comment by patriklund** [comment]
Thank you, that worked, it seemed that the container did the work.
