### ISSUE TITLE
Problems with slider and orientation change?

### ISSUE THREAD

**Issue by lquantz** [iosscripts/iosslider#145]
We're using the iosSlider on mobile web projects and it's great.  One problem however is that when we change the orientation of the phone/tablet, the slideshow goes crazy-- instead of moving gently from slide to slide it jitters between them, and sometimes stops on a blank piece of screen rather than a slide.

If we enter our page in a given orientation --landscape or portrait, makes no difference-- things are fine.  But when the orientation changes the slideshow degenerates.  The slideshow in our case is being used in jQuery mobile and viewed on iOS4 in Safari.  I'm glad to give additional information if you need it.

**Comment by iosscripts** [comment]
I have seen a lot of issues when using iosSlider with jQuery Mobile in the past. This is a bit of a complex issue, would you be able to provide me with a demo so I can see/understand the issue a bit better?

**Comment by lquantz** [comment]
I'll be happy to provide snippets of what we're doing, thanks for the offer.  I should note that this is only a problem when autoSliding is on-- if it isn't and people slide only by hand then changing the orientation is no problem, things work great.

In the meantime, may I ask if it's possible to stop a slideshow that's currently underway?  I looked at the plugin's source code and added a 'pauseSlide' method and tried to stop a currently moving show by calling clearTimeout() on each element in the autoSlideTimeout array.  Previously I tried calling helpers.autoSlidePause(), but neither approach worked, the jittery slideshow continued on an orientation change.

I also used the autoSlideToggleSelector attribute when initializing the slider, and set it to a DOM element using a jQuery selector-- << autoSlideToggleSelector : $('#myDiv') >>

When I triggered a click event on $("#myDiv") from code the slideshow continued, so I'm not sure how to stop a currently running slideshow?

**Comment by neilkyoung** [comment]
Hey, great job on the plugin. It is really good!

I am having the same problem with this issue. When the browser screen orientation changes the slideshow goes crazy with the auto slide switched on.

Tried locking and destroying before reconfiguring or updating and the problem still exists. I am guessing that the timeouts for the auto slide are not cleared ?

For now I have switched off auto slide but would really like this functionality.

Any ideas how I can amend the source code to achieve this ?

I am not using JQuery Mobile.

Many Thanks

**Comment by marcwhitbread** [comment]
@neilyoung2013 let me take a look at this and see if I can reproduce it. I've never experienced that particular issue.

**Comment by lquantz** [comment]
I agree with Neil about the terrific work on this slider, as well as (unfortunately) the reorientation problems.  When I first posted my note I tried adding some code to the plugin, but it didn’t work in the end.  I tried something along Neil’s lines of clearing the timeouts.

Here’s what I added, in the hopes that it might help in the investigation:

```
                            pauseSlide: function () {
                                            $.each(autoSlideTimeouts, function(index, slide) {
                                                            clearTimeout(slide);
                                                            clearTimeout(autoSlideTimeouts[slide]);
                                            });
```

….whenever the orientation changed on the device I would call ‘pauseSlide’ on the slider, but regrettably it simply didn’t do what I’d hoped.

-Larry

**Comment by isuftin** [comment]
This issue has been closed but I'm not sure that anything has been done about it? I'm having this same issue during orientation change and have not yet seen a fix.
