### ISSUE TITLE
handle the bullets when there are slides in large number

### ISSUE THREAD

**Issue by fatemak** [iosscripts/iosslider#148]
I am using iosSldier and its working fine when i have about 10 slides but when the number of slides increase the bullets at the bottom are not visible for the slides of higher number. please suggest some workaround so that the slide which is visible its bullet is also visible at the bottom

**Comment by iosscripts** [comment]
I assume we are talking about one of my demos. I will answer accordingly.

You must add more bullets in the HTML, and account for the new bullets by expanding the bullet container div width to account for more bullets via CSS.

**Comment by fatemak** [comment]
No my problem is when the number of bullets are that much that it exceeds the page width. Then is there any way so that i can show bullets with dots in between and the last bullet in the last. Fo eg.

O O O O O O O O ........O O

Here assuming the 'O' are bullets . Becoz i have about 70 to 100 slides and the page width is not that much and i dont want the bullets to come in the second line.

**Comment by iosscripts** [comment]
This functionality isn't built in actually, so you will have to write the custom JS to show/hide specific dots. I am willing to help with any iosSlider related issues, but this is a custom JS problem. 

If you need JS coding assistance, I do consulting as well. Email contact@iosscripts.com if you are interested in going down that route.
