### ISSUE TITLE
Selectors and Next/Prev Problem in IE

### ISSUE THREAD

**Issue by nyquizt** [iosscripts/iosslider#149]
For some reason the slider snaps to in-between two .items when i'm using IE 9. Also both the selectors and next/prev is not working properly. Next/Prev slides to wierd parts of the slider and gets stuck between two slides.

Everything works perfect in FF, Chrome and Safari, both in OSX and Windows. So it seems like the problems lays in IE. 
Couldn't find any documentation or reports about this..

Used Java:

```
        $(document).ready(function() {

            $('.iosSlider').iosSlider({
                snapToChildren: true,
                infiniteSlider: true,
                keyboardControls: true,
                responsiveSlides: true,
                responsiveSlideContainer: true,
                navNextSelector: $('.next'),
                navPrevSelector: $('.prev'),
                navSlideSelector: $('.selectors .item'),
                onSlideChange: slideChange
            });

        }); 

        function slideChange(args) {

            console.log(args);
            $('.selectors .item').removeClass('selected');
            $('.selectors .item:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');

        }
```

**Comment by iosscripts** [comment]
Can you provide me your full HTML/CSS as well? If you could zip a test case and send it over to contact@iosscripts.com that would certainly speed things up :)

**Comment by nyquizt** [comment]
Sent! :)

**Comment by iosscripts** [comment]
@jakeob thanks for the code. I'm not sure why, but when I removed the modernizer include, it started working properly. Are you sure you absolutely need to include that script?

**Comment by nyquizt** [comment]
Oh, never thought of that could be the problem.. Weird. I'm pretty sure I don't need modernizer for this project, so it should be fine. Please let me know if you figure out exactly what's causing the prob. Thanks again!

**Comment by nyquizt** [comment]
Hmm.. just removing
`<script src="js/modernizr-2.5.3-min.js"></script>`
didn't fix it for me.. Did you do anything more? Do I have to activate IE somewhere in the iosslider.js?

I'm testing in IE 8 on a PC.

**Comment by iosscripts** [comment]
Final issue resolution was console.log() call in JS breaking IE
