### ISSUE TITLE
Click link Problem in chrome, fix inside

### ISSUE THREAD

**Issue by PPP01** [iosscripts/iosslider#151]
Hi, there is an issue in every chrome browser i've tested (win, mac).

chrome fires mousemove, if a link inside a slide is clicked (why ever) - so the click gets prevented, cause "isMouseDown" is true and so xScrollStarted gets true.

I've fixed that with an extra check on e.webkitMovementX/Y (line 1739)
if(!isMouseDown || (typeof e.webkitMovementX != 'undefined' || typeof e.webkitMovementY != 'undefined') && e.webkitMovementY === 0 && e.webkitMovementX === 0) {

This works and has (afaik) no side effects - don't know if it's the best solution

LG
Patric

**Comment by iosscripts** [comment]
I'm not sure I understand the issue 100%. What are you expecting to happen when you do x? What do you think should happen when you do x? I'm not sure what "x" is yet.

Some additional info which may be related to your issue (but might not). If the horizontal scroll has started (ie. the mouse is down and dragging has begun), clicks will be prevented. This is so that a user can scroll content with a large actionable areas without accidentally clicking.

**Comment by PPP01** [comment]
Hi, the problem was, that it is hard to open a link inside a slide with chrome. 
The click (without scrolling) gets always prevented, cause chrome fires mousemove though there was no movement, just a click. To prevent that, now i check the webkitMovement and everything works fine.

**Comment by iosscripts** [comment]
Thanks for the clarification. What type of "link" are we talking about? inline onclick? anchor tag? jquery.bind('click')? Perhaps a link to a demo would help me see/understand the issue.

**Comment by PPP01** [comment]
Hi, i did a demo:
http://schep.de/slider-demo/

But i understand your irritation. First i tried it with your demo, and it works normal.
So i've made a demo with a simplified version of my problematic slider and though it is simplified, the problem occurs.
Click on the links and they will not open every time. Sometimes chromes fires mousemove, when a link was clicked.
I do not know why! Hope the demo helps.
LG

**Comment by iosscripts** [comment]
Odd. I still can't see it in your demo :(. Do you have any touch plugins or addons that might effect the interactivity? Sorry, grasping at straws now.

If not, I might just leave it at that. You are the only person to experience it so far, and you already patched it! :D

**Comment by DerekCS** [comment]
We are experiencing this issue as well under Chrome 23.0.1271.64 where we have a slider on the homepage containing three slides, each slide containing a link to an internal page. The link would arbitrarily work and not work. We saw this whether the slide was moving or not.

PPP01's patch demo links are not working in Chrome for us.

Adding a redundant onClick seems to handle the issue.

&lt;a href="url" onClick="location.href='url'"&gt;LINK&lt;/a&gt;

**Comment by berndslinger** [comment]
it's the same here, Chrome Version 23.0.1271.64
all images on the following page are linked: http://dev.alexa-dahmen.de/test.html
the links work in FF, Safari and IE with a single click; in Chrome only with a doubleclick; even onclick="..." doesn't help

Thanks in advance!

**Comment by iosscripts** [comment]
@berndslinger @DerekCS What version are you running? I patched a double click issue in v1.1.33 a few days ago.

**Comment by berndslinger** [comment]
I've downloaded it today from http://www.iosscripts.com/iosslider/, the zip file is called jquery.iosslider-1.1.32.zip
Ok, I will try version 1.1.34

**Comment by berndslinger** [comment]
sorry, no difference with version 1.1.34

**Comment by iosscripts** [comment]
@berndslinger thanks for the quick test. I will try and isolate your issue and get back to you :)

**Comment by PPP01** [comment]
Hi, good to see that's not only me. I also tested it with a complete new blank chrome (23.0.1271.64 m). It's the same.

I changed today my demo a bit. Now i prevent every link, and throw a debug msg on click.
I also added a debug msg [console.log(...)] at line 1742 (after the return false on mousemove). A normal click should never end here. But i get several debug messages. I did a screenshot:
http://schep.de/slider-demo/iosslider.png

@DerekCS 
The links in my demo (patched) won't open, cause i prevent now all clicks on them.
You can try this js (it's without debug msg):
http://schep.de/slider-demo/jquery.iosslider_patched.js

LG
Patric

**Comment by DerekCS** [comment]
@iosscripts We are currently running v1.1.14 on jQuery 1.4 Will try the newer version.
@PPP01 thanks, will try that.

**Comment by iosscripts** [comment]
Very odd behavior indeed. And it gets weirder. Take a look at the browser tooltip that shows when you stop over top a link. I have noticed that when this tooltip is showing, mousemove is being fired. When it hasn't shown, the link functions as normal. I have confirmed it in a demo I made and @PPP01's demo. I have also been able to fix them both by removing the alt text on the links... 

Can you take a few moments and confirm this behavior on your end? This would have to be considered a browser bug I guess. 

Perhaps I will include a workaround in the source to strip out the alt attribute on anchor tags within the slider. Would that work or is that too intrusive?

**Comment by PPP01** [comment]
Hi, i can confirm it. Without a title attribute, no mousemove is fired. Looks hardly like a browser bug.
But to remove all title tags is too hard in my opinion. Though title tags mostly used for SEO and it wouldn't be harmed, any web accessibility would be destroyed. 

Isn't it easier to use my workaround, till the chrome bug is fixed? Or has it any side effects, i do not see?

**Comment by iosscripts** [comment]
It is 100% a browser bug. Browser tooltips should not trigger a mousemove when clicked under any conditions (within iosSlider or otherwise). This would not be considered expected behavior so it must be a bug. But lets not worry about the classification of this issue, I am more concerned about finding an acceptable workaround that has a minimal/no impact on the end user's code.

> Isn't it easier to use my workaround, till the chrome bug is fixed? Or has it any side effects, i do not see? 

I will take another look at your solution and see if it works across all browsers (Android/iOS/IE7+/FF/Safari/Chrome). Thanks!

**Comment by iosscripts** [comment]
Just updated to v1.1.35 on master with your fix included @PPP01.

**Comment by iosscripts** [comment]
Also, if you need to buy an iosSlider commercial license, I would be happy to offer you one free of charge for helping with that fix. :) Just send an email to contact@iosscripts.com with your username PPP01 and I will send over a license key.

**Comment by berndslinger** [comment]
for the sake of completeness: it also works for me in chrome now; thank you very much.
I'll let the customer check, whether it's ok for him and then buy a licence.
