### ISSUE TITLE
Image to the left of activeslide doesn't appear until scroll

### ISSUE THREAD

**Issue by KingScooty** [iosscripts/iosslider#152]
I'm using the markup from the centre image example. The image to the left of the centre (active) image doesn't appear until the slider is dragged.

Is there a way to force this image to show before the slider is interacted with?

**Comment by KingScooty** [comment]
Looking further into this. It appears that the `transform` property doesn't update properly on the last child. Resulting in the last slide only moving to the left of the initial active slide once the user interacts with the slider, and not before hand.

`-webkit-transform: matrix(1, 0, 0, 1, 6764);`

becomes...

`-webkit-transform: matrix(1, 0, 0, 1, 3004);`

...on the last slide as soon as i interact with the slider. If you want a slide either side of the active slide visible as soon as the page loads, this issue is immediately apparent as the slide to the left doesn't appear until there is some sort of interaction.

Not sure if this is a bug. I am using jQuery 1.8.3.

**Comment by iosscripts** [comment]
Definitely a bug. I was able to reproduce it. I will try and get a fix out ASAP.

**Comment by iosscripts** [comment]
Ok. I have applied a fix to v1.1.34. You can download it from the master branch (https://github.com/iosscripts/iosSlider/archive/master.zip). Let me know if it solves your issue.

**Comment by KingScooty** [comment]
Yep, at first glance, it appears to solve the issue :)
