### ISSUE TITLE
Stuck when slides using arrows

### ISSUE THREAD

**Issue by Morkesjelen** [iosscripts/iosslider#153]
Hi. This is my slider.
http://svartedauden.byethost14.com/SLIDER/

I have updated to the last version of the plugin a few days ago and I'm experiencing issues.
The weird thing is that even if I implement the previous code that doesn't work

As you can see I duplicated the slides, then setted the number of the first duplicated slide in startAtSlide.
When the slide reaches a certain point it stuck, the movement is no longer fluid, and sometime I have blank spaces at the end of the slide.

I opened an issue for the "blank" problem a month ago and I solved it. But now the problem is appeared again.

**Comment by iosscripts** [comment]
Your demo has a javascript error in it (firebug).

Anyway, can you try v1.1.34? I solved this issue https://github.com/iosscripts/iosSlider/issues/152. Seems similar to the issue you are describing.
