### ISSUE TITLE
Responsive slider backgrounds does not scale (background-size)

### ISSUE THREAD

**Issue by alan-thunderapps** [iosscripts/iosslider#155]
Nice solution and the script is crisp!
It would be perfect if the slider images would auto-contain the available area when scaling down ie. true responsive images.

Appreciate any feedback.

**Comment by alan-thunderapps** [comment]
i resolved it by placing / hard-embedding "background-size: contain" in the item class div. Hope this helps someone.

**Comment by iosscripts** [comment]
Yep. The script is primarily meant to provide the ability to slide, add physics, etc. The HTML/CSS side is up to you. Background-size contain works perfectly. Also using an img with width: '100%' and height: 'auto' also does the trick.
