### ISSUE TITLE
Automatic container height

### ISSUE THREAD

**Issue by nicooprat** [iosscripts/iosslider#156]
In a previous version of iosSlider (few months ago), the container height was automatically calculated by the plugin. Now I have to manually set (and update on window resize) all slider heights. It results in a heavy code and poor performances : looks like the plugin was doing it better that me :)

Was there a feature that has been removed, or am I missing something ?

What's more, I'm not sure to understand what "responsiveSlideContainer" and "responsiveSlides" are really doing, because I thought it'll be the solution to my problem, but there're both true by default.

**Comment by iosscripts** [comment]
There was a bug in a previous version which caused me to remove the variable height option. I could not get around this due to too many variable implementation/browser combinations. Basically on some browsers in some instances the height would be calculated to be 0 initially if not set. So I had to add that restriction.

**Comment by iosscripts** [comment]
Which old version was working for you again? I can take another look at it.

**Comment by nicooprat** [comment]
I'm not sure I'll be able to remember what version it was... I might be thinking about this "height" option.

But by looking at the demos you provide with your code, I saw that you use "responsive" height by setting a padding-bottom in percentage. So I used this for now.

I thought there was the possibility for the slider to calculate its height itself. I also took a look at iScroll, 'cause I was sure it can do something like this. But I saw that actually iScroll doesn't set children elements absolute positioned... which has advantages and disadvantages.

So it looks like there's no perfect solution. Would you advice a solution when the "padding trick" won't work ? A bit of code ? It could help someone else too (I won't write mine because it caused performances issues on mobiles).

Thanks !

**Comment by iosscripts** [comment]
> Would you advice a solution when the "padding trick" won't work ?

Sure. Can you elaborate on this a bit? What would be a situation when the "padding trick" will not work? Have you found one? I think it works IE7+.

**Comment by nicooprat** [comment]
For example, I'm curious about how you would make this really responsive :
http://jsfiddle.net/nicooprat/NS7SJ/1/

Here are some part of the slide that are "fluid" (images will keep proportional) and some are static (the strong Lorem Ipsum will stay at height: 50px), that's why a percentage padding-bottom won't be enough I guess.

**Comment by iosscripts** [comment]
Yeah I suppose your right. You are going to need css media queries to cap the min and max. If you need below IE9, you will have to use JS to swap out styles.

**Comment by nicooprat** [comment]
A side not about a way I finally found : simply set a px-based padding-top and a percent-based padding-bottom. It can do the trick sometimes.

**Comment by Pixelous** [comment]
Marc, I have the issue with the container height too. The container height is important and it shouldn't be hardcoded in px via css bacause in case of implementing iosSlider to CMS. Actually the main problem now is only that scrollbar isn't visible because the container height is 0px height. Please see the live example http://demo.themeuniverse.net/iosslidertest/ Any fast fix on this? Thanks.

**Comment by marcwhitbread** [comment]
> The container height is important and it shouldn't be hardcoded in px via css bacause in case of implementing iosSlider to CMS.

@Pixelous I agree with you completely. But as I said above. There are browser limitations which cause the height of the slider to be calculated to be 0px intermittently by different browsers and implementations when I make the height optional on any of the elements. Obviously for a decent programmer, there are workarounds in the end users implementation that can remedy these height 0px issues. 

Most users need this to work right out of the box, with as many code variations as possible. When they run into height 0px issues randomly, they are unable to fix them without experienced programming assistance, and that is a deal breaker for 99% of people.

So you see my dilema? I could make the script a tiny bit more flexible but adding this functionality back in, but in return I get a lot of random height 0px rendering issues. It's just not worth it to the end user in almost all cases.

> Any fast fix on this?

Hmmm. Fast fix. You could try to set the iosSlider element height manually following the initialization. Something like: 

``` js
var setHeight = $('.iosSlider .item:eq(0)').outerHeight(true);

$('.iosSlider').css({
    height: setHeight
});
```

The above code will need to be added to the onSliderUpdate() callback as well probably to apply following orientationchange/window resize.

I will reopen this issue again to confirm my findings again. This issue keeps coming back.

**Comment by Pixelous** [comment]
@marcwhitbread your code above doesn't work for me unfortunately. http://demo.themeuniverse.net/iosslidertest/ the container still have 0px height however you can see at the console log the value of the container's height.

So as I have understood you correctly in some browsers there was 0px? Could you say what browsers there were?

**Comment by iosscripts** [comment]
The above code must follow the initialization for it to work. Not before. Or maybe grab the height of the image within the slide in stead of the item element to see if that works in stead.

> So as I have understood you correctly in some browsers there was 0px? Could you say what browsers there were?

Yes, 0px height was calculated at initialization. It would depend on the implementation, but usually Safari and Chrome.

Based on the console.log() you added, the height calculated on the item is 0px. This is actually an example of what I said above about jQuery calculating the height of elements to be 0px on initialization in some situations. The item element is clearly not height: 0px. But here it is calculated as 0px incorrectly. There is no way to work around this.

Let me elaborate further on why this happens. When using $(document).ready() to fire a script, only the DOM is ready. All of the elements on the page may have not been loaded yet (usually images). In your case, that's probably what it is. You may be able to fix this by using $(window).load() in stead, but the consequence of using this is the delayed loading of the slider.

**Comment by iosscripts** [comment]
Did you just add the window.load()? I am seeing the console report a height of 404px now. 

Minor edit to your code:

``` js
$('.iosSlider').iosSlider({
    snapToChildren: false,
    desktopClickDrag: true,
    infiniteSlider: false,
    snapSlideCenter: false,
    stageCSS: {
        overflow: 'visible'
    },
    scrollbar: true,
    responsiveSlideContainer: true,
    responsiveSlides: true,
    scrollbarLocation: 'bottom',
    frictionCoefficient: 0.98,
    onSliderUpdate: updateHeight
}); 

updateHeight();

function updateHeight() {

    var setHeight = $('.iosSlider .item:eq(0)').outerHeight(true);

    $('.iosSlider').css({
        height: setHeight
    });

}
```

**Comment by Pixelous** [comment]
Marks, sorry for spamming but your code works partly unfortunately. On window load now the height of the container not 0px anymore but after window resize it becomes 0px again. Seems onSliderUpdate method doesn't work?

I know about this weird issue with 0px height on Chrome, Safari on $(document).ready(). You might be interesting how David Desandro an author of Isotope plugin solved this issue http://isotope.metafizzy.co/docs/help.html#imagesloaded_plugin It’s a small plugin that finds all the images in a context, and fires a callback function once all the images have loaded.

So maybe one of the variants would be return back a version where the height of the container was calculating and use iosSlider included with imagesLoaded plugin?

**Comment by iosscripts** [comment]
Apparently I'm an idiot and forgot the onSliderUpdate function usage. It is not supposed to fire on window resize so that's why this doesn't work. But on a positive note, I added a new callback called onSliderResize in v1.1.45. It seems to be working now: 

``` js
$(window).load(function() {

    $('.iosSlider').iosSlider({
        scrollbar: true,
        snapToChildren: true,
        desktopClickDrag: true,
        scrollbarHeight: '2px',
        stageCSS: {
            overflow: 'visible'
        },
        onSliderResize: sliderResize
    });

    sliderResize();

});

function sliderResize(args) {

    var setHeight = $('.iosSlider .item:eq(0)').outerHeight(true);

    $('.iosSlider').css({
        height: setHeight
    });

}
```

Let me know if that works with v1.1.45.

**Comment by Pixelous** [comment]
@iosscripts thanks for the fix, appreciate it! However now after window resize I have gaps between images. Please note: there were no gaps before that. Seems it was v1.1.36 version of iosSlider. You can still see the live example here http://demo.themeuniverse.net/iosslidertest/

**Comment by marcwhitbread** [comment]
I see it. 

Line 1195: 

``` js
sliderMax[sliderNumber] = sliderMax[sliderNumber] + slideNodeOuterWidths[j];
```

Change to: 

``` js
sliderMax[sliderNumber] = sliderMax[sliderNumber] + newWidth;
```

I also updated the master branch with the fix.

**Comment by Pixelous** [comment]
@marcwhitbread thanks for such great support! Really appreciate it! Now everything works like clockwork! :+1:

**Comment by nicooprat** [comment]
Thank you guys for your investigations ! Really good work here.

**Comment by marcwhitbread** [comment]
Yeah! Teamwork :)

**Comment by nicmare** [comment]
are there any convenient fixes for automatic height?? i use iosslider for text items. and every items contains different text with different heights.

**Comment by marcwhitbread** [comment]
@nicmare unfortunately, at the moment a % or px height is still required for the slider. All slides must be the same height.

**Comment by nicmare** [comment]
then it would be probably a smart fix if the script checks the item with the tallest height and assign it to all items automatically.

**Comment by marcwhitbread** [comment]
@nicmare Not as easy as it sounds. Calculating auto element heights while the page is loading causes not only different results in different browsers, but inconsistent results based on page load time. You could write your own function that checks for the tallest slide and applies the height to all slides before initializing. I recommend checking after $(window).load() in stead of $(document).ready().

**Comment by nicooprat** [comment]
Side note for future readers : beware with calculating image heights, that are sometimes not loaded yet when `$(window).load()` is fired. You should check plugins like this one : https://github.com/desandro/imagesloaded to prevent this issue.

**Comment by AndyYoobee** [comment]
Hi guys!!

Im having an issue with this slider...

I get blocks of ul (they slide with their content) containing li img from the server, in a div container.
Le problem is that these blocks dont show until the browser window gets resized...
It works absolutely find on locaserver but once online..nope

Anyone else got this issue?
Is this what you guys where talking about few months ago?
Any efficient trick??

Cheers,

Andy

**Comment by marcwhitbread** [comment]
@AndyYoobee in this situation, any time you make manual modifications to the slider after the initial page load you should call `$(element).iosSlider('update');` to recalibrate based on new content.

This could all be caused by lax CSS of course. But if the issue is being caused by images that aren't ready yet, you should make sure you are initializing the slider within a `$(window).load();`

**Comment by locto03** [comment]
@AndyYoobee I have the same situation like you. After few tries i see that i have not insert the css `height: 100%` for the img which result in img have 0 height at `onsliderloader`. After i did it and initializing the silider within a `$(window).load();` Everything work great again. I think you can try this way also
