### ISSUE TITLE
addSlide issue

### ISSUE THREAD

**Issue by nothingam** [iosscripts/iosslider#159]
Helo,

I have started to use the slider in my web page, but when I try to insert a slide or use the update command I get this error: ReferenceError: stageNode is not defined. In case of 'update', it's from line 2242.

The slider DOM structure is the same as the provided example.
The update command is called from a different javascript file via a button click handling function.

Thanks for you help in advance,
nothingam

**Comment by iosscripts** [comment]
@nothingam Sorry about that. I have applied a fix to v1.1.37 that should resolve your issue. You can grab it off the master branch. Let me know if that resolves your issue.

**Comment by nothingam** [comment]
Thank you, it is perfect now! Appreciate the fast issue solving :)
