### ISSUE TITLE
addSlide using Ajax cause slide to move to first rather than forward

### ISSUE THREAD

**Issue by MaheshVN** [iosscripts/iosslider#161]
Hi,

By default we have two slides on page load and in the onSlideComplete method we are using Ajax to get the HTML and then using 'addSlide' to add the slide to args.data.numberOfSlides + 1 . This causes the slide to go back to the first rather than the 3 slide that is added via Ajax. 

On page load if we have 3 slides and add the 4th one via Ajax then the slide moves forward and everything works fine.

Is this a bug or is there a work workaround for the same?

code snippet:

``` js
onSlideComplete:function (args) {
    var currentSlideNumber = args.currentSlideNumber + 1;
    $.ajax({
            url: "mediatopics_content.html",
            dataType: "html",
            success: function(html){
                    element.iosSlider('addSlide',html,args.data.numberOfSlides + 1);
            }
    });
    element.iosSlider('update');
}
```

I have the infiniteSlider set to false.

Please help!

Thanks
Mahesh

**Comment by marcwhitbread** [comment]
It's a bug. I was able to reproduce it and will try and get a fix out shortly.

As a side note, the `element.iosSlider('update');` isn't doing anything in this case, you can remove that line.

**Comment by marcwhitbread** [comment]
I have updated to version v1.1.43 with a fix for this issue. Please let me know if it works.
