### ISSUE TITLE
Hidden $(parent).hide() sliders do not work properly after being show()

### ISSUE THREAD

**Issue by alpha1125** [iosscripts/iosslider#162]
Using version iosSlider 1.1.40...  and jQuery 1.8.3

Here's the use case that I experience this issue.

I had multiple sliders going on.
Using multiple sliders that are based off of example 7 -> 3.

The sliders are in a parent div, that is "display: none"...
The sliders are initiated with $("<selectors>").iosSlider({
            snapToChildren:true,
            desktopClickDrag:true,
            infiniteSlider:true,
            snapSlideCenter:false,
            //                onSlideChange:slideChange,
            stageCSS:{
                overflow:'visible'
            }
        });

When I do $(parent div).show(), the sliders display normally (initially)...
Problem #1: attribute infiniteSlider:true is not honoured.
Problem #2: After some usage of this newly displayed/shown slider, the class="item" width is reset/set to 100px, instead of what my css file set.

Not sure what the issue could be...

Any work arounds possible?

**Comment by marcwhitbread** [comment]
Redering the sliders while hidden within display: none; elements cause issues. After showing them, call `.iosSlider('update');` to recalibrate based on the actual height.

Let me know if that fixes your issue.

**Comment by alpha1125** [comment]
Worked.  Thanks!

**Comment by marcwhitbread** [comment]
Awesome! :+1:
