### ISSUE TITLE
Preloading images?

### ISSUE THREAD

**Issue by KingScooty** [iosscripts/iosslider#163]
Working locally, the plugin behaves fine as the images load instantly.

However, when plugged into Wordpress and setup on a remote test server - where there are loading times for images etc - the plugin/DOM seems to time out sometimes. I have to resize the browser window in order to have the images show up in the slider.

I'm wondering whether preloading the images, and _then_ initialising the plugin would sort this?

I can try and pass a link to the problematic page to you later if you need to see it.

**Comment by marcwhitbread** [comment]
Hi @KingScooty, you should delay the initialization until after the images have loaded then. Put the initialization in a $(window).load() in stead of a $(document).ready();. Alternatively, just call .iosSlider('update'); in $(window).load() and it will reinitialize. 

Let me know if that works.

**Comment by KingScooty** [comment]
I've added the following to my script:

```
    $(window).load(function() {
        $('.iosSlider').iosSlider('update');
    });
```

But i seem to get the following console log error now once the page is fully loaded:

`Uncaught ReferenceError: stageNode is not defined`

Interestingly, though, the plugin does seem to be triggering the DOM regularly now instead of timing out.

**Comment by marcwhitbread** [comment]
Please make sure you are on the latest version, that bug was sorted out in either 1.1.37/38.

Or on the line with the error, change stageNode to data.stageNode.

**Comment by KingScooty** [comment]
A-ha! I'm rocking the fairly new, but obviously not new enough, 1.1.34. Will report back in a few mins :)

**Comment by KingScooty** [comment]
Fixed it right up! 
Nice one, dude!
