### ISSUE TITLE
Click link Problem in IE8

### ISSUE THREAD

**Issue by berndslinger** [iosscripts/iosslider#164]
All images on the following page are linked: http://alexa-dahmen.de/sport.html
The links work in FF, Safari, IE9, meanwhile also in Chrome, but not in IE8

Thanks in advance!

**Comment by marcwhitbread** [comment]
A bug. I see it. Let me get back to you with a fix.

**Comment by iosscripts** [comment]
I was able to fix it for inline onclicks but actual anchor links appear to not work well in IE8 on drag for some reason. Are you able to bind your events using jQuery click() or bind() or inline onclick events? Those methods both work.

**Comment by berndslinger** [comment]
Thank you very much; it worked using bind; I've bought a licence for this project
