### ISSUE TITLE
Latest plugin version breaks centred example

### ISSUE THREAD

**Issue by KingScooty** [iosscripts/iosslider#165]
Ha, sorry to file another issue - the latest version of the plugin seems to affect one of the centred examples when resizing the browser (for responsive web design).

`7-Centered-Slides/2-Background-Images/index.html`

I've been using this example as the basis for a responsive web implementation, but the slides seem to move a percentage to the left and off the screen as the browser is made smaller in width - so the slides are half on the screen on the iphone.

**Comment by iosscripts** [comment]
Fix in version 1.1.42. Please confirm if possible.

**Comment by KingScooty** [comment]
Fixed! Amazing work! Cheers buddy!
