### ISSUE TITLE
Issue in iosSlider when slided backwards

### ISSUE THREAD

**Issue by senthil4axim** [iosscripts/iosslider#167]
I’m seeing an issue with swipe on iPhone during the swipe backwards(right to left) in dynamic multiple slider page.
## Background:

We have a main slider in form of index1Slider.
Based on args.currentSlideNumber(slider1SlideNumber) on index1Slider, on click of a button on the index1slider, I’m showing(initializing it the first time) dynamic slider ”index2”+slider1SlideNumber+”slider”.
For example:
If index1Slider has 2 slides, it dynamically creates index21Slider (for first slide) and index22Slider (for second slide). And the number of slides in these dynamic sliders are also dynamic, say for ex., index21Slider has 2 slides and index22Slider has 3 slides.
All these dynamic elements are constructed using Javascript/JQuery.
Assume the following: [The index inside the ‘(..)’ indicate the slide number]
                TABLE-1
index1Slider (1)     –    index21Slider (1)
index21Slider (2)

index1Slider (2)     –    index22Slider (1)
                index22Slider (2)
                index2 2Slider (3)
## slider1 : 

``` js
$('#locationSlider').iosSlider(
{
    desktopClickDrag : false,
    unselectableSelector : '.unselectable',
    snapToChildren : true,
    navSlideSelector : '#index1Content .slideSelectors .item',
    onSlideComplete:slideCompleteIndex1,
    onSliderLoaded : sliderLoadedIndex1,
    onSlideChange :slideChangeIndex1,
    autoSlide : false,
    scrollbar : true,
    scrollbarContainer : '#Index1Content .scrollbarContainer',
    scrollbarMargin : '0',
    scrollbarBorderRadius : '0',
    startAtSlide : slide_no,
    navPrevSelector: $('.prevButton'),
    navNextSelector: $('.nextButton')
});
slideCompleteIndex1 = function (args) {}            
sliderLoadedIndex1= function (args) {
    slideCompleteIndex1 (args);
    slideChangeIndex1 (args);
}
slideChangeIndex1= function (args) {
    currentIndex1 = args.currentSlideNumber - 1;
    $('#index1Slider .slideSelectors .item').removeClass('selected');
    $('#index1Slider .slideSelectors .item:eq(' + currentIndex1 + ')').addClass('selected');                
}
```
## Slider2 :

``` js
$('#index2’+ currentIndex1 +’Slider2'+ currentIndex1 ).iosSlider({
    desktopClickDrag : true,
    snapToChildren : true,
    navSlideSelector : '#index2Slider'+ i +' .slideSelectors .item',
    onSlideComplete :slideCompleteIndex2,
    onSliderLoaded :sliderLoadedIndex2,
    onSlideChange :slideChangeIndex2,
    autoSlide : false,
    scrollbar : true,
    scrollbarContainer : '#index2Content'+ currentIndex1 +' .scrollbarContainer',
    scrollbarMargin : '0',
    scrollbarBorderRadius : '0',
    startAtSlide : 1
});
slideCompleteIndex2 = function (args) {}            
sliderLoadedIndex2= function (args) {
    slideCompleteIndex2 (args);
    slideChangeIndex2(args);
}
slideChangeIndex2= function (args) {
    currentIndex2 = args.currentSlideNumber - 1;
    $('#index1Slider .slideSelectors .item').removeClass('selected');
    $('#index1Slider .slideSelectors .item:eq(' + currentIndex2 + ')').addClass('selected');                
}
```
## Actual Issue:

On sliding forwards (swiping leftright), everything works fine.
But once we slide backwards (swiping right left) on one of the dynamic sliders(index2’x’Slider), there seems to be a problem with the main slider(index1Slider). The main slider seems to invoke an extra ‘slideChange’ event if we try to get to the dynamic slider afterwards. 
1.  For ex, in index1Slider go to the second slide i.e, index1Slider (1) to index1Slider (2) as per TABLE-1.
2.  Click on the ‘link’ that shows the corresponding dynamic slider i.e, index22Slider. 
3.  Now go to the second slide index22Slider (1) to index22Slider (2). 
4.  If I click on the ‘back’ button to show the main slider, it works fine. 
5.  I could again click on the ‘link’ to show the dynamic slider (and back & forth works perfectly). 
6.  Now if in the dynamic slider index22Slider when I swipe backwards [swiping from index22Slider (2) to index22Slider (1)], go back to main slider (index1Slider) and again click on the link [to display index22Slider], the main slider does an automatic slideChange [i.e, index1Slider (2) to index1Slider (1)] messing up with the indexes. i.e, I land on index22Slider but when click ‘back’, I don’t end up back on index1Slider (2) but instead end up on the index1Slider (1), since the index1Slider args.currentSlideNumber had changed.
## HINT:

I don’t see this behavior in the browser.
This happens in version 1.1.32, 1.1.36, and 1.1.40. However, the version 1.0.35 seem to work fine.

**Comment by senthil4axim** [comment]
We have purchased the license of "iosSlider - iOS/Android Application". Having this issue in latest version is disappointing. 

Please address this and provide us the solution ASAP. Thanks in advance.

**Comment by iosscripts** [comment]
If you have a working demo, zip it and send it over to contact@iosscripts.com. That would speed things up if timing is an issue.

**Comment by iosscripts** [comment]
pre v1.1 wont be much help unfortunately. The script was completely overhauled in v1.1. I will keep working on a fix.

**Comment by iosscripts** [comment]
I'm still having problems reproducing this issue. Can you provide your HTML/CSS as well? 

As I said above, zipping a demo of the bug and sending it to contact@iosscripts.com would speed this up by about 1000%.

**Comment by marcwhitbread** [comment]
Not enough info from submitter. Closing.
