### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by Pixelous** [iosscripts/iosslider#168]
Hi, Marc! First much thanks for such a great plugin! I wish to know for sale a WordPress theme should I buy  Extended License once or buy it for every single theme?

**Comment by marcwhitbread** [comment]
Hi, thanks for using iosSlider :). You would need to purchase an "iosSlider - Website Template License" for each theme you create for sale. If you feel like you are going to make a lot of themes with this script, you may want to consider volume/bulk licensing.

If you are interested in receiving more information about volume licensing. Send an email to contact@iosscripts.com and we can get a discussion started.

Let me know if you have any questions
