### ISSUE TITLE
Responsive Mode Issue

### ISSUE THREAD

**Issue by Pixelous** [iosscripts/iosslider#169]
Hi! On responsiveSlideContainer: true and responsiveSlides: true we have gaps between images. Than smaller the window screen then bigger the gaps between images. Please see the screenshot. http://snag.gy/FhBe0.jpg

**Comment by marcwhitbread** [comment]
Odd. Can I see some HTML/CSS for the slider and the JS initialization parameters?

**Comment by Pixelous** [comment]
Marc, we have been testing it on our local storage. Now you can see it live here http://demo.themeuniverse.net/iosslidertest/ We were pretty surprised that everything works like a charm now!!! :+1: 

Much thanks for such a great plugin! This is the best we've seen lately! Really appreciate it! We are going to buy iosSlider - Website Template License USD 100.00 tomorrow.

**Comment by marcwhitbread** [comment]
Glad to hear you got everything working :). Let me know if you run into any issues down the road and I would be happy to assist.
