### ISSUE TITLE
Stuck between slides

### ISSUE THREAD

**Issue by shaicoleman** [iosscripts/iosslider#17]
On Firefox 12.0 under Windows XP, every 10th slide or so gets stuck half way when dragging with a mouse. Doesn't seem to happen with other browsers. This is with snapToChildren enabled.

**Comment by iosscripts** [comment]
Tested iosSlider v0.9.4.1 in FF 12.0 and unable to reproduce. Waiting for more info from jj05 regarding more specific test case for reproduction.

**Comment by shaicoleman** [comment]
It happens on _demos/_examples/2-Rotating-Banner/index.html , perhaps because of the infiniteSlider setting.

**Comment by shaicoleman** [comment]
Works for me with 0.9.4.5 (beta)   06/12/12 on Firefox 13

**Comment by iosscripts** [comment]
Fantastic :)
