### ISSUE TITLE
onSlideChange returns args.currentSlideNumber == args.targetSlideNumber

### ISSUE THREAD

**Issue by zigotica** [iosscripts/iosslider#172]
Either this is a bug or it's like that on purpose, dont know. Anyway, we should either have another internal variable for currentSlideBeforeChange or we have another method onBeforeSlideChange

Am i missing something?
Thanx for the great script

**Comment by iosscripts** [comment]
Your right. That is a bug. I will update currentSlideNumber with the value of the slide you are sliding from.

**Comment by marcwhitbread** [comment]
Fixed in v1.1.47. currentSlideNumber now reflects the number of the slide you are moving "from". targetSlideNumber will stay as the number you are sliding "to". You can grab it off the master branch.

**Comment by zigotica** [comment]
THANX!
