### ISSUE TITLE
args.targetSlideNumber gets crazy when reaching end sides

### ISSUE THREAD

**Issue by zigotica** [iosscripts/iosslider#173]
hi

args.targetSlideNumber has a bug when reaching either side, it does not update value and stays constant even if coming back/forth. i think it was like that as well before #172 change was made.

**Comment by iosscripts** [comment]
I'll take a look. Is this while infiniteSlider: true?

**Comment by zigotica** [comment]
yes!

**Comment by iosscripts** [comment]
Hmmm sorry I am not seeing anything. Can you answer a few questions to help me reproduce it?

Can you give me your iosSlider() initialization code?
Can you tell me when you are seeing the error (onSlideChange, onSlideComplete, or another time)?
What is the error value, and what do you expect that value to be?
How many slides do you have?

**Comment by iosscripts** [comment]
Hey, I had to roll back to the previous version before the data('args') currentSlideNumber change. In stead, I added a variable called args.prevSlideNumber and args.prevSlideObject. They are accessed the same way as the others. Let me know if that works for you.

The targetSlideNumber variable being off is resolved as well.
