### ISSUE TITLE
Add and Remove Not working

### ISSUE THREAD

**Issue by ken12** [iosscripts/iosslider#174]
Hi, I am trying to add and remove from the slider but I keep getting this error:
Uncaught TypeError: Object [object Object] has no method 'iosSlider'.

This is the code I have:
                  jQuery(document).ready(function($) {
                $('.iosSlider').iosSlider({
                    snapToChildren: true,
                    desktopClickDrag: true,
                    keyboardControls: true,
                    navNextSelector: $('.next'),
                    navPrevSelector: $('.prev'),
                    navSlideSelector: $('.selectors .item'),
                    infiniteSlider: true,
                    onSlideChange: slideChange
                });

```
        });
        function slideChange(args) {

            console.log(args);
            $('.selectors .item').removeClass('selected');
            $('.selectors .item:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');

        }
        function AddSlide(){
            console.log("Adding Slide");
            var slidePosition = $(".slider")[0].childElementCount;
            var slideHTML = "<div class = 'item'>d5</div>";
            console.log($('.iosSlider'));
            $('.iosSlider').iosSlider('addSlide', slideHTML, slidePosition);
        }
```

I'm a not an experienced javascript program but I'm trying to learn. What could the issue be?

**Comment by marcwhitbread** [comment]
Hmmm, your code looks ok. When does your addSlide() function get called? Which version of iosSlider are you running?

If you could provide me with a link or a zip of a demo with the issue in question, I would be able to figure out the problem in no time (probably).

**Comment by ken12** [comment]
I am using the latest version from the website. My addslide function gets called when an addslide button has been called

**Comment by marcwhitbread** [comment]
> If you could provide me with a link or a zip of a demo with the issue in question, I would be able to figure out the problem in no time (probably).

**Comment by ken12** [comment]
I will in an hour. Not close to my computer

**Comment by ken12** [comment]
Could you include the issue? Didn't mean to do it

**Comment by marcwhitbread** [comment]
> I will in an hour. Not close to my computer

Thanks.

**Comment by ken12** [comment]
I meant unclose the issue which i just did. Gotta turn off the autocorrect.

**Comment by marcwhitbread** [comment]
Ah ok.

**Comment by ken12** [comment]
I figured out what the problem was. I forgot to remove an inclusion of another jQuery call. That fixed the error but doesn't add at all. Could this caused by the way I defined slideHTML up above? I noticed that in the benchmark, the add slideHTML was created like this: 

```
          var slide = $("<div/>", {
        'class': 'item item6'
    }).append($('<img />', {
        'src': '../../_site-demo/_img/h-slider-1.jpg'
    }));
```

The code I'm using is the 9-Full-Width-Responsive-Height in the examples folder.

**Comment by marcwhitbread** [comment]
Both ways should work.

**Comment by ken12** [comment]
I want to send a a zipped folder of what I've been working on. Any email?

**Comment by iosscripts** [comment]
Ah sorry about that. Send it over to contact@iosscripts.com. Hopefully soon GitHub will allow users to drag and drop zip files into these text boxes (right now only images are allowed to be attached I guess :S).

**Comment by ken12** [comment]
Just sent it, thanks again

**Comment by iosscripts** [comment]
I emailed you a fix. You had a minor bug in your code and I fixed it. Also, I found a related bug in the iosSlider.js, which I also fixed. Make sure you download v1.1.48 before using.

Let me know if its working on your end.

**Comment by ken12** [comment]
The min/js you updated is it the javascript itself or the iosSlider.min?  What bug was it? I'm asking just for educational purposes only.

**Comment by marcwhitbread** [comment]
Both files were updated. iosSlider.js and iosSlider.min.js do the same thing, one is just compressed. Include either of them, but not both.

The bug in your code was the $('div').iosSlider({ .. }); code. It needed to be changed to $('.iosSlider').iosSlider({ .. });. If you need more info about why, read up on jQuery selectors and how they work.

The bug in my code was preventing a slide to be added to the first slide position while infiniteSlider: true. Something I should have caught a while ago.

I will close the issue for now. If you still run into issues, email contact@iosscripts.com
