### ISSUE TITLE
Slider reinitialises after destroy

### ISSUE THREAD

**Issue by seb3point0** [iosscripts/iosslider#178]
I am experiencing an issue where I destroy the slider and remove all data associated with the slider element. However, when I resize the window, the slider reinitialises by itself. have you seen this before. I can provide an example.

**Comment by iosscripts** [comment]
Probably a bug. Let me see if I can reproduce it. If you have a demo already that would be great.

**Comment by seb3point0** [comment]
Hi, we spoke and Twitter and StackOverflow. 

Here is the demo : http://artiris.clients.twi.tl/galeries/galerie-bleue

You'll see in the log the init and destroy calls. Specifically the slider gets destroyed when min-width:768px unmatches. The destroy function gets called and everything seems to be working fine. But if you fiddle with the screen size under 786 after destroy is called, the slider gets activated again but the init function is never called.

I was also able to reproduce the bug in an other scenario.

Thanks

**Comment by iosscripts** [comment]
You beat me to it! I was going to look into this tonight after wrapping up some other issues. I will take a look at your change in issue #179 and then if it's all good, I will pull it into the master branch.

**Comment by seb3point0** [comment]
Cool my first pull request :) It was a simple fix though. 

You can discard issue #179, the correct fix is #180 which also cleans up the args data which was left over

**Comment by iosscripts** [comment]
Awesome. I will take a look :).

**Comment by iosscripts** [comment]
Your changes were good. Thanks :)
