### ISSUE TITLE
Margin-left seems to break

### ISSUE THREAD

**Issue by KingScooty** [iosscripts/iosslider#181]
I've just updated to the latest version of the plugin and i've noticed that a `margin-left` i had applied to every slide (excluding `first-child`) to produce a nice little gap between each slide appears to break after the first margin is applied to the second child. The inspector recognises a margin is applied on all slides, but the slides are bunched next to each other after the second child.

**Comment by marcwhitbread** [comment]
I see it. The calculation is being thrown off in initialization and not including the margin. I'll try and patch it today.

**Comment by marcwhitbread** [comment]
Take a look at v1.1.53 and let me know if that sorts it out.

**Comment by Batmensch** [comment]
1.53 seems to fix the issue for me.
