### ISSUE TITLE
 Conflict with 'sharethis' social share code in ie8/ie9

### ISSUE THREAD

**Issue by dv247** [iosscripts/iosslider#185]
We're using the latest code however the iosslider carousel breaks in ie8/ie9 when the 'sharethis' social share script is added to the page. Any ideas?

**Comment by Pixelous** [comment]
Any links?

**Comment by iosscripts** [comment]
@Pixelous links for what? I'm confused.

**Comment by Pixelous** [comment]
Links where they are using the iosSlider. :)

**Comment by iosscripts** [comment]
Ah. @dv247 hasn't provided me with anything to troubleshoot this :S. I will try to reproduce it.

**Comment by iosscripts** [comment]
Can you answer a few questions for me:
- Do you have a demo of the issue I can see?
- Can you provide your sharethis code that produces the issue?
- Where in the code is the sharethis located?

A link to a demo of the issue in question would be ideal.

**Comment by dv247** [comment]
Here's a html demo link of the issue:
http://www.dv247.com/0Oo-_QAvaXJnVz5_unDRLUDSBj1.htm
You may need to do a refresh to re-produce in ie9.

**Comment by marcwhitbread** [comment]
This big, unstyled HTML file wont be very useful. iosSlider is not working in this demo due to the lack of the script being present. Is this intentional? Where in the code is the sharethis in question?

**Comment by dv247** [comment]
iosSlider code starts from line 86. Sharethis code starts from line 978. Best to work off the demo link.

**Comment by dv247** [comment]
Lack of the script is not intentional. What's missing?

**Comment by marcwhitbread** [comment]
I'm not seeing the iosSlider.js being included in the page you linked. Also, the page has no CSS, images, etc. It's just unformatted HTML.

**Comment by marcwhitbread** [comment]
My page looks like this: 
![Screen shot 2013-01-14 at 10 20 00 AM](https://f.cloud.github.com/assets/1944274/64837/1e8770c6-5e5e-11e2-884d-e1718b3c315b.png)

**Comment by dv247** [comment]
Sorry, forgot about the include files, please try:
http://www.dv247.com/0Oo-_QAvaXJnVz5_unDRLUDSBj1.aspx.

**Comment by iosscripts** [comment]
I rebuilt a demo and haven't been able to reproduce the issue. I used demo 2-Rotating-Banner with the following share this code: 

In the head:

``` html
<script type="text/javascript">var switchTo5x=false;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "ur-773a1fb-1df5-b15-5c85-d67513493db8"});</script>
```

in the body:

``` html
<span class='st_sharethis_large' displayText='ShareThis'></span>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_linkedin_large' displayText='LinkedIn'></span>
<span class='st_pinterest_large' displayText='Pinterest'></span>
<span class='st_email_large' displayText='Email'></span>
```

What does your share code look like?

**Comment by dv247** [comment]
Header

```
/* sharethis css */
.shareThisSmallVersion      {display:inline !important; float:right; height:26px;  z-index:99; }
.shareThisSmallVersion span {height:26px; cursor:pointer;  z-index:100; display:inline-block; }
.st_googleplus_custom       {background: url("/images/buttons/google+.png") no-repeat scroll left top transparent; padding:0 28px 0 0; }
.st_twitter_custom          {background: url("/images/buttons/twitter.png") no-repeat scroll left top transparent; padding:0 28px 0 0; }
.st_facebook_custom         {background: url("/images/buttons/facebook.png") no-repeat scroll left top transparent; padding:0 28px 0 0; }
.st_email_custom            {background: url("/images/buttons/email.png") no-repeat scroll left top transparent; padding:0 28px 0 0; } 
.dv_print_custom            {background: url("/images/buttons/print.png") no-repeat scroll left top transparent; padding:0 20px 0 0; } 
```

Body

```
<h1>
<span class="shareThisSmallVersion"><span class="st_googleplus_custom" displayText="Google +" title="Share on Google+">&nbsp;</span><span class="st_twitter_custom" displayText="Tweet" title="Share on Twitter">&nbsp;</span><span class="st_facebook_custom" displayText="Facebook" title="Share on Facebook">&nbsp;</span><span class="st_email_custom" displayText="Email" title="Share via email">&nbsp;</span><span title="Print this page" class="dv_print_custom" onclick="window.print();">&nbsp;</span></span>
</h1>

<!-- Sharethis Javascript -->
<script type="text/javascript"> var switchTo5x = true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript"> stLight.options({
        publisher: '85d09957-7aa3-4a02-ab70-f11b7fd18417',
        headerTitle: '| dv247.com - Play Perform Record Music',
        tracking: 'google'
    });
</script>
<!-- End 'Sharethis' Javascript -->
```

**Comment by dv247** [comment]
Any news with this as we're hoping to go live with this page today?

**Comment by iosscripts** [comment]
I am still not able to reproduce the issue with your social code and iosSlider on the same page. How were you able to confirm that iosSlider and sharethis are conflicting and not something else?

**Comment by marcwhitbread** [comment]
All I have is the default slider with your exact code: http://marcwhitbread.com/m/iosSlider/_demos/_examples/2-Rotating-Banner/

Everything is working. Something else I should try? 

If not, I will need you to isolate a test case with just the sharethis and the iosSlider to confirm that iosSlider has an involvement in this issue. Duplicate the web page and start pulling things out until it starts working again, that will isolate the cause. Debugging 101.

**Comment by dv247** [comment]
We managed to get this working by upgrading to jquery 1.8.1 from 1.8. A bug in jquery which stops the page from firing on a button refresh. Thanks for your help.

**Comment by iosscripts** [comment]
Glad to hear you got it sorted out. I'll make a note of the jQuery 1.8 issue. Thanks.
