### ISSUE TITLE
Photo Gallery Thumbnails

### ISSUE THREAD

**Issue by Pixelous** [iosscripts/iosslider#186]
Hi!

I have noticed that at the demo 3-Photo-Gallery when clicking on a thumbnail first selected class receive thumbnail which is near for a split second.

Any help?

**Comment by iosscripts** [comment]
What specifically do you need help with?

**Comment by Pixelous** [comment]
Ideally would be great to fix that, it's a tiny bug, not critical however.

**Comment by iosscripts** [comment]
I don't understand the issue you are describing. Can you expand on your description?

**Comment by Pixelous** [comment]
Yeah. Take a look at the screenshot please. http://snag.gy/1xgdw.jpg

**Comment by iosscripts** [comment]
Hmmm. not seeing it. Which iosSlider version? 1.1.53?

**Comment by Pixelous** [comment]
v1.1.49

**Comment by iosscripts** [comment]
Which browser are you using? I see nothing still.

**Comment by Pixelous** [comment]
Have updated to the latest version but it's still there. Tested on Chrome and Firefox. Strange you don't see this behaviour. As I have said it's occurs for a split second and therefore is not immediately evident to the eye.

**Comment by iosscripts** [comment]
Very odd. Firebug isn't showing anything either. If any class is being added for even the shortest duration, firebug would show it.

**Comment by Pixelous** [comment]
Try Chrome “Inspect Element” tool instead http://snag.gy/yNPAm.jpg Chrome show it.

**Comment by iosscripts** [comment]
That looks different than my demo. You changed some things?

**Comment by iosscripts** [comment]
And the third item showing "selected" isn't the issue right? Isn't the issue that the 4th item is showing selected?

**Comment by iosscripts** [comment]
Maybe you are describing the way iosSlider passes though slides? If you had 10 slides, and were on slide 1, and clicked the 10th slide, you would see the selector pass through each item as it animates through. Is this what you are talking about?

**Comment by Pixelous** [comment]
Sorry, I have made screenshot from the theme I am working on. But the behaviour is the same.

**Comment by Pixelous** [comment]
Marc yes I see the selector pass through each item as it animates through. Is there a way to disable this animation?

**Comment by iosscripts** [comment]
Ah. That would be in the callback. Give me a moment to modify it.

**Comment by iosscripts** [comment]
This is proving difficult. What about using the onSlideComplete callback in stead of onSlideChange?

**Comment by Pixelous** [comment]
Then there is some delay for selected thumbnail. Is there an easy and quick way to give selected class to thumbnail immediately?

**Comment by iosscripts** [comment]
Yeah, just go around the script. 

Try this:

``` js
$('.iosSliderButtons .button').bind('click', function() {

    $('.iosSliderButtons .button').removeClass('selected');
    $(this).addClass('selected');

});
```

**Comment by Pixelous** [comment]
Perfect! Much thanks Marc!

One more. It's normal to use img tags for item's thumnails? I mean if item's thumnails are the same images as main slider's images so there are shouldn't be multiple server requests, right?

**Comment by iosscripts** [comment]
Yeah that's right. The browser will cache the images.

**Comment by Pixelous** [comment]
Ups, Marc but in case of click there will not be selected thumbnail in case of dragging but not clicking.

**Comment by Pixelous** [comment]
Marc one more I have noticed that infiniteSlider is not working anymore with thumbnails now after I have updated to v1.1.49. You may see that at your demo 3-Photo-Gallery.

**Comment by Pixelous** [comment]
Have downloaded v1.1.49 and infiniteSlider works fine with this version.

**Comment by iosscripts** [comment]
> Ups, Marc but in case of click there will not be selected thumbnail in case of dragging but not clicking.

Unfortunately, you can't have it both ways in this case. Either the slide indicators are manually updated, or automatically using the callbacks. You will have to make a compromise because there is no way to prevent the onSlideChange callback from firing in between.

I will look into the infinite slider issue. I've been able to reproduce it in v1.1.53.

**Comment by Pixelous** [comment]
Ok, thanks any way. Marc try 2-Rotating-Banner at your demo. Infinite slider is not working.
