### ISSUE TITLE
snapping breaks when touching diagonally in iOS

### ISSUE THREAD

**Issue by tankadesign** [iosscripts/iosslider#189]
If you have a slider with a fixed height set on a tall page, and you use your finger to scroll the page by touching the slider, you can get the iosSlider to slide left/right while the page scrolls up/down if you go in a diagonal motion. When you stop scrolling the slider can be stuck in between pages, which when snapToChildren is on shouldn't happen. Or you can also make it get stuck if you start scrolling the slider horizontally and then quickly release and tap and start scrolling up/down.

You can try it out on our website (in the Who We Are section): http://www.tankadesign.com

**Comment by marcwhitbread** [comment]
There is a difficult balance between touching the slider and scrolling vertically and preventing the horizontal action. The script does perform some checks to make sure that if adequate vertical velocity is achieved, the horizontal movement is blocked (or vica versa).

In short, there is no way of knowing what the user is trying to do in every case. Move vertically or horizontally? Every movement has as at least some vertical or horizontal component. The difficulty is deciphering which the user is trying to do, and preventing the opposite. One example of this breaking is a user moving their finger at or very close to a 45 degree slope. So which action is the user attempting to perform? It's impossible to force a UI reaction based on these conditions so the script lets both movements occur.

With respect to the snapping issue getting caught between slides. This is a browser limitation propagated by the browser movement (vertically) and the slider triggered (horizontally) being started. As soon as vertical scrolling begins, all scripts are stopped. Therefore, preventing iosSlider from snapping back to the slide edge.

Hopefully that explanation was sufficient. Let me know if you have any questions.

Also, I should mention that I am always open to suggestions if you have any.

**Comment by tankadesign** [comment]
Can't you make it respond to the touchend event, so that it runs through the code to see if it needs to snap to children then?

**Comment by marcwhitbread** [comment]
touchend is where the deceleration, snapping occurs currently. Calling $('.iosSlider').iosSlider('update'); would recalibrate the slides. Then it would be up to you to decide when the call is fired.

Make sure to download v1.1.55. There was a bug in the update function I resolved last night.

**Comment by tankadesign** [comment]
Awesome, that fix was a huge help. I was able to fix my issue using onscroll and setTimeout to run the update call every time someone finishes scrolling vertically. Thanks for being so on top of it!

**Comment by iosscripts** [comment]
Glad to hear it :). 

Don't forget to pick up a license for any commercial projects you might be working on.
