### ISSUE TITLE
iOSSlider Version: v1.1.40 (11/29/2012) inputs not working

### ISSUE THREAD

**Issue by kraberx** [iosscripts/iosslider#191]
iOSSlider Version: v1.1.40 (11/29/2012) inpunts is not working in chrome and safari with desctopClickDrag:true :(

**Comment by iosscripts** [comment]
v1.1.40 is old. It won't be fixed. Update to the latest version before submitting a bug. v1.1.56

**Comment by iosscripts** [comment]
Try this first. use the 'unselectableSelector' parameter and contain the inputs within that.

``` js
$('.iosSlider').iosSlider({
    unselectableSelector: '.unselectable'
});
```

``` html
<div class = 'slide'>
    <div class = 'unselectable'>
        <input />
    </div>
</div>
```

**Comment by kraberx** [comment]
understand. Thanks.
