### ISSUE TITLE
Problem using CSS percentage values (margin-right) on the slides for a responsive slider with infiniteSlider turned on

### ISSUE THREAD

**Issue by Quirksmode** [iosscripts/iosslider#192]
Hi,

when I use the following JS and CSS the slider and slides scale brilliantly when resizing the window, but when you click to see the next slides it seems to struggle to maintain an even margin between the last and first slides after looping (infiniteSlider) causing them to overlap or double with space. Resizing the window briefly corrects the issue, but then after clicking to see the next few slides the problem comes back when it reaches the last slide again. Using px fixes this, but then unfortunately does not resize nicely.

JS

$('.iosSlider').iosSlider({
        snapToChildren: true,
        desktopClickDrag: true,
        responsiveSlideContainer: true,
        responsiveSlides: true,
        infiniteSlider: true,
        navPrevSelector: $('.featured-work .flex-prev'),
        navNextSelector: $('.featured-work .flex-next')
    });

CSS

.iosSlider {
    position: relative;
    top: 0;
    left: 0;
    overflow: hidden;
    width: 100%;
    height: 334px;
}

.slider {
        width: 100%;
    height: 100%;
}

.slide {
         float:left;
         width: 29.6%;
         margin-right:5.6%;
}
![iosprob](https://f.cloud.github.com/assets/1786608/94984/ba8f08a2-665c-11e2-96ad-236be4af7a0b.jpg)

**Comment by marcwhitbread** [comment]
Are your slides images in this case?

Can you paste in your HTML for the slider structure also?

**Comment by Quirksmode** [comment]
Hi,

the slides contain HTML. There was quite a lot of code in each one so to keep things simple I have recreated the issue using very simple html along with a couple of extra styles so you can see the slide outlines. 

Full Code below:

JS

``` js
$('.iosSlider').iosSlider({
snapToChildren: true,
desktopClickDrag: true,
responsiveSlideContainer: true,
responsiveSlides: true,
infiniteSlider: true,
navPrevSelector: $('.featured-work .flex-prev'),
navNextSelector: $('.featured-work .flex-next')
});
```

CSS

``` css
.iosSlider {
position: relative;
top: 0;
left: 0;
overflow: hidden;
width: 100%;
height: 334px;
}

.slider {
width: 100%;
height: 100%;
}

.slide {
float:left;
width: 29.6%;
margin-right:5.6%;

background-color:blue;
border:1px solid red;
height:200px;
}
```

HTML

``` html
<div class="iosSlider">
    <div class="slider">
                <div class="slide"></div>
        <div class="slide"></div>
        <div class="slide"></div>
        <div class="slide"></div>
        <div class="slide"></div>
        <div class="slide"></div>
    </div>
</div>
```

**Comment by marcwhitbread** [comment]
Simplified demos are music to my ears. Let me take a look at it over the next few hours and see if I can sort it out.

**Comment by Quirksmode** [comment]
Thanks for the really quick response :-)

**Comment by marcwhitbread** [comment]
Updated to v1.1.58 with a fix. Let me know if that works for you.

**Comment by Quirksmode** [comment]
Works perfectly now, thanks so much for the incredibly quick turnaround time, I am blown away!!
