### ISSUE TITLE
Full Width

### ISSUE THREAD

**Issue by Pixelous** [iosscripts/iosslider#193]
Hi Marc!

Don't understand why full width slider doesn't work for me. Could you have a look please? bit.ly/WNnx46

**Comment by marcwhitbread** [comment]
You are using width auto on your slide elements. So it's collapsing to the width of the image. 

Follow the instructions on the website. You need a width and a height specified on your slide element CSS.

Setting the width of the slides to 100% will likely fix it.

**Comment by Pixelous** [comment]
Thanks Marc!
