### ISSUE TITLE
Broken on IE 8?

### ISSUE THREAD

**Issue by Batmensch** [iosscripts/iosslider#194]
Didn't iosslider work on IE 8 at one time?  I'm finding right now that it seems to be broken on IE 8 and earlier; even the front page

http://iosscripts.com/iosslider/

doesn't display properly on IE 8 and earlier.

**Comment by marcwhitbread** [comment]
The demo package works in IE8. The script supports back to IE7. Working and tested regularly. 

The website does not because I am lazy. I should probably take a look at updating it... but I'm currently rebuilding it to make way for some new plugins :).

**Comment by Batmensch** [comment]
OK, good, that's a relief.  Mine's broken because I broke it, then. ;)
