### ISSUE TITLE
Recommended way to paginate multiple items, via an offset?

### ISSUE THREAD

**Issue by alpha1125** [iosscripts/iosslider#195]
Say I have a slider that shows 5 items at a time, and there's 25 items in total.
I want the next/prev buttons to skip ahead 4 (or 5, depending if we want to see the last one).  While still allowing for a swipe to be one at a time (or more... maybe a flag for this behaviour)

Is this possible, to:
NEXT Btn onClick: $('#iosSlider').iosSlider('goToSlide', $currentSlideNumber + navBtnOffset) )
PREV Btn onClick: $('#iosSlider').iosSlider('goToSlide', $currentSlideNumber - navBtnOffset) )

My problem is, I can't seem to get the $currentSlideNumber value.  I've probably just overlooked/missed the value.  Should I be using $('#iosSlider').data('iosslider') to look for the $currentSlideNumber in there?

An alternative for me to do this, is that I just group the items in a DIV, 4 or 5 at a time, and pull the whole group... but was hoping that this could be done via iosSlider.

Thanks,

**Comment by marcwhitbread** [comment]
You should be able to access the current slide number like so: 

``` js
$('#iosSlider').data('iosslider').currentSlideNumber;
```

And then like so:

``` js
$('#iosSlider').iosSlider('goToSlide', $('#iosSlider').data('iosslider').currentSlideNumber + navBtnOffset);
```

Let me know if that works.

**Comment by alpha1125** [comment]
What was suggested didn't seem to work.

Inside the chrome (osx latest) javascript console:

iosSlider Version: v1.1.56 (01/20/2013)
jQuery 1.8.3

The iosSlider object itself exists...

``` javascript
$('#slide2').data('iosslider');
```

Object
centeredSlideOffset: 0
childrenOffsets: Array[4]
infiniteSliderOffset: 0
infiniteSliderWidth: undefined
numberOfSlides: 8
obj: v.fn.v.init[1]
originalOffsets: Array[4]
scrollBorder: undefined
scrollMargin: undefined
scrollbarClass: "scrollbar3"
scrollbarStageWidth: undefined
scrollbarWidth: undefined
scrollerNode: v.fn.v.init[1]
settings: Object
slideNodes: Array[8]
sliderMax: 1820
sliderNumber: 3
stageWidth: 860
**proto**: Object

Next command I send to the console:

``` javascript
$('#slide2').data('iosslider').currentSlideNumber;
```

undefined

There is no currentSlideNumber, there is a sliderNumber, but that is not what I am after, as that is the actual iosSlider counter...

The currentSliderCounter is not accessible, seems to be a private variable, not exposed by .data().

**Comment by marcwhitbread** [comment]
Oops I meant 'args' sorry.

``` js
$('#iosSlider').data('args');

$('#iosSlider').data('args').currentSlideNumber;
```

It's all in the documentation under **Settings and Options** > **jQuery .data() Object Details**.

**Comment by alpha1125** [comment]
Didn't think to look in data('args').  Thanks, got the data I need now.
