### ISSUE TITLE
Scroll doesn't work on Internet Explorer 8

### ISSUE THREAD

**Issue by Pixelous** [iosscripts/iosslider#197]
Hi!

Seems scroll doesn't work on Internet Explorer 8 with iosSlider. Any fix?

**Comment by marcwhitbread** [comment]
Do you mean the browser scroll? or the horizontal dragging?

Be as specific as possible. Assume I have no idea what you are talking about (trick question, I don't!)

**Comment by Pixelous** [comment]
I mean the browser scroll. Could you test it on you side please?

**Comment by marcwhitbread** [comment]
Sure I can. I will investigate. I just didn't know which scroll you were talking about...

**Comment by Pixelous** [comment]
Thanks. I am not crazy about IE8 compability actually but for the theme I sell people asking to make it compability with IE8. :)

P.S. Any plans for WordPress version? You can sell it here http://codecanyon.net/

**Comment by marcwhitbread** [comment]
Codecanyon is bullshit. They take an 80% cut... and they will set the prices. I would sell it through my store if anything. I have a wp version planned, but it's a low priority right now.

Tested the IE8 issue. Browser scrollbars are working. Please, please be as specific as possible. I cannot help you if I don't have all the information. 

Where is the scrollbar located that isn't working? in the slider?

**Comment by Pixelous** [comment]
Marc could I send a link to my page with your slider by email? Because if I'll post link here it will be a promotion then right?

P.S. Codecanyon take an 50% actually and when you will be an elite author (means you sell more then $75 000 as I remember) then they take 30% only.

**Comment by marcwhitbread** [comment]
Yes, you can always send your stuff to contact@iosscripts.com. Posting it here or there is up to you, I don't mind.

50% is for an exclusive partnership I thought. That means I can only sell it on codecanyon which is lame. Either way, it's not as good as the custom store I manage now with only 9% overhead ;)

**Comment by Pixelous** [comment]
Thanks, send a link by email.

**Comment by marcwhitbread** [comment]
> Could you tell me does the browser scroll works for you at Internet Explorer 8? I test my page at Internet Explorer 10 but with a help of document compatibility mode for IE 8.

It does work for me. I have an actual old XP vm that I use for testing IE8 and it's fine. I also checked my windows 7 IE9 in browser mode: IE8 and document mode: IE8 standards. 

It's important when testing in a different browser mode that you change the browser mode and the document mode… not sure if that is a setting in IE10.

I did notice another thing. Can you make sure you don't have any console.log() calls in your JavaScript? IE7/8 JS does not understand this command and can cause undesired effects. Make sure you remove console.log() call and try again.

**Comment by Pixelous** [comment]
Thanks Marc for the support! Glad it works for you. I don't have any console.log() calls in my JavaScript. Any way thanks again!
