### ISSUE TITLE
Touch Slide Causes CurrentSlideNumber to change without changing slide

### ISSUE THREAD

**Issue by mklahorst** [iosscripts/iosslider#199]
When I am at the end of the slides and I go to advance and the slider starts to move but obviously can't complete, my currentSlideNumber decreases from Slide 2 to Slide 1 (for example), even though I haven't actually changed slides.

Using snapToChildren: true;

However, if I use the navNext/Prev selectors, this doesn't happen.

**Comment by marcwhitbread** [comment]
Interesting. Just to clarify...

Is this during the click/drag beyond the last slide?
When are you checking currentSlideNumber and getting incorrect data (onSlideChange, onSlideComplete)?

**Comment by mklahorst** [comment]
I will email you a link on where this is happening. I have the info printed in console.log and using onSlideComplete

**Comment by marcwhitbread** [comment]
Hmmm. I didn't see it come through. Did you email contact@iosscripts.com?

**Comment by marcwhitbread** [comment]
Nevermind. I found it. Make sure you send emails regarding iosSlider issues to contact@iosscripts.com in the future.

**Comment by mklahorst** [comment]
Ok, just did. Resent.
