### ISSUE TITLE
desktopClickDrag true , causing problems in Chrome with other elements

### ISSUE THREAD

**Issue by daffz** [iosscripts/iosslider#200]
Hello,
 there is an issue in every Chrome browser i've tested.

With desktopClickDrag true , it seems that the touch events are not localized on the slider.  Other elements that are not in the slider, like an audio player, is also effected ( and it makes a conflict ) making the play/pause controls unusable (  on every player i have tested ). 

If i turn off desktopClickDrag, the player works.

Here is a demo of the website that im building http://centrala.mk
At the bottom-left corner there is a audio player that works in FF, IE etc.. but not in Chrome ( this happenes only with  desktopClickDrag true, and the player is not an element of the slider )

Please help :)

**Comment by marcwhitbread** [comment]
Very odd behavior. Can you make a new page with just jQuery, iosSlider.js, your slider and the flash object? I want to confirm that no other code is somehow interfering with the flash object. It's very strange that something like this hasn't been reported already.

**Comment by marcwhitbread** [comment]
Also, remove unselectableselector: audioplayer1 from your iosSlider settings. If the audio player is not in the slider, it doesn't need to be included.

**Comment by daffz** [comment]
Sure, 
http://centrala.mk/indextest1.php  ..here it is. Just the slider, with empty blocks, and the player. It is the same. I have tried with other players,  html5 players also... same problem. The controls does not work.

**Comment by marcwhitbread** [comment]
Thanks for the demo. Your right, something weird is happening.

Is there a way I can download this flash audio player and test it on my end?

**Comment by marcwhitbread** [comment]
Nevermind, I just linked directly to your swf in stead. :)

**Comment by marcwhitbread** [comment]
If you comment out line 2219 (//return false;), you will get functionality back. That should hold you over until I can get a fix out. I will keep digging and update this issue with a fix once I have one applied.

**Comment by daffz** [comment]
Yeap, it is a quick fix. Thank you.

**Comment by daffz** [comment]
And also , i have noticed that if you put the audio player inside the slider in one of the items , there will be no problem... it will work... very strange :)

**Comment by marcwhitbread** [comment]
Fix applied in v1.1.60. Thanks for the find :)

**Comment by daffz** [comment]
Thank you too. I will get a license as soon as i start with my project successfully ( in about 10 days from now ), i hope that's not a problem. 

Cheers :)

**Comment by marcwhitbread** [comment]
No problem at all. Just don't forget ;). Thanks in advance for licensing.
