### ISSUE TITLE
Destroy is not firing.

### ISSUE THREAD

**Issue by sunpietro** [iosscripts/iosslider#204]
When I want to destroy and update the iosSlider then nothing is cleared.
I've noticed that clearStyle is not firing at all, because $this.data('iosslider') is undefined.

**Comment by marcwhitbread** [comment]
Just checked the benchmarks. $('.iosSlider').iosSlider('destroy'); is clearing the style correctly. Calling update after destroy would just undo what destroy has cleared. Can I see your JS to make sure everything is being called correctly?

**Comment by sunpietro** [comment]
I'm calling the iosSlider that way:

$widget.find('.sliding-panels').iosSlider(_.extend({
        navPrevSelector   : $widget.find('.arrow.left'),
        navNextSelector   : $widget.find('.arrow.right')
      }, customParams));

And destroying it that way:
$('.widget').iosSlider('destroy', 'clearStyle');

**Comment by marcwhitbread** [comment]
The second parameter isn't a string, it's a boolean. Proper usage: 

``` js
$('.widget').iosSlider('destroy'); //clearStyle is true by default if blank.

$('.widget').iosSlider('destroy', true); //clearStyle is true
$('.widget').iosSlider('destroy', false); //clearStyle is false
```

**Comment by sunpietro** [comment]
Still, in line 2250 it's returning me false.
I'm trying to debug your code and see where execution fails.

**Comment by marcwhitbread** [comment]
Version 1.1.60?

Also, is $('.widget') the jQuery object that iosSlider is initialized on? Based on your code, it should be: 

``` js
$widget.find('.sliding-panels').iosSlider('destroy');
```

**Comment by sunpietro** [comment]
Thanks, it was so obvious! I have complicated HTML structure and I was calling it wrongly. iosSlider inside iosSlider and everything can lead to the mistake.
Great thanks!

**Comment by marcwhitbread** [comment]
No problem. Have a good one :).
