### ISSUE TITLE
Android 2.3 issues?

### ISSUE THREAD

**Issue by lquantz** [iosscripts/iosslider#205]
Are there any known bugs when using iosSlider on Android 2.3?  We've encountered a problem whereby the slider is interfering with the operation of HTML dropdowns sharing the same page.  

This is not a problem when viewing the same page in any other version of Android we've tried (2.1, 2.2, 4.x), but is a problem on every device running 2.3.  Odd, but that's Android for you.  

If we remove the iosSlider from the page the dropdowns work fine in 2.3.  Has anyone else reported a similar issue?

**Comment by marcwhitbread** [comment]
No one else has reported any issues specific to Android recently but I know from experience that the 2.3 built-in browser has some bugs in it. Are you testing in the "built-in" browser?

Which iosSlider version are you running?

I don't mind taking a look if you have a link to the issue in question.

**Comment by lquantz** [comment]
Hi Mark,

Thanks very much for the reply.  We are testing the built-in browser on Android.  I can post a 4 minute SWF file to Vimeo or wherever showing the behavior on Android 2.3 vs 2.2 and 2.1 if you like.

You’re more than welcome to run our page in question on one of the mobile emulators at the interesting site called ‘www.manymo.com’, which has a plethora of them you can run in the browser, free of charge—registration required however.  (You get to pick a device profile and Android OS version.  Pretty neat.)

We’re using version 1.1.15 of the slider, dated Oct 15th 2012.

**Comment by marcwhitbread** [comment]
Yes a video would be helpful. Thanks! If you can provide a link that would be better though.

I don't mind creating an account. If your link is sensitive, you can email it over to contact@iosscripts.com and I'll check it there.

v1.1.15 may have some bugs that I have since fixed but nothing specific to android so it shouldn't be an issue.

**Comment by lquantz** [comment]
Thanks Mark.  I’ll send a link to the video to your contact@iosscripts.commailto:contact@iosscripts.com email address shortly.

-Larry

**Comment by marcwhitbread** [comment]
I was able to reproduce the issue using your description. Thanks!

Next step: Reproduce it on my end. I am curious about the JS on the dropdowns that are acting up. Would you be able to provide the contents of the function that opens the dropdown menu, the element that the event is bound to, and the event you are binding (I'm assuming it's 'onclick')? I tried to view source and poke around with no success.

I'm expecting to see something like: 

``` js
$('#dropdown').bind('click', function() {
     /* your function contents */
});
```

**Comment by lquantz** [comment]
Glad to hear you can replicate the issue Mark.  Thanks for the followup.

As for my followup, I’ll speak to our page designer regarding what the dropdowns are binding to, event handlers etc.  I’m almost certain your instinct is correct and there’s a jQuery bind() call in there, but I’ll confirm and have them get back to us.

Thanks again!

-Larry

**Comment by marcwhitbread** [comment]
One thing first. Just thought I would check my actual device... I have a Galaxy S2 (Android 2.3.5).

The drop downs are showing fine on the real device. Have you been able to replicate the problem on the actual hardware? VM's aren't always 100% accurate.

**Comment by lquantz** [comment]
We originally saw the problem on a test device running Android 2.3.3.  Same issue as with the emulators we tried it with subsequently.  Maybe the problem was fixed by 2.3.5?

**Comment by marcwhitbread** [comment]
Ok. Well that makes the bug case even smaller (and harder to test). Can you send over the JavaScript code I requested above? I still want to rule that out.

**Comment by lquantz** [comment]
Sure thing.  The dropdowns themselves are straightforward, with no jQuery attached to them.  The <div> container that holds them is what’s activated when you click the date button (actually an anchor tag) at the top.

When you click the Date as shown in the video, an onClick handler calls this method.  One of the steps it takes is to show the dropdowns in question.

Here’s a sample of what’s on the page when you see the date anchor tag:

<a id="lnkDateSummary" href="javascript:void(0);" onclick="OT.Widgets.Results.ProfileResults.showSearchModule();" data-role="button" data-icon="grid" data-iconpos="right"><span class="dateSummaryInner">Tue 2/26/2013 - Party of 2</span></a>

And when you click it, this happens:

var showSearchModule = function () {

```
          $("div.result").removeClass("highlightBar");
          $("#ulSlots").hide();
          $("#lnkDateSummary").hide();
          $(".noAvailabilityMessage").hide();
          $(".nextAvailable").hide();
          $("#searchModule").show(); //this is the <div> that contains the dropdowns.
   }
```

**Comment by marcwhitbread** [comment]
So the top element is the dropdown? No event bubbling correct? 

It could be possible that the focus is being lost when clicking the dropdown. If you add something like this to the event to make sure that the focus is on the select:

``` js
$('#selectDropdownId').focus();
```

Sort of grasping at straws here sorry :S.

**Comment by lquantz** [comment]
Unless something’s changed that I’m not aware of there’s no event bubbling.  We can give your suggestion a try, it sounds promising.  We’ll report back…thanks again.
