### ISSUE TITLE
Resizing square images

### ISSUE THREAD

**Issue by Ceda** [iosscripts/iosslider#206]
Resize square images don't work, when i try resize browser window. 
Landscape an portrait images work fain, but square make me trouble

**Comment by marcwhitbread** [comment]
Please provide a link to your page with the issue. I can't help at all with only 2 sentences to go on.

**Comment by Ceda** [comment]
Thx for quick reply... The problem is on this page http://pavelcahajla.cz/test/?page_id=6
Third image... When i change size of browser window.

**Comment by marcwhitbread** [comment]
It's actually not working for any of the slides if you look closely. You are missing a few CSS attributes.

Take a look at example 12 in the download package (_demos/_examples/12). The slide setup is more or less identical. Take a look at the CSS for the slide and img elements and work from that. In your stylesheet, make sure you set the max-width CSS property for the image to be the max width of the image.

Let me know if you run into any issues.

**Comment by Ceda** [comment]
In example 12 with same images is working ;) Thank you!
