### ISSUE TITLE
Margin-left extends item

### ISSUE THREAD

**Issue by wtrbuit** [iosscripts/iosslider#207]
The slider seems to interpretate the margin-left as the start point of every slide. So when the slider goes to the second item it just slides 45px instead of the 300+45 it should slide.

**Comment by marcwhitbread** [comment]
Do you have a link I can look at?

**Comment by wtrbuit** [comment]
I used an example of iosslider for this: http://wouter.nul76.nl/iosslider/

**Comment by marcwhitbread** [comment]
Thanks for the link. The margins are included in the slide width, so everything is operating as intended. if you need a gap, use margin-right and then override the margin-right from the last slide with a class.

``` css
item:last-child {
     margin-right: 0;
}
```

**Comment by wtrbuit** [comment]
Thanks fo the quick reply. This works indeed, one problem however is that :last-child is not support in IE7 and lower. But thanks for this solutions!

**Comment by marcwhitbread** [comment]
In that case your first-child CSS wouldn't have worked either :P. I usually add a lastItem class for IE7.

**Comment by wtrbuit** [comment]
You are right, my bad! I was going for that too :+1:
