### ISSUE TITLE
Hide last item

### ISSUE THREAD

**Issue by Sudhamsha** [iosscripts/iosslider#208]
Hi there!
Is there a way to hide last item? If you view the slider here http://www.koobalabs.com/wonga/ it's showing the fourth item. I don't want to show that.

Thanks,
Sud.

**Comment by marcwhitbread** [comment]
This is a CSS issue. 

You need to either change the CSS for the iosSlider element to be equal to the width of exactly 3 slides or change the slide width to be exactly 33.3~% of the iosSlider element width.
