### ISSUE TITLE
mousemove event not bubbled to components inside the iosscroller

### ISSUE THREAD

**Issue by 4dz** [iosscripts/iosslider#209]
If you put something interactive inside the iosscroller, it may not function because the 'mousemove' event does not bubble through.

In my specific example we have custom scrollbars using jScrollPane, inside the iosscroller.

They don't work properly because the 'mousemove' event is completely taken over by iosscroller.

The fix is very simple, line 1806 needs to be changed from 'return false' (which triggers preventDefault and stopPropagation) to 'return true' (so that the event is propogated).

So this is inside, $(touchSelectionMove).bind(touchMoveEvent, function(e) {

there is an if statement on line 1805,

```
                        if(!isMouseDown) {
                            return false;
                        }
```

which needs to be changed to,

```
                        if(!isMouseDown) {
                            return true;
                        }
```

Could this be included in future releases? As we try to keep up to date with the code so try not to make local modifications.

**Comment by marcwhitbread** [comment]
Thanks for the detailed description. You are right I think. I will do some testing and if everything checks out on my end I will make the change in the source. I will update this issue when this happens.

**Comment by marcwhitbread** [comment]
Seems to check out. v1.1.62 has the fix going forward. Thanks again.

**Comment by 4dz** [comment]
That was a super fast response, thanks!
