### ISSUE TITLE
Gallery thumbnails don't update if slide advanced during transition.

### ISSUE THREAD

**Issue by benlachman** [iosscripts/iosslider#21]
In both gallery demos, if you advance to the next slide while the previous transition is still completing, the thumbnail will not be updated past the previous slide.

**Comment by iosscripts** [comment]
I am able to reproduce it intermittently. For some reason I can't seem to nail down a 100% positive test case. Either way I think I fixed it. Can you try with the latest version in the master branch?

**Comment by benlachman** [comment]
Looks like it's fixed.  Thanks!
