### ISSUE TITLE
"Selected" Selectors Block out-of-sync

### ISSUE THREAD

**Issue by francisrupert** [iosscripts/iosslider#212]
- Currently reproducible in **Firefox 18**.
- [Brief Screencast](http://f.cl.ly/items/2Y3Z101E2j1H3R1W000x/iosSlider%20bug.mov).  

**Details**:
During **auto-rotation**, the cycling of `item.selected` is out-of-sync. Interestingly, it "catches up" when the actual slide rotates but then goes out of sync again — almost like they are running at two different intervals.

/c @jodythomas, @pjcampmalik

**Comment by marcwhitbread** [comment]
The demos in the download package seem to be working fine. So everything should be working.

The "selected" class is applied your onSlideChange callback? Do you have a demo I can look at? I need to see some code.

**Comment by francisrupert** [comment]
Since it's in a Client environment, I'll see how I may get it somewhere you can view. 

> "...applied your onSlideChange callback?"

This is what I have, which I don't think I changed much from one of your demos.

``` javascript
function sliderbuild() {
    $('.iosSlider').iosSlider({
        snapToChildren: true,
        desktopClickDrag: true,
        keyboardControls: true,
        navNextSelector: $('.next'),
        navPrevSelector: $('.prev'),
        autoSlide: true,
        navSlideSelector: $('.selectors .item'),
        onSlideChange: slideChange
    });
}
function slideChange(args) {
    $('.selectors .item').removeClass('selected');
    $('.selectors .item:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');
}
```

Thanks.

**Comment by marcwhitbread** [comment]
Everything looks good here, but I couldn't reproduce the bug shown in the video on my end which is odd. I think there must be something specific to your implementation? Can't say for sure.

If you can't get a live link, can you zip and send the issue in question to contact@iosscripts.com? That would work as well as a link.
