### ISSUE TITLE
Refresh slider for filtering

### ISSUE THREAD

**Issue by ghost** [iosscripts/iosslider#213]
Hi,

I tried to implement a filter option to the iosSlider. However, when I filter the items, those which are again displayed after filtering are not rearranged. I need to refresh the slider in order to avoid gaps between items.

I tried the update fonction of the slider but nothing happens.

Here is my filter jquery code:

```
$(document).ready(function() {
  $('#filterOptions li a').click(function() {
    // fetch the class of the clicked item
    var ourClass = $(this).attr('class');

    // reset the active class on all the buttons
    $('#filterOptions li').removeClass('active');
    // update the active state on our clicked button
    $(this).parent().addClass('active');

    if(ourClass == 'all') {
      // show all our items
      $('.slider').children('div.item').show();
      $('.selectors').children('div.item').show();
    }
    else {
      // hide all elements that don't share ourClass
      $('.slider').children('div:not(.' + ourClass + ')').hide();
      $('.selectors').children('div:not(.' + ourClass + ')').hide();
      // show all elements that do share ourClass
      $('.slider').children('div.' + ourClass).show();
      $('.selectors').children('div.' + ourClass).show();
    }
    return false;
}); 
});
```

Is there a way to update or refresh the slider in order to rearranged items when some are added or removed

**Comment by marcwhitbread** [comment]
Changing inline CSS attributes will be overwritten by the iosSlider script. So using hide() will be ineffective by itself.

After the hide() animation is complete, add a class to the hidden element which has the same CSS applied by the hide() method (ie. display: none; etc.', see example below). This will prevent the values from being overwritten by the plugin when updating.

``` css
.isHidden {
     display: none;
     /* other CSS */
}
```

After you make manual javascript adjustments to the slider, the update() public method must be called to recalibrate the slider. Do the reverse when adding items back (remove isHidden class and animate in).

Also, the hide() and show() jQuery methods are terrible. Use animate in stead. That way you can add a callback at the end of the animation to add the isHidden class mentioned above. This problem would by 90% less complicated without the animations (if you could live without them).

Hopefully that helps. If you have a link to a demo that I could see, that would be useful.
