### ISSUE TITLE
iosslider in ipad- scroll jumps

### ISSUE THREAD

**Issue by peterhuang** [iosscripts/iosslider#214]
when I use iosslider in my web project。I edit like this:
 $('.iosSlider').iosSlider({
                    autoSlide: true,
                    autoSlideTimer: 5000,
                    autoSlideTransTimer: 1000,
                    infiniteSlider: true,
                    snapToChildren: true,
                    desktopClickDrag: true,
                    keyboardControls: true,
                    scrollbar: true,
                    desktopClickDrag: true,
                    scrollbarMargin: '5px 40px 0 40px',
                    scrollbarBorderRadius: 0,
                    scrollbarHeight: '2px',
                    navPrevSelector: $('.prevButton'),
                    navNextSelector: $('.nextButton'),
                    navSlideSelector: $('.selectors .item'),
                    onSlideChange: slideChange
                });

```
        }); 
        function slideChange(args) {
            $('.selectors .item').removeClass('selected');
            $('.selectors .item:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');
        }
```

Desktop browsers works well , but ipad's safari has a problem, when it auto scroll to the first picture ( or item) it jumps to the first picture too. the experience effect is very poor.

**Comment by DigitalCoder** [comment]
hi ! I've got the same thinh with iosslider vertical on firefox 4.0

**Comment by peterhuang** [comment]
do you know how to solve this issue?

**Comment by marcwhitbread** [comment]
@peterhuang is the issue appearing in the demo's included in the download as well? or your custom implementation?
