### ISSUE TITLE
Input fields in chrome not working

### ISSUE THREAD

**Issue by marcwhitbread** [iosscripts/iosslider#216]
Input field in chrome not maintaining focus when selected.

**Comment by wriess** [comment]
Is there a solution for this problem allready?
Input fields in chrome not maintaining focus when selected.
onClick: there is focus
onMouseUp: focus lost

Thanx for help

**Comment by marcwhitbread** [comment]
@wriess I believe I have found the fix. Please download v1.2.6 and let me know if it's working on your end as well.

**Comment by wriess** [comment]
```
Hello Marc Whitbread,
thanx a lot for this fast support.
Now its working well.
Focus is not lost anymore in Chrome/Safari.
Greetings
W. Riess
WR MultimediaOn 07.04.13 23:33, Marc Whitbread
  wrote:

  @wriess I believe I have found the
    fix. Please download v1.2.6 and let me know if it's working on
    your end as well.
  —
    Reply to this email directly or view
      it on GitHub.

-- 
```

Mit freundlichen Grüssen

Winfried Riess
WR Multimedia

WR Multimedia
Fürther Straße 212 / Gebäude A1 / 1.OG 
D-90429 Nürnberg
Tel.: 0911 377 80 12

Mobil: 0151 46677778
E-Mail: w.riess@wr-multimedia.com
Internet: www.wr-multimedia.com
