### ISSUE TITLE
Vertically align iosSlider or resize to fit window height

### ISSUE THREAD

**Issue by jasondixson** [iosscripts/iosslider#217]
Does anyone know if there is a way to either:
1) Vertically align the iosSlider so that it is perfectly centered vertically in a window?  I've tried this in my own code, but so far have been unsuccessful.  The page I've been working on is here: http://bit.ly/WBDC1s.

or 

2) resize the iosSlider so that the height of the container is responsive to the height of the browser window.  I know that it is designed so that the container height can respond to the container width, but I'd like to make it so that an image shrinks to fit the browser height, and maintains its aspect ratio. 

Thanks!

**Comment by marcwhitbread** [comment]
This is more of a general programming problem. Not really in iosSlider issue. For stuff like this you would probably get a faster answer on StackOverflow.

Anyway, probably the best approach would be to put everything in a container element and set CSS: display: table; vertical-align: middle; height: 100%;
