### ISSUE TITLE
IE8 problem with direction RTL for arabic languages

### ISSUE THREAD

**Issue by sunpietro** [iosscripts/iosslider#218]
When you set the attribute dir="rtl" to HTML element the iOSSlider behaves incorrectly: `<html dir="rtl">`
The problem appears on the iOSSlider project site too.

**Comment by marcwhitbread** [comment]
I don't have any experience wit RTL websites so bear with me.

What impact on the slider does RTL have besides changing the text alignment? How should the slider behave? All of my research is showing that this attribute only impacts text elements, so the slides will not change either way.

**Comment by sunpietro** [comment]
Well, when you change the text direction in Internet Explorer it changes the way the browser calculates the dimensions. Slides are going too far from the container. For example, when the container is 500px wide and slide too, in IE8 with RTL attribute, the slide is moved away by 500px from the left margin of the container, that makes the slides not visible for the users. Try adding the dir="rtl" to the HTML tag and look how the browser behaves.

**Comment by marcwhitbread** [comment]
Thanks for the update. Interesting... and IE8 and below only?

I will take a look at it and see if this is something that I can fix reasonably. Seeing as this would be a small corner case for users, it may not make sense to make major changes to the script to support this.

I will update this once I have determined the course of action.

**Comment by yabasha** [comment]
I'm setting the the direction also in the body tag <body dir="rtl"> when i'm doing that in chrome or firefox (the latest versions) the slides move to the right 
![image](https://f.cloud.github.com/assets/932321/380478/ef8a3f02-a5c4-11e2-9a3c-e429504fb97c.png)

When I change the dir to ltr the slides work normally
![image](https://f.cloud.github.com/assets/932321/380484/26ac9e9e-a5c5-11e2-96b1-181fa2882594.png)

After researching, I found that I need to customize CSS Transforms Matrix, or there is an easier way?

**Comment by marcwhitbread** [comment]
Have you tried switching back to LTR in the iosSlider element div and then only applying RTL on applicable elements within the slider?

It's not likely that I will be fixing this bug will be fixed.

@yabasha IE8 does not use a transform matrix. It uses absolute positioning to place the slides. It will be very difficult to modify these values so I wouldn't recommend it.

**Comment by yabasha** [comment]
I'm not using the iosSlider on IE8, the problem of rtl support also happens on all other browsers (Chrome, FF, Safari,,,etc.)

**Comment by yabasha** [comment]
i'm using:

$('.iosSlider').iosSlider({
     desktopClickDrag: true
});

When the dir="ltr" it slides from right to left, how can I inverse the dragging when the dir="rtl"?

**Comment by marcwhitbread** [comment]
The script doesn't do any LTR/RTL checks so there is no way the script could handle inverting the dragging. You will have to do it. 

Try reversing the slide elements using some of your own JS, then using the startAtSlide parameter to start at the last slide when initializing.
