### ISSUE TITLE
infinite scroller: next, previous buttons scrolling numslides+1 slides, not 1

### ISSUE THREAD

**Issue by petehobo** [iosscripts/iosslider#22]
Hi Marc,

Firstly - thanks.  Your scroller does just what my client needs.

Unfortunately, I have an issue.  I've created a simplified example [here](http://megasponge.com/iosSlider-issue/).  It uses jQuery 1.4.4, as that's the version I'm stuck with, but it happens with the same version as the samples (1.6.1).

In essence, I have an infinitely-scrolling gallery with 4 slides and next/previous buttons.  The first two slides scroll normally, but the third and fourth scroll 5 slides instead of one.

I had a quick look at the code, and it seems the current slide number in changeSlide() is not in sync with the current offset of the slider.  For example, at the start of the third click, the startOffset is -600px, which corresponds to childrenOffsets[2], but slide is 7.

Thanks again,

Pete

**Comment by iosscripts** [comment]
Issue occurs when slides are shorter than the width of the content box. I have a working test case on my end and will troubleshoot. Thanks for using iosSlider and good find!

**Comment by iosscripts** [comment]
Please try version 0.9.4.3. I just committed it to the master branch.

**Comment by petehobo** [comment]
Looks great.  Thanks for the quick response - really appreciate it.
