### ISSUE TITLE
IE8 "Unknown Runtime Error"

### ISSUE THREAD

**Issue by 4dz** [iosscripts/iosslider#223]
Intermittently in IE8, document.selection.empty() can throw an unknown runtime error.  From researching the web this is a bug in IE8 caused when a selection is not visible, or sometimes when nothing is selected.

E.g. http://echo.nextapp.com/site/node/6326
Or https://mootools.lighthouseapp.com/projects/24057/tickets/456-html-table-selectrow-ie8-problem

Adding a try/catch around the two instances of this fixes the issue e.g. line 1743 and 1830 become,

try { document.selection.empty(); } catch(ex) {}

**Comment by marcwhitbread** [comment]
Interesting. I will take a look at it.

**Comment by marcwhitbread** [comment]
Updated in v1.2.3. Thanks for the find.
