### ISSUE TITLE
Steps to install iosslider on my magento store.

### ISSUE THREAD

**Issue by samuelmorse** [iosscripts/iosslider#224]
Hi,

Could you please assist me. How to install the iosslider on my magento store.
I gone through the http://iosscripts.com/iosslider/ , but here lot of code is there. I am confused with that code. How to use that code, and where to be pasted the code.

Please assist me. It will be greatfull to me, in fixing the slider on my home page of the website.

**Comment by marcwhitbread** [comment]
Just like the tutorial states: 
- script includes go in the head
- slider HTML goes in the body
- CSS goes in the stylesheet
- jQuery iosSlider code goes in the head following the script includes.

If that's not straight forward enough, then you need to improve your general programming knowledge. iosslider is a tool for developers, so you are required to have a basic understanding of HTML/CSS/JS/jQuery to be able to use it. In this case, you would also need Magento template experience also (which I cannot assist with).

Sorry for the inconvenience.

**Comment by samuelmorse** [comment]
Hi marcwhitbread

Thanks for the steps.
Is it should be added in the home.html or in any other files to be added.

## 

Sam

**Comment by marcwhitbread** [comment]
If you are referring to Magento specifically I'm not sure. 

If you mean in general, you can find some demos in the download package to show you some possible code setups, but there are no set rules.

**Comment by abrar006** [comment]
![screen shot 2013-06-13 at 1 42 45 pm](https://f.cloud.github.com/assets/3853520/647460/58ced95a-d405-11e2-8f84-27888c7aa6c8.png)

**Comment by marcwhitbread** [comment]
I have no idea how that theme was setup so I'm not sure what the issue is or even how to approach it. I'm also not a Magento developer. 

You will have to contact the maigeetheme developers for assistance with any slider visual changes. Maybe you could try a Magento CMS developer forum?
