### ISSUE TITLE
iPhone / Andorid showing Half Image 

### ISSUE THREAD

**Issue by therockstar** [iosscripts/iosslider#229]
G'day Marc,
Hope you are doing good.
I am using iosSlider on my mobile website. However I am facing strange problem the sliding image showing half in iPhone / Andorid (portrait mode). 
Please help you can see the preview over here ... http://ascentis.com.sg/labs/demo/

have a wonderful day

Cheers

here's the CSS

.iosSlider {
                width: 640px;
                height: 360px;
            }

```
        .iosSlider .slider {
            width: 100%;
            height: 100%;
        }

        .iosSlider .slider .item {
            position: relative;
            top: 0;
            left: 0;

            width: 640px;
            height: 360px;
            background: #000;
            margin: 0 0 0 0;
        }

        .iosSlider .slider #item1 {
            background: url(i/slide-1.png) no-repeat 0 0;

        }

        .iosSlider .slider #item2 {
            background: url(i/slide-1.png) no-repeat 0 0;

        }

        .iosSlider .slider #item3 {
            background: url(i/slide-1.png) no-repeat 0 0;

        }

        .iosSlider .slider #item4 {
            background: url(i/slide-1.png) no-repeat 0 0;

        }

        #slider-pan
        {
            width:100%;
            margin-top:70px;
        }
```

**Comment by marcwhitbread** [comment]
2 things should be changed. Based on your implementation, I would recommend working from example 12 in the download package. The only major difference between yours and this is the use of img elements as slides in stead of div's with background. This will allow the image to scale proportionally when resized.

In addition, you will also need to add a media query to your CSS to update the .iosSlider and slide elements width to work with the new window size. In this case, width: 100% would be sufficient.

**Comment by therockstar** [comment]
Thanks for reply mate  
I will make that changes and let you know :)  
Enjoy your weekend  

## 

Romi Farooqi
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by therockstar** [comment]
@marcwhitbread G'day how are ya? hope you are fine i have made the changes and its working fine. Thank you so much =)

Cheers!
