### ISSUE TITLE
Javascript error when tapping on a 'slide'

### ISSUE THREAD

**Issue by peduarte** [iosscripts/iosslider#23]
Only happens on touchscreen device (not on desktop).
Error says:
'undefined' is not an Object.

Event happens on the iosSlider plugin website.

The iPhone inspector does not show line number or anything, very difficult to debug.

**Comment by iosscripts** [comment]
Indeed. I am aware of this, I have a few leads. It has something to do with the minor issue touchstart/end without triggering the touchmove event in between. I will most likely have a resolution for the next release.

**Comment by peduarte** [comment]
Yeah I tried debugging it but no luck so far. Thanks

**Comment by iosscripts** [comment]
Just updated the master branch with a fix. Please let me know if it solves the JS error you are experiencing.

**Comment by peduarte** [comment]
Yeah sweet, that works. Thanks.
