### ISSUE TITLE
Microsoft Surface support

### ISSUE THREAD

**Issue by jaworskig** [iosscripts/iosslider#230]
I tried to run example web page on MS Surface with IE10 and it's not working, do you know what can be a reason, of course on normal pc with IE10 it works pefect.

Does anyone have experience with this device and sliding support ?

**Comment by marcwhitbread** [comment]
I haven't used one of these new surface tablets yet so I have not been able to test it. I would assume that it is not going to work without some minor code adjustments.

I will pick up a surface tablet over the weekend and do some testing.

**Comment by marcwhitbread** [comment]
Added support for ie10 ms surface tablets in v1.2.0.
