### ISSUE TITLE
Multiple "slideChange" to control a single slide

### ISSUE THREAD

**Issue by kwagsthlm** [iosscripts/iosslider#232]
Is it possible to have several "slideChange" to control one and the same slider.
If so, how do I do?

Grateful for answers!

**Comment by marcwhitbread** [comment]
Well, you don't need multiple instances exactly. What about this approach?

``` js
$('.iosSlider').iosSlider({
    onSlideChange: function(args) {

        func1(args);
        func2(args);
        func3(args);

    }
});
```

**Comment by marcwhitbread** [comment]
> I deleted your comment by accident

Thank you, marcwhitbread, for your quick response.
I tried like this;

``` js
$('.iosSliderWide').iosSlider({
snapToChildren: true,
desktopClickDrag: true,
keyboardControls: true,
navNextSelector: $('.next'),
navPrevSelector: $('.prev'),
navSlideSelector: $('.selectors .item'),
onSlideChange: function(args) {
func1(args);
func2(args);
}
});
function func1(args) {

$('.selectors .item').removeClass('selected');
$('.selectors .item:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');

}

function func2(args) {

$('.selectors .item').removeClass('selected');
$('.selectors .item:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');

}
```

And then;

``` html
<div class = 'selectorBlock'>...</div>
```

at two places in the code. It's only the last 'selectorsBlock' called that is working.

**Comment by marcwhitbread** [comment]
I think you are confused about what this is supposed to do. you're calling the same code twice on slide change so naturally the first function would be overwritten by the second.

**Comment by kwagsthlm** [comment]
Yes, you got me. I'm confused.

I want to have two "controllers" for one slider. I have no idea how to accomplish that. Will you help me?

**Comment by marcwhitbread** [comment]
Ah, I think I understand. You want 2 sets of indicators to be both clickable (navigate between slides) and highlighting on slide change? I don't normally offer support for customizing implementations, but here's a freebee. 

Like so:

onSlideChange should be like this to update the highlighting:

``` js
onSlideChange: function(args) {

    $('.selectors .item').removeClass('selected');
    $('.selectors .item:nth-child(' + args.data.numberOfSlides + 'n+' + (args.currentSlideNumber) + ')').addClass('selected');

}
```

To make both sets of indicators clickable.

``` js
//remove the "navSlideSelector: $('.selectors .item')" line from the code
$('.selectorBlock').each(function() {

    $(this).find('.selectors .item').each(function(i) {

        $(this).bind('click', { num: i }, function(e) {
            $('.iosSliderWide').iosSlider('goToSlide', (e.data.num+1));
        });

    });

});
```

Keep in mind this this is just straight up jQuery. If you need any further jQuery or general programming help, try one of the many popular programming help websites.

**Comment by kwagsthlm** [comment]
Thank you so much! That was the "Nail in the coffin". Count on me sign up for a license and maybe i'll post you an link of the implementation.

**Comment by marcwhitbread** [comment]
Glad it all worked out. And thanks in advance for licensing! :)
