### ISSUE TITLE
Fixed height is an issue for variable content

### ISSUE THREAD

**Issue by AlexWebLab** [iosscripts/iosslider#235]
I'm trying to use the iosslider to display the excerpt and the featured image of all sticky posts in my wp theme. The problem is that I don't know how much will be long the text of the excerpt so I can't decide the height of the slider. Is there any chance to adapt the height of the slider on the content inside?

**Comment by marcwhitbread** [comment]
Right now this is a limitation of the script and CSS in this situation. 

Even if the variable slide height were possible, you would run into other issues where each slide would have varying heights based on content. So unfortunately, iosslider is not going to work well with your implementation if the variable height is a major requirement.
