### ISSUE TITLE
iOS clicking too quick breaks slider

### ISSUE THREAD

**Issue by kevshub** [iosscripts/iosslider#236]
I've found that if you click the slider before its had a chance to set itself up the slide / snap functionality does not work and when you slide the slider it stops wherever you leave your finger and does not snap to a slide. You have to close the app right down and start it again.

This only happens on IOS i think it has something to do with the binding and the flag to mark its been touched, if i find the exact cause ill post it up here.

**Comment by marcwhitbread** [comment]
Which version? I just fixed a very similar issue.

**Comment by kevshub** [comment]
Version: v1.2.0 (03/23/2013)

**Comment by kevshub** [comment]
Could i suggest that if you added a debug mode to the plugin, just a variable that was true or false then if it was set to true you console.log everything that happens from within the plugin (maybe just a separate debug js file) that was it would make it easier to see where its failing and you could find the cause of problems quicker?

**Comment by marcwhitbread** [comment]
Give v1.2.4 a shot and let me know if that works. I updated it 8 hours ago.

**Comment by kevshub** [comment]
awesome, cheers buddy. Also ill be sending some money your way as soon as i get this working. Really appreciate your work on this plugin its awesome :)

**Comment by marcwhitbread** [comment]
Glad to hear you like the slider, and thanks for your support :). Let me know if you run into any other bugs.

**Comment by kevshub** [comment]
Yup, thats fixed it!

I've added a hack to it that recognises a tap, it probably needs to be made more friendly but would you like me to send it your way to consider adding? I'm using your slider for a free project im making which will be going on the app store for free.

**Comment by marcwhitbread** [comment]
> I've added a hack to it that recognizes a tap

Not sure I understand what you mean by that. If you want, use the pull request method above ^^ . That way I can see your specific line by line changes.

**Comment by kevshub** [comment]
When i say recognises a tap i mean; the difference between a user sliding to the next slide or tapping the slide to go "into the content" because in ios "onclick" is too slow, and you can't bind a touchend because it overwrites your functionality so i added a line in the touchend to see if the touch xScrollStarted is false then activate the tap

if (xScrollStarted != true) { if (args.currentSlideObject.data("action")) { sliderTapCallback(true); return true } }

Could probably be done a bit more cleanly but it has the desired effect.

If you tap the slide without moving it then the function is called (its a quicker onclick without the delay - in ios anyway)

**Comment by kevshub** [comment]
The above line goes above;

$(touchSelection).bind('touchend.iosSliderEvent', function(e) {

it would be better to overwrite the onclick usual behaviour and run whatever function is in onclick because it keeps it the code cleaner. Onclick does of course work, but theres a 500 ms delay in ios which makes it look like it didnt recognise your tap :)

**Comment by kevshub** [comment]
I'm new to version control and github so i havent got the hang of push / pull stuffs yet sorry!

**Comment by marcwhitbread** [comment]
No problem. I understand the issue now. I'll take a look at your edit and consider adding it to the script. Thanks for the suggestion! :)
