### ISSUE TITLE
Last item no fully shown

### ISSUE THREAD

**Issue by wtrbuit** [iosscripts/iosslider#238]
I have a problem where the last item in mij slider isn't fully shown.
http://goo.gl/4Hqan > the submenu under "Producten", the last item

I am experiencing this on another website with only 4 larger slides > http://goo.gl/WDfVY

**Comment by marcwhitbread** [comment]
![Screen shot 2013-04-03 at 11 40 42 AM](https://f.cloud.github.com/assets/1944274/334511/2be98e48-9c75-11e2-8639-98e6fd0a3e6a.png)

is this the slider you are referring to? I don't see any clipping on the last item. Am I looking in the wrong place?

**Comment by wtrbuit** [comment]
Actually to both. When my browser window is big the last item isn't shown fully. But when I decrease it to 960px the last item is shown fully. As seen on the screenshot the yellow one is the third item and the blue one is the last.

![screenshot 3](https://f.cloud.github.com/assets/2961836/334623/df6d83f0-9c77-11e2-9ac4-a76dca2efcad.png)

The browser size is smaller now:
![screenshot 4](https://f.cloud.github.com/assets/2961836/334624/df931f84-9c77-11e2-950d-4d7e95096b89.png)

**Comment by marcwhitbread** [comment]
What page is this occurring on? I need to see the source.

**Comment by wtrbuit** [comment]
this one -> http://goo.gl/WDfVY

**Comment by wtrbuit** [comment]
I believe the problem was the container of the slidercontainer. This had a width of 100%.

I had this:

<code>&lt;div container&gt; /\* width:100% */</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div slidercontainer&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div slider&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div slider&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div slidercontainer&gt;</code>
<code>&lt;/div container&gt;</code>

I needed another container for the slidercontainer with the right width set up to get it to show the last item properly.

So:

<code>&lt;div container&gt; /\* width:100% _/</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div extracontainer&gt; /_ width:960px */</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div slidercontainer&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div slider&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;div item&gt;&lt;/div item&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div slider&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div slidercontainer&gt;</code>
<code>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/div extracontainer&gt;</code>
<code>&lt;/div container&gt;</code>
