### ISSUE TITLE
infiniteSlider causes slides to move over each other (-webkit-transform:matrix issue)

### ISSUE THREAD

**Issue by wtrbuit** [iosscripts/iosslider#241]
I have 6 items in my slider and when the website is loaded on a desktop or tablet I show three items but when the website is loaded on mobile it only shows one item. It was all working fine until I added infiniteSlider.

The website: http://www.ploumoverdecloud.nl/whitepapers/privacy-de-cloud/ (in the bottom)

On start:

![Screen Shot 2013-04-05 at 10 09 42](https://f.cloud.github.com/assets/2961836/342895/b7f6f99e-9dc8-11e2-8ae1-f9d94e314ef2.png)

After one touch on the slider:

![Screen Shot 2013-04-05 at 10 09 58](https://f.cloud.github.com/assets/2961836/342898/c5bb08fe-9dc8-11e2-9586-da707c3cab63.png)

As you can see a couple of items have the same value on -webkit-transform

**Comment by marcwhitbread** [comment]
I've never seen this happen before. Can you make sure that your CSS is a bit tighter? The iosSlider and slider elements in your site do not have width attributes defined. Not sure why this would happen with infiniteSlider on exclusively, but it could be causing the stacking issue.

**Comment by wtrbuit** [comment]
The problem was indeed the CSS. I accidentally gave an overruling width to the .slider. Got that out of the way and know it runs good. Thanks for the help!
