### ISSUE TITLE
Options for threshold on horizontal & vertical scrolling

### ISSUE THREAD

**Issue by a-budhraja** [iosscripts/iosslider#242]
Hi. First up, thanks for this awesome plugin.

I'm working on an iOS app made with Phonegap/Cordova + JQM

Each slide of the slider also has a list of items which are populated dynamically each time using an Ajax call. This list is vertically scrollable as well.
Now the user can swipe to change the slide and scroll through the items to parse each list.

As long as the user is using a strictly vertical swipe motion, things are good. But as soon as  the gesture starts getting diagonal, the problems start. And more so if the velocity of the gesture is larger (ie, a diagonal flick gesture).

In a single-handed operation, the probability of a diagonal gesture occurring is extremely high. Thus i would like to enforce some sort of threshold distance on the gestures.

JQM has mapped the swipe event & provides some global configuration variables (http://api.jquerymobile.com/swipe/). I tried changing those values, but it had no effect.

So I'd like to know if some such option is available in the slider to do this. Or, well, any other alternative.

Thanks in advance..

**Comment by marcwhitbread** [comment]
Which theshold are you looking to control:
- modify the minimum velocity threshold for snapping to the next/prev slide on touchend?
  or
- modify the minimum velocity threshold before any horizontal sliding can occur on touchmove?

**Comment by marcwhitbread** [comment]
I added 4 threshold variables that will allow you greater control to when the slider will begin, lock axis movement, and snapping in v1.2.5. Let me know if those help at all.

**Comment by a-budhraja** [comment]
I was looking for something to modify the minimum velocity threshold before any horizontal sliding can occur on touchmove.

Thanks a lot for adding the threshold variables. I'll give it a go and get back to you guys..

**Comment by a-budhraja** [comment]
Those threshold variables work like a charm, adding the much needed control i needed for the horizontal vs vertical movement.
Thanks a lot for the prompt resolution!

**Comment by marcwhitbread** [comment]
Thanks for the update. I'm happy to hear it worked :)
