### ISSUE TITLE
Support for variable width images?

### ISSUE THREAD

**Issue by luetkemj** [iosscripts/iosslider#243]
Is this possible with this plugin? Looking through the examples and am seeing that in ever example all images are the same width. Would love to have images that can be variable width in this demo: "13-full-width-image-slides"

**Comment by marcwhitbread** [comment]
The plugin does support variable width slides. If the CSS of your slides to reflects either dynamic width or static variable width slides, the plugin should be able to handle it.

**Comment by luetkemj** [comment]
Awesome! To be clear this can be done without margins between the slides? It looks like this one does something similar but has margins between images: 7-Centered-Slides/2-Background-Images/

Appreciate the quick reply!

**Comment by luetkemj** [comment]
Playing around with the demos and yes! It does appear to do exactly that! Now to muck around till I figure out how to get the active image to center instead of left align. 

Thanks for the awesome plugin! Been looking for something like this for a LONG time!
