### ISSUE TITLE
Slider Swipe Not Smooth On IPAD After Hide or Display: None the Iosslider

### ISSUE THREAD

**Issue by poetra72** [iosscripts/iosslider#244]
I get a problem on showing iosslider on ipad.

I create button to show and to hide Iosslider.
Before i press the the hide button, iosslider was working great, but after i hide it using display:none function then i show it again, the slider not move smoothly when i swipe it.

Anybody Help me?

**Comment by marcwhitbread** [comment]
I'm not sure exactly what you mean by "not smooth". I may need you to be more specfic by sending over a demo or your code so that I can work toward a fix.

You may need to recalibrate the slider after hiding it. After you show the slider, you may want to try recalibrate it using $(element).iosSlider('update'); and see if that helps. Also, you can try reinitializing it completely like so:

``` js
/* destroy plugin on element */
$(element).iosSlider('destroy');

/* reload plugin */
$(element).iosSlider({
     /* your parameters */
});
```

Let me know if either of those help.

**Comment by joepdooper** [comment]
Hello Marc,

I think I have the same problem as Poetra72.

When I click on a button to show the slider with java like .show() or .css() the slider doesn't work properly anymore on the iPad. What happens is when you drag and let go of the slider it stays on the position it was, so it doesn't correct its position. While if you don't hide and show the slider it works flawlessly.

I tried a millions things and I tried your $(element).iosSlider('update'); but then it doens't use the 'return false' which means my website reloads…

You can see everything here > http://www.brandtontwerpbureau.nl/test > click on portfolio to show the slider.

**Comment by marcwhitbread** [comment]
@joepdooper Please download v1.2.11. A fix was added for a similar bug since 1.2.0. Let me know if that helps.

**Comment by joepdooper** [comment]
It works, great, thanks! Only one comment; it jumps a little bit when you drag, also on the desktop…

**Comment by marcwhitbread** [comment]
@joepdooper hmmm. what do you mean by jump? performance lag?

**Comment by joepdooper** [comment]
No performance lag. While dragging it jumps slightly faster into the right position. I replaced the jquery.iosslider.js and the inline script. 

You can see everything here > http://www.brandtontwerpbureau.nl/test > click on portfolio to show the slider.

**Comment by marcwhitbread** [comment]
Fixed in v1.2.13. Please let me know if it's working on your end.

**Comment by joepdooper** [comment]
Yes this is it! Great!

**Comment by JDAllen007** [comment]
I have swiping problems on my ipad 32 gb. I dont know what you guys are talking about, but can you help me or can I use the information provided here somehow, to fix the swiping issues on my ipad?

**Comment by joepdooper** [comment]
Are you using the latest iosslider.js? For me replacing the old with the latest worked. V1.2.13

**Comment by JDAllen007** [comment]
Just had to restore and start new it worked fine. Thanks for the quick responce though.
