### ISSUE TITLE
Problem with infinite sliding and 2 slides only.

### ISSUE THREAD

**Issue by sunpietro** [iosscripts/iosslider#246]
When infiniteSlider = true and there are only two slides, the prev button doesn’t work well. Both prev and next button works the same and slider moves only right.

**Comment by marcwhitbread** [comment]
Ah, I see it. Definitely a bug. Basically the slider is trying to decide which is the shortest path, backward or forward when infinite. In this case, it's seeing them as the same distance so it picks the same direction for both buttons.

I will update this issue once I have a fix.

**Comment by dscafati** [comment]
And something else, the slider is not continuous in this case! and when this have only one slide, infinitieSlider = true produces that the slider be positioned at the right of himself (in the position of the next slide) and this cannot be displayed. Sorry for my english

**Comment by marcwhitbread** [comment]
@dscafati the slider is never really continuous or infinite. In fact, the way the slider works is that in stead of duplicating slides forever in both directions, slides simply "leap frog" over each other to appear that way. This is the cleanest and most efficient way of building an infinitely scrolling slider. So that's why an infinite slider with 1 slide will not work.

**Comment by dscafati** [comment]
no no, i was trying to say that when i have two slides, the "visual effect" is not like a infinite slider. First disappear one slide, and when it finish, the second slide start to move. (Not continuous, space between the 2 slides).
When i have only one slide, this is positioned at the right of the container, as a second slide waiting to be showed, and its not visible.

**Comment by dscafati** [comment]
and, if i have more than two slides, and i press fastly the next button, when the slider finish, this continuity breaks again, doing the same effect mentioned in the previous comment

**Comment by dscafati** [comment]
sorry, really is not "press fastly", is "press before the last slide has finished to move on the screen"

**Comment by marcwhitbread** [comment]
Fix applied to v1.2.15 for directional sliding. Visual direction will be consistent with directional button pressed.

**Comment by martinstender** [comment]
I'm sorry to bring down the room, but the problem persists (two slides with next/prev going in the same direction)
It's fine when there are three slides or more... -.-

**Comment by ubiquitas** [comment]
yep, 2 slides caused auto slide to slide backwards instead of forwards - paying customer here, please fix asap as it looks real bad. thanks

**Comment by nicmare** [comment]
probem still exists!! please fix that. iosslider needs at least 3 slides to work properly with infiniteloop. why is the issue closed?!

**Comment by marcwhitbread** [comment]
@nicmare what issue above are you experiencing? Is the sliding going in the wrong direction? or are the slides not appearing correctly?

**Comment by nicmare** [comment]
yes. just create an iosslider with two items and infiniteSlider: true.
now if you use api functions for next and prevslides, they go to the wrong directions sometimes:
$(".iosslider").iosSlider('nextSlide');
$(".iosslider").iosSlider('prevSlide');
i use these on anchors

**Comment by marcwhitbread** [comment]
@nicmare I see it. Can you confirm that if you wait for the slide to come to a complete stop and click next again you see the appropriate behaviour. Just want to make sure we are seeing the same thing.

**Comment by nicmare** [comment]
marc, if you visit my testserver 
and use keyboard right and left keys, you will see that left button moves the slider forward. its the wrong direction!

**Comment by marcwhitbread** [comment]
@nicmare Fantastic example. I will take a look at the code and fix it.

**Comment by marcwhitbread** [comment]
@nicmare I have applied a fix for this issue. Please download from master or branch issue/246 and try it out.

**Comment by nicmare** [comment]
yea. finally! seems to work properly now! thank you marc (you can see it on my testserver).
