### ISSUE TITLE
Items overlapping in IE7 & IE8

### ISSUE THREAD

**Issue by wtrbuit** [iosscripts/iosslider#247]
I have a submenu with iosslider. The problem I'm facing is that the items overlap in IE7 and IE8 but when I resize the browser window the items appear as they should.

<b>IE8</b>
![screenshot 9](https://f.cloud.github.com/assets/2961836/367528/aa6c29f6-a2ab-11e2-89ff-bef7e0dbbd7a.png)

<b>IE7, as you see the left postions are all wrong</b>
![screenshot 10](https://f.cloud.github.com/assets/2961836/367527/aa563de4-a2ab-11e2-8813-7863fa1c9e9d.png)

**Comment by marcwhitbread** [comment]
Ah, the width 0px issue. That's indicative of a slider that has been loaded while hidden or contained within a display: none element. When the slider is initialized while hidden, sizing issues can occur. 

When you show the sub menu, if you call $(element).iosSlider('update'); that should recalibrate the slider without needing to resize the browser.

**Comment by wtrbuit** [comment]
Thanks for the quick comment. I actually don't hide the slider, It just hides with a min top position. But the update fixed the problem!
