### ISSUE TITLE
The onSlideComplete callback does not seem to be triggered every time

### ISSUE THREAD

**Issue by stephaneeybert** [iosscripts/iosslider#25]
On Firefox 12.0 on my Linux pc the onSlideComplete callback is not call every time.

On my iPod Touchon iOS 5 is it never called.

Here is how I use it:

```
onSlideComplete: function(args) {
  selectPageTab(args[currentSlideObject].find('a').attr('elearningExercisePageId'));
}
```

It can be tested live at:

http://www.learnintouch.com/elearning/exercise/55/page/225/subscription/

Kind Regards,

Stephane

**Comment by iosscripts** [comment]
It is firing every time, but it's throwing a JS error. Watch your syntax.

Try: $(args.currentSlideObject).find('a').attr('elearningExercisePageId');

Let me know if that helps :)

**Comment by stephaneeybert** [comment]
Oh my.. :-)

Thanks for your patience and kindness !

**Comment by iosscripts** [comment]
No problem.
