### ISSUE TITLE
iosSlider 'unlock' not working

### ISSUE THREAD

**Issue by eyalbeker** [iosscripts/iosslider#251]
I'm creating an iosSlider which contains images. At page load the iosSlider has to be locked. So I added the function $('.iosSlider').iosSlider('lock'); This works great.

But when a user clicks a link on te page, the slider has to be unlocked. I tried using the code $('.iosSlider').iosSlider('unlock'); but this doesn't work. I added this code in a function which is triggered once the link is clicked (I know it is triggered because i alerted a message in this function which is displayed on the website).

Does anyone know a solution for this problem?

**Comment by petermeester** [comment]
I'm having the same issue like above. Does somebody has a solution for this?

**Comment by marcwhitbread** [comment]
Let me take a look at it. I should be able to sort it out.

**Comment by eyalbeker** [comment]
Ok thanks. Do you need a piece of code from me or are you looking into the class of iosSlider itself?

**Comment by marcwhitbread** [comment]
No that's ok. I am seeing the issue in my benchmarks from the download package so I should be good.

**Comment by marcwhitbread** [comment]
Fixed in v1.2.11. That's for reporting the bug. Let me know if it's working for you as well.

**Comment by eyalbeker** [comment]
Yes it's working now! Thanks for the quick update!

**Comment by marcwhitbread** [comment]
No problem. Glad to hear it's working now. :+1:
