### ISSUE TITLE
item elements in two rows?

### ISSUE THREAD

**Issue by s-coder** [iosscripts/iosslider#253]
Hi i have try to develop something like this: 
http://s-coder.com/projects/mecom/wp3/leistungen/portfolio/
(this example is using different sliding plugin but i want to achive same effect using iosslider, and isotope sorting will be added later)

I want to reduce .slider (element) width by using this logic (total width / 2) and then i will add float:left to .item elements and i should get the items sorted in two rows.

But i am not able to reduce width of the .slider element, here is the link of my code:
http://jsfiddle.net/9VpKg/7/

i have try to manualy edit width with css, and i have also try to use $('.iosSlider').iosSlider('update');  but i am not able to get this effect.

**Comment by marcwhitbread** [comment]
You cannot control the CSS width of elements via javascript on elements managed by the iosslider plugin because it needs to control these properties to ensure everything is calibrated correctly.

My recommendation: Add a container around the outer iosslider element and apply your width changes to that. If you set your CSS width for your outer iosslider element to 100%, it will resize properly based on its parent when update is called.

eg:
HTML

``` html
<div class = 'container'>

    <div class = 'iosSlider'> <!-- other stuff --> </div>

</div>
```

CSS

``` css
.iosSlider {
    /* other stuff */
    width: 100%;
}
```

JS

``` js
$('.iosSlider').iosSlider({
    /* other parameters */
    onSliderUpdate: someFunc
});

function someFunc(args) {

    $('.container').width(someWidth);

}

$('.iosSlider').iosSlider('update');
```

**Comment by s-coder** [comment]
thanks for your quick answer,
i was thinking about same thing, but by doing this i can change size of complete  iosSlider container, and i can not force .item elements to be sorted in two rows.

here is sample with resizing container:
http://jsfiddle.net/Q4YHt/

is there any other posibility to sort items in two rows in one slider?

**Comment by marcwhitbread** [comment]
Yep that wont work either. You are altering the slide width after the slider has already been calibrated. Just as I said before, you cannot alter these values without breaking the slider.

> is there any other possibility to sort items in two rows in one slider?

This is an issue with html in general. You wont be able to sort items into two rows within a div evenly with just HTML/CSS. Some JS is definitely required. Try adding an additional container within the slide element, and then apply your width to that element. If you initialize the slider after setting the container width, the slider variables will still be intact and it should work.
