### ISSUE TITLE
Help me, iosSlider auto run 5 slider at time.

### ISSUE THREAD

**Issue by vhamail** [iosscripts/iosslider#255]
Please help me,

I have iosSlider, i set autoSlide: true. Now i want it auto run 5 slider at time. I try some way, but not run for me!

thanks.

**Comment by marcwhitbread** [comment]
Any error messages? Show me your iossldier JS.

**Comment by vhamail** [comment]
This is my code, it have no next/preview button, with param: autoSlider:true
With this code, Its work!! But i think is not pro. 
You can edit my code? thank you.

<script type="text/javascript">
    $(document).ready(function() {
        
        $('.iosSlider').iosSlider({
            snapToChildren: true,
            desktopClickDrag: true,
            keyboardControls: true,
            snapToChildren: true,
            scrollbar: true, 
            autoSlide:true, 
            onSlideComplete: slideComplete
        });
        
    });
   
   
   var nextNumber=5;
   
   function slideComplete(args)  { 
        if(nextNumber !=args.currentSlideNumber) {
         $('.iosSlider').iosSlider('goToSlide', nextNumber);  
       }else {
          nextNumber= nextNumber+5;
       }
   }
</script> 

![111](https://f.cloud.github.com/assets/4253381/434475/b5c1e6c8-af45-11e2-9c7a-85bedbdd272c.jpg)

**Comment by marcwhitbread** [comment]
Unfortunately, I wont be able to fix it for you. This is an implementation problem, so putting in the effort must be your responsibility and you will have to rely on your own ability to solve this. 

If you need general programming assistance, ask your question in a programming forum like stackoverflow.

**Comment by vhamail** [comment]
ok,thank you.
