### ISSUE TITLE
No snap to final position upon fast sliding on desktop

### ISSUE THREAD

**Issue by mathbr** [iosscripts/iosslider#256]
If using the desktopClickDrag and snapToChildren option sliders sometimes but reproducible fail to properly snap to the final position on desktops. This issue occurs if the sliding happens really fast and can even be reproduced on the slider on iosscripts.com. (As can be seen by the text on the slide not appearing until clicked somewhere else.)

Due to this, the "slidecomplete" callback is never called in such cases.

**Comment by marcwhitbread** [comment]
I'm not seeing your issue on my end. Can you define "sometimes"? Any idea what causes this to occur for you?

**Comment by mathbr** [comment]
I can mostly reproduce it on your project site by sliding the slider quickly and far roughly 5 or 6 times. If the issue occurs, the promotion texts on the slides do not appear unless clicking somewhere.

It seems the far movement seems to be the key here since the issue occurs in our project with narrow slides which can obviously travel quite far during drag.
