### ISSUE TITLE
overflow-y: visible?

### ISSUE THREAD

**Issue by luetkemj** [iosscripts/iosslider#258]
None of this seems to work:

stageCSS: { [ 'overflow-y' ]: 'visible' }
stageCSS: { overflow-y: 'visible' }
stageCSS: { overflowY: 'visible' }

I also tried setting stageCSS overflow to visible and using and !important tag in my css for hiding overflow-x and that also was no good.

Am I missing something?

All I need is a 3px space for an overlapping graphic on slides (paperclip)

Quick edit: found a solution to my own problem but still curious if this is available in the plugin. 
For anyone else, I set the containing element to overflow-x hidden and gave it enough top padding to show my graphic.

**Comment by marcwhitbread** [comment]
The css attribute available for customization is "overflow", not "overflow-y". If you want to edit the source to add overflow-y, you can find it on line 1182 within: `$(stageNode).css({});` of v1.2.13
