### ISSUE TITLE
Option to make certain areas within a slide unselectable.

### ISSUE THREAD

**Issue by iosscripts** [iosscripts/iosslider#26]
This would be useful for making a portion of a slide's inner text to be highlight-able/copy/paste friendly. This option would accept a jQuery selector, those selected elements would override the slide functionality when touched, the slider would do nothing and the content would revert back to default browser behavior.

**Comment by acentofante** [comment]
Anyway this is coming soon?  Using this awesome plugin for a fullscreen sliding website and would need some areas like forms and buttons to be clickable.  Thanks!

**Comment by iosscripts** [comment]
Not too hard to implement I don't think... I can prioritize it.

Don't forget to buy a license if it's a commercial project :P

**Comment by acentofante** [comment]
awesome, was going to wait to buy as I am still juggling technologies for
this project. originally was going to go with this one until I realized not
being able to click was a deal breaker.  Thanks for being quick to respond.

On Wed, Jul 25, 2012 at 2:50 PM, Marc Whitbread <
reply@reply.github.com

**Comment by iosscripts** [comment]
Hey, no worries. I wouldn't want you to buy it if it wasn't exactly what you are looking for anyway :).

**Comment by acentofante** [comment]
oh and while I have your ear, would it be easy to add a hashtag to the url
to allow for browser forward and back?  I was thinking it would use the
onSlideComplete somehow.

Andrew

On Wed, Jul 25, 2012 at 4:28 PM, Marc Whitbread <
reply@reply.github.com

**Comment by iosscripts** [comment]
@acentofante Do you mean overriding the back/forward browser functionality? That isn't supported by this script. You could add a hash onSlideComplete though:

``` js
$('.iosSlider').iosSlider({
    onSlideComplete: slideComplete
});

function slideComplete(args) {

    window.location.href = '#page-' + args.currentSlideNumber

}
```

**Comment by acentofante** [comment]
I guess I dont understand this well enough because what you provided
definitely worked to add the hashtag but did make the browser forward and
back button trigger anything.  I probably wont be able to figure this out
but its not a big deal.  Thanks for your help.

On Thu, Jul 26, 2012 at 9:47 AM, Marc Whitbread <
reply@reply.github.com

**Comment by iosscripts** [comment]
v1.0.24 has a new parameter 'unselectableSelector', which accepts a jQuery selection of objects and disables touch/click move events on them, allowing for click+drag/input fields/buttons to be used safely. 

Also, I am aware how terrible the parameter name is... LOL

**Comment by acentofante** [comment]
Hey Marc,

Having trouble implementing this.  It seems to disable the drag functionality but doesn't allow for selection/fields/buttons.  It also doesn't work on child elements so I have to add this class to every element.

**Comment by iosscripts** [comment]
Try version 1.0.27. All child elements are now automatically included under the selection for 'unselectableSelector'. I have also fixed the issue with input elements becoming unresponsive. Let me know if you are still experiencing issues.

**Comment by kevinsmith22** [comment]
Hello Marc,
I'm experiencing some issues using HTML5 range input: with unselectable disabled no access to the element, while with unselectable enabled the elements keeps the focus (and moving) after mouse up.
Can you confirm this behaviour?

**Comment by iosscripts** [comment]
@kevinsmith22 I haven't tested it before actually but I just tested it and can confirm this behavior on my end. I will open a new issue and track it there. https://github.com/iosscripts/iosSlider/issues/170
