### ISSUE TITLE
autoSlideToggleSelector Uncaught Exception

### ISSUE THREAD

**Issue by rwohleb** [iosscripts/iosslider#262]
In jquery.iosslider.js on line 1562, the click event handler for autoSlideToggleSelector references 'e' but it's never passed as an argument:
Uncaught ReferenceError: e is not defined 

Changing it to:
$(settings.autoSlideToggleSelector).unbind(clickEvent).bind(clickEvent, function(e) {...});
fixes this.

**Comment by marcwhitbread** [comment]
Thanks for finding that. Should be fixed in v1.2.14.
