### ISSUE TITLE
Wrong args in the callback

### ISSUE THREAD

**Issue by pasine** [iosscripts/iosslider#263]
I have found that currentSlideNumber, targetSlideNumber and slideChanged are wrong.
If you try to add a callback to the default example like this:

```
        $(document).ready(function() {

            $('.iosSlider').iosSlider({
                desktopClickDrag: true,
                onSlideComplete: checkChange
            });

        });

        function checkChange(args){
            console.log('changed');
            console.log(args.slideChanged);
            console.log(args.targetSlideNumber);
            console.log(args.currentSlideNumber);
        }
```

you see that targetSlideNumber is undefined, and slideChanged after the first slide is always  true even when the slide is not changed.

**Comment by marcwhitbread** [comment]
I am aware of this issue. See #219. I am working on a fix.

**Comment by marcwhitbread** [comment]
I have applied a fix for the change/complete callbacks to show correct data for arguments in v1.2.18.
