### ISSUE TITLE
slideChanged has the wrong value

### ISSUE THREAD

**Issue by pasine** [iosscripts/iosslider#264]
Steps to replicate:
- take example number 2;
- add a console.log after line n. 140 ( if(!args.slideChanged) return false; )
- try to click on the first slide without swipe: the console.log is not fired (and this is ok)
- swipe on the next slide
- click on it without swipe: the console.log is fired 
- log targetSlideNumber and currentSlideNumber and swipe the slide: they have both the same number on slidecomplete (and this is wrong).

Can I help somehow?

**Comment by pasine** [comment]
So the problem is related to $(node).parent().data('args') that has wrong values at line 956.

**Comment by marcwhitbread** [comment]
Thanks for the feedback. I'll take another look and get back to you. Sorry about that.

**Comment by marcwhitbread** [comment]
> log targetSlideNumber and currentSlideNumber and swipe the slide: they have both the same number on slidecomplete (and this is wrong).

You are actually wrong about this one. On slide change/compete current and target are the same while prevSlideNumber is different. The only time current and target will be different is when you release and the slide moves farther than the next slide. Does that make sense?

**Comment by pasine** [comment]
It makes sense, but I have a problem with the onSlideComplete event: I want to fire an event only if the slide has changed, while actually it is fired even if I just click on an item.
I've tried to check the prevSlideNumber, but the number is always (currentSlideNumber - 1) even if just click on a slide without change it.

**Comment by pasine** [comment]
Ok, if you slightly move the slide instead of just click on it, the slideChange is correctly set to 'false'. So I think is a problem related to the offset control.

**Comment by marcwhitbread** [comment]
I see what you are saying. For consistency, do you agree that onSlideComplete should not fire on just a click? In the current state, onSlideStart is not fired unless you move 1 pixel. I think the same should be true for onSlideComplete as well. This would resolve the incorrect data problem I believe.

**Comment by pasine** [comment]
I agree. The click should not fire onSlideComplete.

**Comment by marcwhitbread** [comment]
Updated with fix. onSlideComplete should not fire when no drag is started. Let me know if that works for you as well.

**Comment by pasine** [comment]
Yes, this seems fixing the problem.
Thanks a lot!
