### ISSUE TITLE
iosSlider and display:none style

### ISSUE THREAD

**Issue by sarahr2810** [iosscripts/iosslider#265]
I am trying to implement the iosSlider to give me multiple sliding galleries on my website:
http://sarahrosephotography.co.uk/gallery.shtml

I am using the display:none style to hide the content to begin with until the title is clicked to reveal the additional sliders, and at the same time hide the others.

However the top slider shown when the page loads work as intended but when clicking to reveal any of the others, they appear small and thin. 

I am not sure whether the error lies in the way I have set up the divs or the way I have organised the sliders.

**Comment by marcwhitbread** [comment]
If you initialize a slide while it is contained within an element with height/width 0px (display: none;), the slider will not be able to be calibrated correctly. The workaround for this is to either initialize after the element is shown for the first time or to simply call the update public method to recalibrate the slider based on the new dimensions of it's element container.

**Comment by sarahr2810** [comment]
Thanks, I see what you mean, however I'm not sure I know how to implement that.

Although this only seems to happen when I style my isoSlider to 100% width and not if I put in say 1000px, which is what I have it currently set as.

**Comment by marcwhitbread** [comment]
It's pretty straightforward. Call $('.iosSlider').iosSlider('update'); after the slider becomes visible OR initialize after the slider becomes visible the first time: $('.iosSlider').iosSlider({ /\* your parameters */ });

**Comment by tazcarper** [comment]
I'm having a similar issue. In the demo file '7-centered-slides > 2-background-images'. If you put a media query in the CSS with a max-width, it will lock up the browser.

So for example, putting this in the CSS works fine if you are above 1024 or below 768. However, once that media query activates, the slider locks up the screen. 

@media only screen 
and (min-width : 768px) 
and (max-width : 1024px) {
  .containerOuter {display: none;}
}

Do we need to write a $(window).resize function to detect the size and then iosSlider('destroy') and/or iosSlider('update') depending on if we want it showing or not?

**Comment by marcwhitbread** [comment]
@tazcarper you shouldn't need to add any of your own events. Maybe it's a bug. Let me take a look at it.

**Comment by marcwhitbread** [comment]
The bug seems to be associated with the jQuery 1.4 library inclusion. I switched the jQuery library over to 1.8.2 just to check and the browser didn't hang up. I will keep digging but I might just drop support for 1.4... It's pretty old.

**Comment by tazcarper** [comment]
Thanks Marc.
