### ISSUE TITLE
Scrollbar seems broken

### ISSUE THREAD

**Issue by luetkemj** [iosscripts/iosslider#267]
I can't get the scroll bar functionality to work.

Trying these settings:
                $('.iosSlider').iosSlider({
                        scrollbarDrag: true,
                        scrollbarLocation: 'bottom',
                        scrollbarContainer: '.scrollbar',
                        scrollbarHeight: '20px',
                        scrollbarOpacity: 1.0,
                        scrollbarBackground: 'red',
                        scrollbarElasticPullResistance: '0.5'
                });

But it appears to break the slider as it will no longer move and the scrollbar I do get cannot be dragged.
The only demo you have that uses it (200 slides) appears broken as well as I don't get anything in the demo at all. Just white screen.

**Comment by luetkemj** [comment]
Tried again with the settings from the website:

$('.iosSlider').iosSlider({
snapToChildren: true,
                    scrollbar: true,
                    scrollbarHide: false,
                    desktopClickDrag: true,
                    scrollbarLocation: 'bottom',
                    scrollbarHeight: '6px',
                    scrollbarBackground: 'red',
                    scrollbarBorder: '1px solid #000',
                    scrollbarMargin: '0 30px 16px 30px',
                    scrollbarOpacity: '0.75'
});

Again no dice. Scrollbar is not draggable. Slider no longer functions.

**Comment by marcwhitbread** [comment]
The above parameters work when used with example 1 in the download package for me. See screenshot.

![screen shot 2013-05-16 at 12 06 21 pm](https://f.cloud.github.com/assets/1944274/514594/c0892d44-be5b-11e2-89e0-10e7717fe12d.png)

Are you using the latest version? Which browser? Any JavaScript errors being thrown?

**Comment by luetkemj** [comment]
Got it working, I needed to add scrollbarDrag: true

sorry to bug you.

**Comment by yuchant** [comment]
Indeed, without scrollbarDrag: true, scrollbar does not appear!
