### ISSUE TITLE
Prev/Next buttons only working once after Ajax remote content load

### ISSUE THREAD

**Issue by presuming-ed** [iosscripts/iosslider#269]
Hi, I'm new to Jquery so please excuse me if this is stupid.

I've got an iosSlider loading into a prepended div from an external source file using .load() in Jquery. Everything works fine the first time but once I close the div and reopen it the prev/next navigation buttons don't work.

From what I've read it's probably an event binding issue, but I don't know if that's in my code or in the iosSlider code. I've tried a lot of things in a bit of a trial/error fashion and would greatly appreciate any help.

Cheers, Ed. 

Code below:

Homepage script for loading div/styling bits:

```<script type="text/javascript">

```
    $(window).load(function() {

        // cache container
        var $container = $('#container');
        // initialize isotope
        $container.isotope({
          // options...
          filter:'',
          animationOptions: {
             duration: 300,
             easing: 'linear',
             queue: false },
          resizable: false, // disable normal resizing
          // set columnWidth to a percentage of container width
          columns: 5
         });

        // update columnWidth on window resize
        $(window).smartresize(function(){

            if ($(window).width() > 480) {
                $container.isotope({
                    // update columnWidth to a percentage of container width
                    columns: 2
                });
            }

            if ($(window).width() < 985 > 480) {
                $container.isotope({
                    // update columnWidth to a percentage of container width
                    columns: 3
                });
            }

            if ($(window).width() >= 985) {
                $container.isotope({
                    // update columnWidth to a percentage of container width
                    columns: 6
                });
            }
        });

        // filter items when filter link is clicked
    $('#nav a').click(function(){
            var selector = $(this).attr('data-filter');
                $container.isotope({ filter: selector });
          });       
```

});

``````
        $(document).on("click","a.dynamicLoad", function() {

            $('body').prepend( ('<div class="projectcontainer"></div>') );

            $('.caption').fadeOut(400);

            $( '.projectcontainer' ).load( $( this ).attr( 'data' )).animate({'opacity': '1'}, 400);
        });

    </script>```
``````

And here's the remote div script:

``````
``` <script>
 $('.iosSlider').iosSlider({
                    snapToChildren: true,
                    desktopClickDrag: true,
                    keyboardControls: true,
                    navNextSelector: $('.nextContainer'),
                    navPrevSelector: $('.prevContainer'),
                    infiniteSlider: true,
        });

            $( document ).on("click","a.close", function( ) {

                    $('.caption').show();
                    $('.projectcontainer').fadeOut('fast', function(){ this.remove(); });
                    $('#floater').fadeOut('fast', function(){ this.remove(); });

        });




            function onResize() { 

                //get the height of the parent  
                var parent_height = $('.projectcontainer').height();  

                //get the height of the image  
                var image_height = $('.slide').height();  

                //calculate how far from top the image should be  
                var top_margin = (parent_height - image_height)/2;  

                //get the width of the parent  
                var parent_width = $('.slide').width();  

                //get the width of the image  
                var image_width = $('img').width();  

                var prevnext = (parent_height)/2;  

                //calculate how far from left the image should be  
                var left_margin = (parent_width - image_width)/2;  

                //and change the margin-top css attribute of the image  
                $('.slide').css( 'margin-top' , top_margin);
                $('.center').css( 'margin-right' , left_margin); 
                $('.center').css('margin-left' , left_margin);
                $('.prevContainer').css('top', prevnext );
                $('.nextContainer').css('top', prevnext );
                $('.close').css('position:fixed;top:5px;right:5px;z-index:50;');

                }           

        $(window).smartresize(onResize);
        $('img').load(onResize);
``````

</script>```

**Comment by marcwhitbread** [comment]
Are all the old elements being removed from the dom before being reloaded?

**Comment by marcwhitbread** [comment]
You can also use the goToNextSlide or goToPrevSlide public methods in stead using custom buttons. That way if the script is having issue binding a second time due to element duplication, this will get around that. Usage like so:

``` js
$('.iosSlider').iosSlider('goToNextSlide');
$('.iosSlider').iosSlider('goToPrevSlide');
```

Simply bind an event with the above functions included to your own buttons after reloading.

**Comment by presuming-ed** [comment]
Thanks for your speedy reply. 

The div that the slider's loaded into is removed in Jquery using .remove() so it's taken out of the DOM and should automatically unbind all events at the same time. 

I've used your public methods to specify the nav buttons like this (and removed the specifiers from the inital iosSlide list):

```
$( document ).on("click",".nextContainer", function( ) {

                    $('.iosSlider').iosSlider('goToNextSlide');

        });
```

And it's sort of working in that the buttons work on second load too now, but the slider goes a bit haywire and gets unpredictable – sometimes skipping slides and sometimes scrolling halfway through a slide.

**Comment by marcwhitbread** [comment]
The skipping of slides and jumping to incorrect slide locations tells me the internal variables are being screwed up somehow on reload. I will need to see your implementation to get a better idea of what is going on.

**Comment by presuming-ed** [comment]
(edit: removed link)

The top left link after loading (EPC 2012) is the only one working so far, on first load everything's fine, subsequent loads go wrong. Thanks for your help.

**Comment by marcwhitbread** [comment]
Remove the nextSlideSelector/prevSlideSelector from the initialization. You can bind the public methods manually as I mentioned above OR setting the selectors in the initialization but not both. So remove the nextSlideSelector/prevSlideSelector from the initialization.

Also, you have a JS error being thrown when closing the slider overlay. That might be causing some issues.

**Comment by presuming-ed** [comment]
Have fixed those issues and that seems to have sorted it, thanks very much!
