### ISSUE TITLE
Bug with Navigation Selector (pagination)

### ISSUE THREAD

**Issue by peduarte** [iosscripts/iosslider#27]
Let's say I have 5 slides and a pagination (similar to the demo you have on the demo site).

On a touchscreen device, if I go to the 3rd slide and swipe at the right edge of the viewport, it will unselect the 3rd active box and add the active class to the first.

Same thing happens if I swipe at the left edge, but it will activate the last navigator box.

Please let me know if that makes sense?

Thanks a lot.

**Comment by iosscripts** [comment]
Ah, that's odd. I'll take care of it :).

**Comment by peduarte** [comment]
Yeah, weird issue!

**Comment by iosscripts** [comment]
Fixed in 0.9.4.5

**Comment by peduarte** [comment]
Nice one dude, thanks a lot.
