### ISSUE TITLE
Fails in iOS Simulator

### ISSUE THREAD

**Issue by toddprouty** [iosscripts/iosslider#270]
When I view the demos in the iOS Simulator (Xcode), they break rather badly, showing up as a vertically scrolling stack of images. This may be an issue with the simulator itself, but I don't remember seeing it render pages differently than actual iOS devices running the same version of the operating system. Here's what I'm seeing using [BrowserStack](http://www.browserstack.com/) with the iOS 6 simulator — this is the "1-Default" demo:

![ios_simulator_ios6](https://f.cloud.github.com/assets/232426/526207/4e52aff2-c11c-11e2-9c42-6320b415647e.jpg)

It looks much the same on my local version of the simulator (iOS 4.3 — I'm on Snow Leopard), and all the other demos are similarly broken. Is this a known issue?

**Comment by marcwhitbread** [comment]
I was unaware of this issue but it is a possibility I suppose...

With that said, I haven't had any other reports of this so it might be something on your end. I only test Safari/Chrome on the real iOS devices themselves, and the demos are working currently without any problems.

**Comment by tomatic** [comment]
I'm using iOS Simulator 6.0 on Mountain Lion and while there are some layout glitches (linen background pattern in 16-Site-Demo isn't the correct height; see attached screenshot), it generally works. I can swipe through the gallery and the snapping also works.
![screen shot 2013-05-22 at 19 38 47](https://f.cloud.github.com/assets/367058/550019/8360f80c-c306-11e2-9be1-768e42138a3f.png)

**Comment by marcwhitbread** [comment]
@tomatic fixed the site demo in v1.2.22. Thanks for the submission.
