### ISSUE TITLE
Detect user interaction

### ISSUE THREAD

**Issue by pasine** [iosscripts/iosslider#272]
Hi, I need to fire a callback after a user has manually changed a slide.
I cannot use slideChange/slideComplete, since I am using the autoSlide feature and I don't want the callback to be fired if the change is automatic.
I can bind an event on navigation click: can I do something similar for the drag gesture?

**Comment by marcwhitbread** [comment]
Distinguishing between auto and manual wont be distinguishable so you will have to add 2 custom events with a flag. I would approach it like so: 

``` js
var manualFlag = false;

$('.iosSlider').bind('mousedown', function() {
    manualFlag = true;
});

$('.iosSlider').iosSlider({
    onSlideChange: slideChange
})

function slideChange(args) {
    if(manualFlag) {
        /* do stuff */
    }

    manualFlag = false;
}
```

I haven't tested the above code but it's enough to get you started.

**Comment by pasine** [comment]
Thanks! This seems doing exactly what I was looking for!
