### ISSUE TITLE
On Mousehover

### ISSUE THREAD

**Issue by santosh5** [iosscripts/iosslider#273]
Hi
I want that slider should be auto slide  when I mouse hover on slider. Can you tell to me how to solve this issues.

Thank you

**Comment by marcwhitbread** [comment]
Are you saying you would like to not disable the slider on hover? This functionality is not built in unfortunately but you can edit the source manually to achieve this. Simply remove the function starting on line 1628.

``` js
$(stageNode).bind('mouseenter.iosSliderEvent', function() {
    helpers.autoSlidePause(sliderNumber);
});
```

**Comment by marcwhitbread** [comment]
See issue #277
