### ISSUE TITLE
multiple instance of iossilder on one page

### ISSUE THREAD

**Issue by muzammal** [iosscripts/iosslider#274]
i have implement iosslider in my app on first page the slider is doing well but on the next page the slider is not working properly the name of slider is same for both pages and container name is also same means that the setting for these two slider is same..please reply fast..

**Comment by ericbeekman** [comment]
You should set the sliders to unique ID's for the elements. Otherwise you'll get some unexpected behaviour.

Like this: 

``` HTML
<div id="slider1"></div> 
<div id="slider2"></div>
```

Hope it helps!

**Comment by marcwhitbread** [comment]
@muzammal It's likely a scope issue but your explanation of "not working" is not really helpful. If you are not experienced enough to understand immediately why this is happening or where to begin troubleshooting I would recommend doing what @ericbeekman solution as the most basic workaround. 

Doing something like this would be a similar JS: 

``` JS
$('.iosSlider').each(function() {

    $(this).iosSlider({
        /* parameters */
    });

});
```

That way you could individually initialize parameters and handle scope more effectively.

**Comment by sebvandijk** [comment]
Would it be possible to get the id of the slider div back from onSlideComplete?  (when using multiple sliders like the example above?

**Comment by marcwhitbread** [comment]
@sebvandijk yes in the arguments supplied to the callback you can.

``` js
var callback  = function(args) {
    //use args.sliderContainerObject
}
```

Take a look at the documentation on iosscripts.com/iosslider or dump args for more information about the callback argument object.

**Comment by sebvandijk** [comment]
Thanks, 

yes I already got this working:
current_slider = args.sliderContainerObject.context.attributes[0].value;

So I get the id of the current slider. Problem is this works like a charm, except on a tablet (ipad) where i just need that because the use the drag function.
