### ISSUE TITLE
-webkit-backface-visibility slow down chrome

### ISSUE THREAD

**Issue by denisborovikov** [iosscripts/iosslider#287]
I have a slider with ~100 of 1200x800 images. Chrome works very very slow on this page (but FF and IE are ok). 

If i removed 'webkitBackfaceVisibility': 'hidden', in the source code, chrome works as always.

May be it can helps http://dontwakemeup.com/webkit-backface-visibility-and-browser-crashing/, there are some links below.

**Comment by marcwhitbread** [comment]
I believe I have a fix for this issue in v1.3.36. Ref issue #327. Merged to master.
