### ISSUE TITLE
desktopClickDrag:true makes text input fields unusable on Mac browsers

### ISSUE THREAD

**Issue by tomsoderlund** [iosscripts/iosslider#29]
When the setting desktopClickDrag is true, text input fields are unusable on Mac browsers (tested on Chrome, Safari). The fields work fine on iOS simulator and device. With desktopClickDrag:false, the fields work fine on Mac browsers too.

**Comment by iosscripts** [comment]
Duplicate of issue #10. I am still working out why this is happening. I can fix it by removing the code that changes the cursor hand to the hand-grabbing cursor onmousedown. Not sure why that fixes it though...

**Comment by iosscripts** [comment]
While overridden with the new parameter 'unselectableSelector', these fields can become usable again. Working test case contained within _demos/_benchmarks/_general/. Use version 1.0.27 or later.
