### ISSUE TITLE
IE10 photos not loading

### ISSUE THREAD

**Issue by myheadisfixed** [iosscripts/iosslider#290]
Hi.

I know it's a lot to ask, but could you have a look here: http://www.valentinwagner.at/portfolio/corinna-dreyer-2/

View this page with IE10, the images on the right don't seem to load at all... i bought that wordpress theme "Heat" from themeforest and it comes with your iosSlider included... so i thought you could maybe help me out, the developer of the wordpress theme says its a IE10 bug... 

Thx.

**Comment by marcwhitbread** [comment]
First thing I would do is swap out your current version with the latest v1.3.5. 

Also, the demo's in the download pack work in IE10 so I wouldn't say it's a browser bug. More likely an implementation issue. I would go back to the theme dev and ask for a code fix if the demos are working.
