### ISSUE TITLE
multiple sliders on page slide selector

### ISSUE THREAD

**Issue by psjak** [iosscripts/iosslider#298]
Hi, 

I'm having an issue with implementing multiple sliders on the same page. Each slider is sliding perfectly but I can't figure out how to get each slider to have it's own pagination dots that work independently. At the moment they seem to all be controlling the last slider on the page and only the fist slider's pagination is changing to '.selected'. Any help would be greatly appreciated as I am trying to implement this for a portfolio for university and I'm not very good with jquery. I would like to buy a licence but I need to fist make sure I can get this to work.

This is the code I'm using currently...

```
$(window).load(function () {

$('.slider').each(function() {

$(this).iosSlider({
    snapToChildren: true,
    desktopClickDrag: true,
    snapSlideCenter: true,
    infiniteSlider: true,
    navSlideSelector: '.dots span',
    onSlideChange: slideChange,
    responsiveSlideContainer: true,
});

});

function slideChange(args) {
$('.dots span').removeClass('selected');
$('.dots span:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');
}
});
```

and here is a link to the site I'm working on http://jakdesign.webflow.com/

**Comment by marcwhitbread** [comment]
You're close! But you need to keep an eye on the scope of your selectors. RIght now '.dots span' will pick up all matched on the page. You need to target elements relative to the slider. Lets say for example your 'dots' exist within the 'slider' element.

``` js
$(this).iosSlider({
    /* other parameters */
    navSlideSelector: $(this).find('.dots span'),
});
```

And in the callback:

``` js
function slideChange(args) {

    /* assuming that the dots are decendents of the slider object */
    $(args.sliderObject).find('.dots span').removeClass('selected');
    $(args.sliderObject).find('.dots span:eq(' + (args.currentSlideNumber - 1) + ')').addClass('selected');

});
```

Thanks!
