### ISSUE TITLE
Slider not properly instantiated if initially hidden

### ISSUE THREAD

**Issue by gjunkie** [iosscripts/iosslider#300]
I am instantiating 2 sliders. The first one immediately visible, the second is hidden with

display: none;

I have a set of tabs that shows/hides each slider. The first slider gets properly instantiated with expected widths. The second is collapsed and not visible. If I remove the display none when first initialized the widths are set on both sliders as expected.

Since widths are required in the css, it should be possible to get the css values for widths when calculating, even for hidden elements.

**Comment by marcwhitbread** [comment]
As you know based on your comment, height/width of elements are calculated to be 0 by JavaScript when looking at display: none; elements. While your recommendation is spot on, it won't work for the wide variety of responsive implementations allowed by this script.

The recommended workaround for this is to manually call `$('.iosSlider').iosSlider('update');` to manually recalibrate the slider once you have removed the display: none; attribute.

**Comment by gjunkie** [comment]
This does work, but it may have exposed a bug. When calling 'update' it converts the set width I have of 48% to 48px.

**Comment by marcwhitbread** [comment]
@gjunkie possibly. Do you have an example I can look at?

**Comment by gjunkie** [comment]
I don't have an example as we haven't pushed to prod yet, but this is how I have it set up.

``` html
<div class="Slider">
  <nav class="Tabs">
    <a href="#Slider1" class="tab">Slider1 </a>
    <a href="#Slider2" class="tab">Slider2 </a>
  </nav>
  <div id="Slider1" class="iosSlider" data-element="iosSlider">
    <ul class="slider">
      <li class="slide"></li>
      <li class="slide"></li>
    </ul>
  </div>
  <div id="Slider2" class="iosSlider hidden" data-element="iosSlider">
    <ul class="slider">
      <li class="slide"></li>
      <li class="slide"></li>
    </ul>
  </div>
</div>
```

``` css
.hidden {
  display: none!important;
}
.iosSlider .slider .slide {
  width: 48%;
  margin-right: 2%;
}
```

``` javascript
myElem = $('.Slider');
myElem.find('[data-element="iosSlider"]').iosSlider('update');
```

This JS is a bit overly simplified as I'm actually calling 'update' in my Tabs class when tabs are switched. But this is essentially what it's doing. Side note, I have also set the width of the slides in the css wrapped in media queries to account for iPad and iPhone in portrait and landscape. 

Also, if I remove the hidden class to expose both sliders to start, they both get set up properly. But once I begin to call 'update' the second slider has its slides set back to width 48px.

**Comment by gjunkie** [comment]
To fix the issue, or patch it I should say, I have set a pixel width for every screen size with !important. This seems to be working well. Still would like to know why its converting my percent widths to pixels.
