### ISSUE TITLE
Centring variable width slides

### ISSUE THREAD

**Issue by mikeebee** [iosscripts/iosslider#301]
Hi! 

I have an infinite carousel where each slide needs to be variable width. I have it working as per the demo but I need the active slide to be centred. Is this possible?

Many thanks!

**Comment by marcwhitbread** [comment]
Sorry, that's one of the few limitations of the script unfortunately. The slide centering only works with equal slide widths. I have logged the feature as something I'm considering adding.

**Comment by LinzardMac** [comment]
I have to +1 for this!!!!
