### ISSUE TITLE
Feature Request Dynamic bullets.

### ISSUE THREAD

**Issue by DeepSilver** [iosscripts/iosslider#304]
Would be great if the script will generate bullets dynamically when required.
This will be especially helpful on cms where sliders created dynamically or via shortcodes (like wordpress)
could be...
$(args.sliderContainerObject).find('.iosSliderBullets').append
<SOME BULLETS ELEMENTS>...

**Comment by marcwhitbread** [comment]
@DeepSilver Good idea. First off, I don't like adding too many "hand-holding" options into my scripts. This tends to get in the way of customization/flexibility of implementations. Second, I am targeting intermediate level and up front end devs with this plugin so they don't have much use for these restrictions anyway. Besides, you would have to equip your implementation to handle varying numbers of bullets anyway in your HTML/CSS regardless.

It's not much of a stretch to add a line of code in the sliderLoaded callback. Like so:

``` JS
onSliderLoaded: function(args) {

    var number_of_slides = args.data.numberOfSlides;

    //do stuff using the 'number_of_slides'

}
```

Hope that helps :) :+1:

**Comment by DeepSilver** [comment]
if that's the case, then I would recommend moving style to css as the script add this style to the bullets
style="cursor: pointer;"
this should controlled via css hover and active
$(settings.navSlideSelector).each(function(j) {
$(this).css({
cursor: 'pointer'
});
