### ISSUE TITLE
iosSlider locks vertical scrolling android (4.3)

### ISSUE THREAD

**Issue by Maarten-1984** [iosscripts/iosslider#306]
Hi!

I'm testing iosSlider locally on my mobile; samsung galaxy s4 with android 4.3.
I have two horizontal sliders on my webpage. The sliders on it's own work perfect, but when I start to scroll (swipe) vertically trough my website, at some point the vertical scroll gets locked :S I hardly can't scroll to my page anymore, a refresh is the only option... I was trying something with verticalSlideLockThreshold, but no luck.

This are my options:

``` js
$element.iosSlider({
    desktopClickDrag: false,
    scrollbarDrag: true,
    scrollbar: true,
    snapToChildren: true,
    scrollbarHide: false,
    snapVelocityThreshold: 1,
    verticalSlideLockThreshold: 0,
    scrollbarLocation: 'bottom',
    navNextSelector: $next,
    navPrevSelector: $prev,
    onSlideComplete: slideComplete,
    autoSlide: false,
    onSliderResize: sliderResize,
}); 
```

Any idea how to resolve this vertical scroll problem?

Tnx in advance

**Comment by marcwhitbread** [comment]
The only way the vertical scrolling should lock is if horizontal scrolling has begun. That is expected behavior.

With that said, have you tried increasing the `horizontalSlideLockThreshold`? Does the issue only occur after the slider has been used?

**Comment by Quirksmode** [comment]
Hi, 

I am having exactly the same issue, on Android when I try to scroll up and down it locks. The issue only occurs after the slider has been used and increasing horizontalSlideLockThreshold just makes it worse. It works perfectly on iOS.

Getting desperate for a solution as it's the only thing left to fix before I can go live, any help is massively appreciated.

Thanks in advance.

Dave

**Comment by marcwhitbread** [comment]
Some Android browsers are having serious issues with the touchmove event. In some cases, the touchmove event is only fired once (in stead of every move of the finger on the device). It's causing issues in other functions in the plugin as a result. I am working on a fix currently.

**Comment by Quirksmode** [comment]
Great news about the fix and thanks for getting back to me so quickly. Any idea of an eta for the fix?

**Comment by marcwhitbread** [comment]
@Quirksmode strangely enough, I'm working on it today so hopefully not too long. But testing JS on Android can be a bit of a pain.

**Comment by Quirksmode** [comment]
Yeah, it can be a right bugger, this tool is quite useful for device testing https://github.com/shakyShane/browser-sync

Let me know if you manage to crack it :-)

**Comment by JBSN** [comment]
I have to say, we just purchased this script for commercial use and he's been awesome in responding to the issues we're having. 

Thanks Marc!

JB

**Comment by marcwhitbread** [comment]
I have applied a fix in v1.3.30.

**Comment by Maarten-1984** [comment]
I havent been active with that project in a while, but I got email-notifications for this topic.
Tested the fix in v1.3.30 quickly in my project and it seems to work now. At least no majure scroll locks anymore! 

Tnx a lot for the fix Marc

**Comment by puneetbahuguna** [comment]
Hi marcwhitbread.  I am getting an issue with this iosslider in Iphone3. when i am using combined horizontal and vertical scrolling simultaneously then on quick vertical scrolling through the list its horizontally moving to the next slide. Can you please suggest on this.

**Comment by marcwhitbread** [comment]
@puneetbahuguna your issue is unrelated to this one.
