### ISSUE TITLE
Problem auto width and height for multiple row

### ISSUE THREAD

**Issue by softgen** [iosscripts/iosslider#307]
I am creating a image gallery for multiple row. For every row height different. So when the slide is loading I am setting height. After loading complete the slide is working and all image are showing. But when I am reducing the browser automatic all images are hiding. So please let me how to solve the problem?

See the url : http://api.junctiontv.com/jtv/appshtml/

**Comment by marcwhitbread** [comment]
@softgen when the slider is resized, the height component of the slider is recalibrate. This is for compatibility with responsive implementations. You can fix this by either setting responsiveSlideContainer and responsiveSlides to false or updating the height manually in the onSliderResize callback.
