### ISSUE TITLE
Option - desktopClickDrag has no effect.

### ISSUE THREAD

**Issue by DeepSilver** [iosscripts/iosslider#308]
on the demo pages (v1.3.24), setting option desktopClickDrag:false will not disable desktop drag.
not sure if its a bug.

**Comment by marcwhitbread** [comment]
@DeepSilver unable to reproduce in example 1. Which browser are you testing?

**Comment by DeepSilver** [comment]
Sorry...
Firefox v26.0 (WIN)

**Comment by marcwhitbread** [comment]
Interesting... are you on a screen that has touch capabilities as well? That's the only thing I can think of that could be interfering. It's disabling correctly on my end. 

This is pretty much the first feature to be added and would be a very high visibility problem if broken. I'm not hearing about this issue from any other users so I'm not sure what is specifically going wrong in your case.

**Comment by DeepSilver** [comment]
Firefox v26.0 WIN XP SP3 all Firefox addons disabled, no touch capabilities still the same.
I ended up doing a clean install (reinstall did not fix it) of  Firefox, problem solved.
Don't know what was the cause but it was nothing to do with iosslider script.
