### ISSUE TITLE
Create dinamic bullets

### ISSUE THREAD

**Issue by elchiconube** [iosscripts/iosslider#309]
Hi, i need some help, i want to print a dynamic number of bullets depending of the number of slides. Can be possible? Thanks

**Comment by marcwhitbread** [comment]
@elchiconube take a look at the solution I provided in issue #304. In the onSliderLoaded callback you can use the numberOfSlides variable to create a specific number of dynamic bullets within a defined container. You could approach it like so:

``` js
onSliderLoaded: function(args) {

    var number_of_slides = args.data.numberOfSlides;

    for(var i = 0; i < number_of_slides; i++) {
        $('.bullet-container').append("<div class = 'bullet' onclick = \"$('.iosSlider').iosSlider('goToSlide', " + i + ");\"></div>");
    }

}
```

The CSS for the bullets and container would be up to you.
