### ISSUE TITLE
How to add a slide counter

### ISSUE THREAD

**Issue by whoispaul** [iosscripts/iosslider#31]
Hi,

I'm new to Javascript and Jquery, so please excuse me for what might be a basic question. I'm trying to add a counter to the slider. I've managed to display the total number of slides using this:

<script type="text/javascript">
function displaycounter(){
    var totalcount=document.getElementsByClassName("item").length;
    document.getElementById('counter').innerHTML = "of " + totalcount;
    alert(slideNumber);
    }
onload=displaycounter;
</script>

Not sure if that was the right way to go but now I'm trying to determine the current slide that I'm on. Could you point me in the right direction? Any help would be great.

Thanks.

**Comment by iosscripts** [comment]
If you attach an event to the onSlideChange option, you can access the current slide number.

ex. 
$('.iosSlider').iosSlider({
     onSlideChange: changeSlideFunction
});

function changeSlideFunction(args) {
     var slideNumber = args.currentSlideNumber);
}

**Comment by whoispaul** [comment]
Thanks Marc for the quick response! It works!

I'm trying to a portfolio site with multiple sliders on one page. Is there a way to contain the counter within each individual slider? To put it another way, how can I get the counter to only include slides within a specific project and not count every slide from every project?

Thank you so much for your time.

**Comment by iosscripts** [comment]
the onSlideChange function used in the example above only reports the current slide number of the current iosSlider. You will need to store each slideNumber differently for each slider. Something like this maybe:

function changeSlideFunction(args) {
var slideNumber = args.currentSlideNumber);

$(args.sliderObject).parent().find('.slideCounter').html('slide: ' + slideNumber);
}

<pre><code>&lt;div class = 'iosSlider'&gt;...&lt;/div&gt;

&lt;div class = 'slideCounter'&gt;&lt;/div&gt;
</code></pre>

**Comment by whoispaul** [comment]
Hi Marc,

Here's my code:

<pre><code>
<script type="text/javascript">
    $(document).ready(function() {      
        $('.iosSlider').iosSlider({
            scrollbar: false,
            snapToChildren: true,
            desktopClickDrag: true,
            scrollbarMargin: '5px 40px 0 40px',
            scrollbarHeight: '2px',
            scrollbarBorderRadius: 0,
            navPrevSelector: $('.prevButton'),
            navNextSelector: $('.nextButton'),
            infiniteSlider: false,
            onSlideChange: changeSlideFunction
            });
        function changeSlideFunction(args) {
            var slideNumber = (args.currentSlideNumber);
            $(args.sliderObject).parent().find('.slideCounter').html('slide: ' + slideNumber);
            }   
    });
</script>
</code></pre>


I also placed the "slideCounter" div after the "iosSlider" div. I'm new to Javascript but I'm assuming the code you gave me is telling "iosSlider" to go one level up, find the "slideCounter" div and insert "slide: #" into the HTML. For some reason, nothing shows up. Am I doing something wrong?

Sorry for the formatting. The code shows up formatted when I'm writing it but not when I submit it.

**Comment by iosscripts** [comment]
parent() = look up one level in the DOM. So in this case, the element that contains the iosSlider div. As long as slideCounter is contained within that, it should work. If you have a working demo that I could look at, I could troubleshoot it more easily.

**Comment by whoispaul** [comment]
Hi Marc,

Here's a working demo:
http://whoispaul.com/counter/

I managed to get the counter to appear, however it slides with the first slide. Also, an additional blank slide appears at the end for some unknown reason. Any suggestions on how to prevent the counter from moving?

**Comment by iosscripts** [comment]
Move the "slideCounter" outside the "slider" div. The extra blank slide is because it is treating "slideCounter" as a slide within the "slider" div.

**Comment by whoispaul** [comment]
Marc,

Thank you for the quick response. It's working now! I feel like an idiot but I could've sworn I tried that already. Anyways, thanks again for your help!
