### ISSUE TITLE
Option mobileTapDrag

### ISSUE THREAD

**Issue by dominic-ng** [iosscripts/iosslider#311]
I'm using iosslider as product image gallery. For some reason, I want to have mobileTapDrag:false option as desktopClickDrag:false option in order to disable slide on mobile. This is because when use iosslider with cloudzoom, user can not drag the zoom area for zooming. Test without iosslider, drag for zoom still work well.

**Comment by marcwhitbread** [comment]
I won't be adding this to the plugin as it is a mobile/touch first and foremost product. But following slider initialization, you could unbind the touch events on the slider in your own JS though:

``` js
$('.iosSlider').unbind('touchstart.iosSliderEvent touchmove.iosSliderEvent');
```

That would effectively remove touch capabilities.
