### ISSUE TITLE
Initial Loading Slow

### ISSUE THREAD

**Issue by jaeeunl** [iosscripts/iosslider#313]
Hi,

I'm using iOSSlider that is included in Wodpress Kallyas theme. It looks good once it's loaded, but the loading time is very slow, and you can see the slider resizing the image, which is ugly. This is the page;

http://sequoiabeauty.com/development/homapage-all/

Please let me know if/how I can fix this.

Thanks a lot.

Jaeeun

**Comment by marcwhitbread** [comment]
The issue could be attributed to internet connection speed, old hardware, or an outdated browser. But iosslider performs decently in the supported environments.

It's possible that the developer of the theme has set the slider to wait until window.load() in stead of document.ready() to initialize. Hard to say. Contact the theme developer and see if anything can be done with the load timing.

I would have a support agreement with the theme developer, so he can contact me with any implementation issues he is having via the iosslider support page.
