### ISSUE TITLE
safari can't handle

### ISSUE THREAD

**Issue by ibrahimmumcu** [iosscripts/iosslider#317]
I'm trying this slider on magento e-commerce system. But it's too slow on safari. in Chrome perfectly smoothy.

Example: http://aloom.sekizbit.net/

Can anyone help me?

**Comment by marcwhitbread** [comment]
@ibrahimmumcu it works in desktop Safari quite well on my end. I'm not seeing any difference (performance wise) between the two browsers on my end. Anything different about your Safari? Are you running an up to date version?

**Comment by ibrahimmumcu** [comment]
I'm using 5.1.7 version on Windows. I know, windows dont use Safari but this is just test. But you said, it works very well on Safari, mac running. It's ok then.
