### ISSUE TITLE
slider messy from landscape to portrait

### ISSUE THREAD

**Issue by cloprime105** [iosscripts/iosslider#318]
Hi,
The iosslider is mess when i change the tablet state from landscape to portrait.

I hope you check it asap.

**Comment by marcwhitbread** [comment]
More than likely caused by CSS. When you rotate your device, you have to produce CSS for those responsive states as well.

**Comment by cloprime105** [comment]
I don't think it's the css issue.

I tried the demo slider on your website and local file that I download from
your site, but it's messy, too.

Also it doesn't work well most of the sites.

I think you can check it.

Regards
