### ISSUE TITLE
How to add multiple sliders on one page?

### ISSUE THREAD

**Issue by whoispaul** [iosscripts/iosslider#32]
Hi,

I was wondering how to go about adding multiple sliders on one page. I created alternate versions of iosSlider div but that didn't seem to work.

Do you have any suggestions?

Thanks so much.

**Comment by iosscripts** [comment]
Did you do something like this?

<div class = 'iosSlider-1'>...</div>


<div class = 'iosSlider-2'>...</div>


$('iosSlider-1').iosSlider();
$('iosSlider-2').iosSlider();

**Comment by whoispaul** [comment]
Hi Marc,

I tried this:

<pre><code>
<script type="text/javascript">
    $(document).ready(function() {      
        $('.iosSlider-1').iosSlider({
            scrollbar: false,
            snapToChildren: true,
            desktopClickDrag: true,
            scrollbarMargin: '5px 40px 0 40px',
            scrollbarHeight: '2px',
            scrollbarBorderRadius: 0,
            navPrevSelector: $('.prevButton'),
            navNextSelector: $('.nextButton'),
            infiniteSlider: false,
            onSlideChange: changeSlideFunction
            });
            
        $('.iosSlider-2').iosSlider({
            scrollbar: false,
            snapToChildren: true,
            desktopClickDrag: true,
            scrollbarMargin: '5px 40px 0 40px',
            scrollbarHeight: '2px',
            scrollbarBorderRadius: 0,
            navPrevSelector: $('.prevButton'),
            navNextSelector: $('.nextButton'),
            infiniteSlider: false,
            onSlideChange: changeSlideFunction
            });
            
        function changeSlideFunction(args) {
            var currentslide = (args.currentSlideNumber) + 1;
            document.getElementById('counter').innerHTML = (currentslide) + " of " + totalcount;
            }
                        
        var totalcount=($('.slider > div').length);
        document.getElementById('counter').innerHTML = "1 of " + totalcount;    
    });
</script>
</code></pre>

In addition to that, I duplicated the "iosSlider" div and renamed them "iosSlider-1" and "iosSlider-2". The next and previous buttons disappeared and the CSS styles no longer work. What should I have done differently?

Sorry about the formatting above. It formats when I edit it, but all that goes away when i post the comment.

**Comment by iosscripts** [comment]
If you wrap your code in the comment in &lt;pre&gt;&lt;code&gt;...&lt;/code&gt;&lt;/pre&gt; it will look like above. 

The CSS issues you are experiencing is extremely fundamental. I cant help you troubleshoot effectively without at least a basic knowledge of HTML/CSS/JS. Sorry.

**Comment by whoispaul** [comment]
Thanks for the quick response Marc. I think I see where I went wrong. Thanks for all your help!
