### ISSUE TITLE
iosSlider: Prevent from dragging last slide to the center

### ISSUE THREAD

**Issue by vraguraman** [iosscripts/iosslider#320]
Hi All,
I am using iosSlider plugin. I want to restrict the last slide to the center by using mouse or dragging.  How to implement this ? 

Also, I want to retain the slider positions after the postback. 
iosSlider reloads again if any postback happens, I need to maintain all slides positions before the postback happens. How to do that ?

Thanks,

V. Raguraman.

**Comment by marcwhitbread** [comment]
> I want to restrict the last slide to the center by using mouse or dragging. How to implement this ? 

Center the last slide in the slider? You would use SnapSlideCenter: true for this.

> iosSlider reloads again if any postback happens, I need to maintain all slides positions before the postback happens. How to do that ?

This is not built into the slider. You can store the current slide number in the hash onSlideChange and startAtSlide with this hash on page load.

**Comment by vraguraman** [comment]
Hi Marc Whitbread,

Thanks for your response.

For the 1 Question ,

Actually I want to Prevent / Restrict the last slide to move to the center
by using dragging or mouse wheel. How to do that ?
Even, if I try to drag the last slide to center, it should return back to
the last place automatically.
ie) The last slide should not move to the center by anyway.

For the 2 Question :

Yes, I am storing the current slide number  and I call the GotoSlide method
with the slide number. Now, the current slide is showing
as 2nd slide (Active slide). This is not good. It should retain the same
place before postback happens.

Can you understand the above problems ?  Please let me know.

Thanks,

V. Raguraman.

**Comment by marcwhitbread** [comment]
> Actually I want to Prevent / Restrict the last slide to move to the center
> by using dragging or mouse wheel. How to do that ?

So you want to remove the rubber banding at the end? Not possible unfortunately.

> Yes, I am storing the current slide number  and I call the GotoSlide method
> with the slide number. Now, the current slide is showing
> as 2nd slide (Active slide). This is not good. It should retain the same
> place before postback happens.

If you are looking to retain the precise offset of the slider through a page refresh, that wont be possible. Only the nearest slide offset can be used.
