### ISSUE TITLE
Images will only toggle after all images are loaded

### ISSUE THREAD

**Issue by weblinsolutions** [iosscripts/iosslider#321]
Hi,

I am only able to slide through images only when all images are loaded.
http://www.northwaterstar.com/portfolio/ankita-chatterjee-dushyant-singh-engagement/

Many users will not wait at all and may just close the page out of frustation. Please tell me how can I make the slider to allow toggle without waiting for all images to load.

Thank you.

**Comment by marcwhitbread** [comment]
> I am only able to slide through images only when all images are loaded.

Technically, no. You can move the slider before the images are loaded. I just tried it with my mouse and am able to. Mobile devices may have different requirements which are uncontrollable with JavaScript.

If you are using $(document).ready() to fire your initialization, only the DOM is waited for.

> Please tell me how can I make the slider to allow toggle without waiting for all images to load.

What will this accomplish? Users will just end up navigating through blank slides.

Keep in mind that you are also trying to load in 18MB worth of assets into the page, which is not typical or recommended. Even with a very good internet connection this will take a few seconds.

I recommend the following:
- reduce the size of the images. Your images do not need to be 400-500 KB in size.
- loading in the assets and using some sort of loading gif overlay. Once the images are loaded, $(window).load(); will be fired and you can hide the overlay.

**Comment by notor** [comment]
> Technically, no. You can move the slider before the images are loaded. I just tried it with my mouse and am able to. Mobile devices may have different requirements which are uncontrollable with JavaScript.

I just tried with my mouse and I could not move his slides until they were all fully loaded. I am on Win8.1 using Chrome 40.0.2214.93. So something is going on. On his website, and mine, until the final image is loaded it just. doesn't. work. Here is a video demonstrating.
[https://www.youtube.com/watch?v=dqts71o6Tok](https://www.youtube.com/watch?v=dqts71o6Tok)

> What will this accomplish? Users will just end up navigating through blank slides.

Blank slides that are loading is better than a frozen box.
