### ISSUE TITLE
GET http://xxx.com/undefined 404 (Not Found) error

### ISSUE THREAD

**Issue by ibrahimmumcu** [iosscripts/iosslider#324]
Actually it works very well but in console I got this error. Then I select slider item element I saw this: 

< div class="item" style="width: 1905px; float: left; background-image: url(xxx.com/undefined);">< img src="skin/frontend/meigeetheme/default/img/slider/3.jpg" ></div>

Like I said it's working very well but I want to fix this. Any help?

**Comment by marcwhitbread** [comment]
iosslider doesn't apply any background-image attributes to your slides so it isn't coming from this script. Is that what I am supposed to be looking at?

**Comment by ibrahimmumcu** [comment]
Yes, so you saying it happens with other scripts. Right? @marcwhitbread

**Comment by marcwhitbread** [comment]
I'm saying iosslider isn't applying the background-image so it has to be some other JS.
