### ISSUE TITLE
option to advance whole slider width rather that just slide width

### ISSUE THREAD

**Issue by owzim** [iosscripts/iosslider#326]
It'd be great if there was an option to make the drag snapping, `.iosSlider('prevSlide')` and `.iosSlider('nextSlide')` move the slider not just the amount of pixels of a single slide, but the whole slider width.

Use case:
If I have say 6 slides showing within the width of the slider I don't want to just move the slider the tiny width of one slide but the whole pack. 

Is this currently possible somehow?

**Comment by marcwhitbread** [comment]
This isn't currently possible but not too difficult to implement I don't think.

I am looking into adding `.iosSlider('nextPage');` and `.iosSlider('prevPage');` to support this behaviour.

**Comment by marcwhitbread** [comment]
Public methods now available. Will merge into master.
