### ISSUE TITLE
Dynamically passing value into goToSlide from the index value of an array

### ISSUE THREAD

**Issue by jamjia** [iosscripts/iosslider#329]
Hi there,

I want to create a bunch of shortcuts using a anchor tag but give it a class of "shortcut". I then want to loop through these with the jQuery each method and then binding each to a click event. So that on click, I will then trigger the goToSlide by passing the index value +1 to the slideNum. Here's my code, below. The problem is that I'm constantly getting a TypeError: undefined is not a function could someone help me work out where I'm going wrong???

```
    $('.shortcut').each(function() { 
        $(this).bind('click', function(){
            var slideNum = $(this).index()+1;
            $('.slideshow').iosSlide("goToSlide", slideNum);
            console.log(slideNum);
        });
    });
```

**Comment by marcwhitbread** [comment]
Missing an "r" in the plugin name "iosSlider".

**Comment by jamjia** [comment]
@marcwhitbread thank you!
