### ISSUE TITLE
Seek and DESTROY

### ISSUE THREAD

**Issue by YellowChristian** [iosscripts/iosslider#33]
Great work on the benchmark demos, really great. Would like to have the slider launch in DESTROY mode activated only by INIT and stopped by DESTROY again. Unsure how to make this happen…

Look forward to your relpy.

Best regards

**Comment by iosscripts** [comment]
If you want it destroyed initially, don't call $('.iosSlider').iosSlider() and it wont initialize. Just make sure that your CSS on the exterior iosSlider div has: 

position: relative; 
width: value (px/%);
height: value (px/%);
overflow: hidden;

**Comment by YellowChristian** [comment]
Noticing slide animation jitters when launched for the first time on an iPad. After you've cycled through the entire set once does it become fluid. Have I missed a piece of CSS?

**Comment by iosscripts** [comment]
A possible performance limitation right now. I am always optimizing the script though. Which iPad are you using?

**Comment by YellowChristian** [comment]
IPAD3

That's fine, it s not of huge concern. Optimise away!

Sent from my iPad

On 22 Jun 2012, at 19:51, "Marc Whitbread" reply@reply.github.com wrote:

> A possible performance limitation right now. I am always optimizing the script though. Which iPad are you using?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> ## https://github.com/iosscripts/iosSlider/issues/33#issuecomment-6515502
> 
> Future Publishing Limited (registered company number 2008885) is a wholly owned subsidiary of Future plc (registered company number 3757874), both of which are incorporated in England and Wales and share the same registered address at Beauford Court, 30 Monmouth Street, Bath BA1 2BW.

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to which they are addressed. If you have received this email in error please reply to this email and then delete it. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of Future.

The recipient should check this email and any attachments for the presence of viruses. Future accepts no liability for any damage caused by any virus transmitted by this email.

Future may regularly and randomly monitor outgoing and incoming emails and other telecommunications on its email and telecommunications systems. By replying to this email you give your consent to such monitoring.

---

Save resources: think before you print.
