### ISSUE TITLE
Ability to set animation speed by parameter in public navigation methods

### ISSUE THREAD

**Issue by marcwhitbread** [iosscripts/iosslider#332]
Add optional parameter to goToSlide, nextSlide, prevSlide, nextPage, prevPage which accepts an integer which represents the animation duration in milliseconds.

**Comment by sprohorov** [comment]
Hi, marcwhitbread!
Help me make links to each slide to work on the mobile version.
The TAP command does not transition the link.
Click the mouse working well.
Help me please
