### ISSUE TITLE
iOSSLider and responsive

### ISSUE THREAD

**Issue by mitrovics** [iosscripts/iosslider#335]
Hello,
i just discovered this graet slider. And i am planing to buy it probably some extended licence to server etc. But i have problem. Can i set responsive height and width of slide? because in examples i downloaded width is fixed 900px and height 300px. When i put 100% slider does not work?
Thanks!

**Comment by marcwhitbread** [comment]
@mitrovics Take a look at the responsive height examples in _demos/_examples/9-Full-Width-Responsive-Height 

You will need to leverage the padding-bottom % approach in your CSS. Let me know if you have any questions.
