### ISSUE TITLE
Javascript error when concat+minified by external minifiers

### ISSUE THREAD

**Issue by SGudbrandsson** [iosscripts/iosslider#336]
Hi.

I found a bug in the iosslider minified javascript code, jquery.iosslider.min.js.
The bug presents itself when the minified code is being concatenated and minified by external minifiers.

The bug appears twice in the minified version of the code:
"- -1_T" turns into "--1_T"

To fix this manually, I replaced the following code:
"- -1*T" -> "+T"

Cheers,
 Siggy

**Comment by marcwhitbread** [comment]
Where in the code does this issue occur?

**Comment by SGudbrandsson** [comment]
https://github.com/iosscripts/iosslider/blob/master/_src/jquery.iosslider.min.js

I suspect that this has to do with this code, "-1 -", found on the following lines in https://github.com/iosscripts/iosslider/blob/master/_src/jquery.iosslider.js:
194
289
1539
1656
2229

**Comment by marcwhitbread** [comment]
Which minifier causes these issues? Closure does not produce these problems.

**Comment by SGudbrandsson** [comment]
JSMin (which is the default minifier in W3 Total Cache for WordPress).
You can test it here: http://fmarcia.info/jsmin/test.html

**Comment by marcwhitbread** [comment]
Good to know. I will run some tests against this minifier as well and see if I can iron out the issues.

**Comment by SGudbrandsson** [comment]
Awesome, thanks :+1:
