### ISSUE TITLE
selected Class don't work outside parent container

### ISSUE THREAD

**Issue by brunomonteiro3** [iosscripts/iosslider#34]
Hello, 

I'm trying to move the pagination buttons outside the container div, if I do that, it still works. But, it don't add the "selected" class to the current slide. 

Take a look at this screenshot: http://i.imgur.com/ACb6o.gif (this is just an example...)

Is there any way to still add the class "selected" to the current slide button even if they are outside the main container?

This is the JS code that I'm using: http://pastebin.com/SdT1ft0P
This is the HTML: http://pastebin.com/wbck2ULh
And this is what I want: http://pastebin.com/WF4Csrs7 (note that the .iosSliderButtons is outside of the .slider)

Thanks in advance for any help!

**Comment by bergax** [comment]
You could simply use:

``` javascript
$('.iosSliderButtons .selected').removeClass('selected'); 
$('.iosSliderButtons .button:eq(' + args.currentSlideNumber + ')').addClass('selected')
```

That way you don't have to rely on in which div the indicator buttons are in relation to the slider.

**Comment by brunomonteiro3** [comment]
Many thanks bergax! Problem solved.
