### ISSUE TITLE
Slide page

### ISSUE THREAD

**Issue by jamalsoueidan** [iosscripts/iosslider#342]
Hello,

I have 9 elements in the iosSlider, and I would like to slide 3 elements at the time, right now it slide only 1 at the time.

I tried with.

```
$(this.slider).iosSlider('nextPage');
```

It throws an error:

```
Uncaught Error: invalid method call! 
```

How can I make the slider show 3 new elements everytime?

Thank you.

**Comment by marcwhitbread** [comment]
Invalid method call would imply that the function does not exist. What version are you using?

**Comment by jamalsoueidan** [comment]
This version
- Version: v1.3.24 (12/19/2013)

**Comment by marcwhitbread** [comment]
This method was added later (v1.3.37). f63250cdd727fc3b08647e15b1d16c59de847d1d
