### ISSUE TITLE
iOsSlider takes forever to load

### ISSUE THREAD

**Issue by notor** [iosscripts/iosslider#349]
It seems iOsSlider doesn't fully load until the entire page and all images are finished loading.

I've got a slider with about 15 images in it. If I load the page on broadband speed it's fine, but if the internet is slow it takes ages for the slider to gain its "swipe" functionality.

Is there any way to get the slider to function before the entire page is finished loading?

Thanks for your reply.

**Comment by marcwhitbread** [comment]
Put your initialization in $(document).ready(); That fires on DOM ready, so before any images.

**Comment by notor** [comment]
Currently it looks like:

```
jQuery(document).ready(function($) {
    $('#slider_<?php echo $sliderrandomid ?>').iosSlider({
```

(...)

So that's firing on DOM ready, right?

**Comment by notor** [comment]
So in my Chrome DevTools Network waterfall I see iosslider nice and near the top. But I just verified that the sliding and the responsiveness of the slider don't initiate until the very last image has loaded. I used Fiddler to emulate a slower internet connection to confirm this.

Any ideas?
