### ISSUE TITLE
Not functional on Opera Mini

### ISSUE THREAD

**Issue by peduarte** [iosscripts/iosslider#35]
Hello there,

I just tested this on Opera Mini (both on iPhones and Android) and the touch events do not seem to work.

It works if I click on the navigator thumbnail, but even that it behaves weird. 

Have you experienced this at all?

Thanks a lot
Pedro

**Comment by iosscripts** [comment]
I havn't done any opera testing, so I would assume it doesn't work right now. I will take a look at it.

**Comment by peduarte** [comment]
No worries, thank you.
Opera Mini is a crap browser man, it doesn't support a bunch of stuff.

**Comment by peduarte** [comment]
Hey man, 

The script works in Opera Mini actually. The problem is that Opera Mini does not support touch events.

So it works by adding a Next/Prev Selector.

Cheers!

**Comment by iosscripts** [comment]
Good to know. 

Also, today I learned that Opera Mini and Opera Mobile are different browsers... Maybe Opera Mobile works.
