### ISSUE TITLE
Create method to temporarily suspend sliding

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#38]
I am using iosSlider to slide tiles across the screen, these tiles have inner vertical scroll bars among other content. Currently when touch scrolling vertically if the finger is slightly moved right and left the whole slider shifts, in addition to vertically scrolling the tile. This is creating a large performance hit.

Is there a method I can call to temporarily suspend sliding, and enable it again with another call?

**Comment by iosscripts** [comment]
you can leverage the .iosSlider('destroy') method with some of your own JS and then call .iosSlider() to reinitialize.

**Comment by iosscripts** [comment]
I might want to look at this as a possible feature down the road. Maybe another public method.

**Comment by randomloop** [comment]
add a class to the slider div that disables pointers.  e.g. " pointer-events: none; "  Then remove it.  

<style>
.notouch {
        pointer-events: none;
    }
</style>


//somewhere in your event handler
$('.iosSlider').addClass('notouch'); //prevent scrolling (but still allows autoscroll)

//to remove it
$('.iosSlider').removeClass('notouch');  

*the destroy() method also destroys the ability to pinchzoom on the image in the slider.

**Comment by ColColonCleaner** [comment]
I don't think that will help, have already tried something like it. I have scrollable and clickable content inside the slider, a lot of it. The whole point is to disable sliding while the user is performing an interaction on the inner content.

**Comment by ColColonCleaner** [comment]
Ended up using the blockUI plugin. It works a lot better than attempting to override clicks or stop selection.
For those who would be using this to hide a background behind dialogs, it uses a z-index of 1000. Make your dialogs higher and they will overlay it.

Still having a function to stop the sliders from moving would be great. Maybe just remove the grab/grabbing functionality you assign to the slider container when clicking. adding it back once it's told to start moving again.

Thanks for your work :)

**Comment by iosscripts** [comment]
> I enabled pinchzoom on the images and found that changing the event handlers for touchstart and touchmove inside jquery.iosslider.js - from BIND to ON - causes my gesture event handlers to work better (using jQ 1.7.2 & jQM latest). If you peruse the iosslider.js, the referenced events are on lines (or close to lines) 1089 and 1200.

On is probably the best way to bind these events. The downside is, I would have to force users to upgrade to 1.7. Not sure if I'm ready for that.

> I also built an if statement around the scrollStartPosition/currentScrollRate and newChildOffset/onSlideChange portions of the above referenced methods - only letting them execute if only one finger/touch is detected.

If multiple touches are detected, you have disabled the slider? I'll have to look into this one. I originally coded it with only recognizing the first touch and ignoring the rest, but continue to respond based on the first touch.

I can't seem to find this comment on github, only in my email. Maybe you deleted it? :(

Thanks for doing this research :), I appreciate it!

**Comment by randomloop** [comment]
Here's how I'm getting the slider to lock. I elected to forego the "e.touches.length" (e.g. currentTouches) eval since that wasn't as transparent as positively setting and unsetting a flag.

Modifications to jquery.iosslider.js Version: v1.0.20 - not thoroughly tested, though it seems to work ok on my iPad. 

Add new setting: (add a comma after the onSlideComplete function closure)
line 662, add:  'lockSlider': false

line 1275
remove:  xScrollDistance = (xCurrentScrollRate[1] - xCurrentScrollRate[0]) / 2;
add:  xScrollDistance = settings.lockSlider ? 0 : (xCurrentScrollRate[1] - xCurrentScrollRate[0]) / 2;

line 1332
remove:  helpers.setSliderOffset(scrollerNode, (xScrollStartPosition - eventX - edgeDegradation) \* -1 \* scrollbarMultiplier);
add: settings.lockSlider ?  '' : helpers.setSliderOffset(scrollerNode, (xScrollStartPosition - eventX - edgeDegradation) \* -1 \* scrollbarMultiplier);

You can lock/unlock the slider by using the following methods inside your javascript code:
to lock:
$('.iosSlider').data('iosslider').settings.lockSlider = true;

to unlock:
$('.iosSlider').data('iosslider').settings.lockSlider = false;

Note: The 'if (currentTouches >=2 )' eval worked too, just that I think it's better to have a positive on off switch. To override the touchmove automatically if a gesture (two or more touches) is detected, then substitute "currentTouches >= 2" for "settings.lockSlider" in the ternary operators.

edits - original post substituted bullets for plus/minus signs, changed to remove/add.  Also, the new yScroll is messin with my pinch zoom :(  I suspect there's more work to be done to prevent yScroll too.

**Comment by iosscripts** [comment]
Very nice. I will do some testing on my end as well.

**Comment by randomloop** [comment]
The yScroll issue:  when a gesture on the slider causes the viewport to scroll vertically, it prevents any further pinch-zooming.

Here's what seems to be working pretty good now (only a slight change from above - line 1275 mod reverted, and new line 1250 mod)

Modifications to jquery.iosslider.js Version: v1.0.20 - not thoroughly tested, though it seems to work ok on my iPad. 

Add new setting: (add a comma after the onSlideComplete function closure)
line 662 +  'lockSlider': false

line 1250
remove: if(isTouch) {
add: if(isTouch & !settings.lockSlider) {

line 1332
remove: helpers.setSliderOffset(scrollerNode, (xScrollStartPosition - eventX - edgeDegradation) \* -1 \* scrollbarMultiplier);
add: settings.lockSlider ?  '' : helpers.setSliderOffset(scrollerNode, (xScrollStartPosition - eventX - edgeDegradation) \* -1 \* scrollbarMultiplier);

You can lock/unlock the slider by using the following methods inside your javascript code:
to lock:
$('.iosSlider').data('iosslider').settings.lockSlider = true;

to unlock:
$('.iosSlider').data('iosslider').settings.lockSlider = false;

**Comment by iosscripts** [comment]
I think for the suspend/unsuspend methods I think I will be going to follow the same public method format as the existing public methods like so:

``` js
$('.iosSlider').iosSlider('lock');
$('.iosSlider').iosSlider('unlock');
```

This approach will also allow me to update the method contents from one version to the next and have the end user's calls unaffected.

Wouldn't it be simpler to just have the following at the beginning of each touch event function?:

``` js
if(settings.lockSlider) return false;
```

Unless I am missing something, don't we want to completely disable the touch events on lock?

**Comment by ColColonCleaner** [comment]
By completely disable touch events i would think you mean any touch event that would cause the slider to move, if that is the case then yes that sounds good. I still need to be able to interact with items within the slider though...like jquery buttons and mobile listviews etc.

**Comment by iosscripts** [comment]
Yes; That's exactly what it does right now. Does a quick check when you initially touch the slider, if locked: true, abort.

**Comment by ColColonCleaner** [comment]
Excellent. Exactly what I needed. Thanks!

**Comment by randomloop** [comment]
As long as it doesn't interfere with desktopClickDrag, sounds good.

**Comment by randomloop** [comment]
Note: Argh, unable to edit post on iPad (or delete). to extend that last post...

Does the lock method also disable desktopClickDrag and are there any issues with that?  I can't anticipate any.

**Comment by iosscripts** [comment]
@randomloop Actually it does. It prevents all interaction via touch/click with the slider. I may be confused, what is that main reason (or your reason) for using this feature?

**Comment by randomloop** [comment]
I've been integrating the slider into a website that displays products and information about those products on each slide (image & caption, plus add'l elements such as swatches). 

We're only 'pinch zooming' right now, though we have anticipated a UI where the swatches are dragged and dropped onto the image to change the color/img src.  In this situation, we'd want the slider to lock but not prevent drag and drop/touchmove on elements within a slide.

It's not an immediate issue and there are certainly other ways to program around it if we go that direction.

**Comment by iosscripts** [comment]
> We're only 'pinch zooming' right now, though we have anticipated a UI where the swatches are dragged and dropped onto the image to change the color/img src. In this situation, we'd want the slider to lock but not prevent drag and drop/touchmove on elements within a slide.

The lock functionality will not interfere with any custom JS touch events you are adding within your pages. 

On a side note, I am beginning to understand your logic above regarding the touches >= 2 locking the slider. I have not implemented any logic to lock the slider when this happens. I will include it in a new issue targeted specifically at solving the zoom/slider drag issues.

**Comment by randomloop** [comment]
Sounds good. Thanks!

**Comment by Pinkee** [comment]
Hi, I'm working on simple App,in my page i have a toggle switch. If i slide(horizontal) that switch, the whole page slides to next page.
But i dont want this. how to lock the page except that particular toggle switch.

**Comment by iosscripts** [comment]
@Pinkee Are you building a browser app? or a iOS app? Do you have a screenshot of what you are describing? I am having trouble visualizing the issue.

**Comment by Pinkee** [comment]
It is iOS app and also browser support. Can u imagine the page with toggle switch. If i slide the switch, my whole page slides to next page...(its like jquerymobile.com toogle switch)

**Comment by ColColonCleaner** [comment]
It seems like your IOS app is taking precedence over the web part of it, if you slide to the right/left it assumes you want to change page.

By what i see you have four options.
1. Disable gestures to change between pages altogether, use buttons.
2. Change the sensitivity of the page slide so you would need to slide further than the length of the toggle switch for the whole page to change.
3. Make it so people cannot drag the toggle at all, only click on it, simple css attribute assigned to it. It will still have the same functionality as a toggle switch, but people will just need to tap it to change the value.
4. Use a checkbox instead.

**Comment by Pinkee** [comment]
Hi cobeliga, thanks for ur options..
 "Make it so people cannot drag the toggle at all, only click on it, simple css attribute assigned to it. It will still have the same functionality as a toggle switch, but people will just need to tap it to change the value."
 Basically my requirement to drag the toggle switch. Please help me to find a way to resolve it.

**Comment by ColColonCleaner** [comment]
Move to option one then. Or 2 as a fallback. I don't see any other option at this point. I'm not familiar with native IOS apps, just web and how things are usually implemented on mobile. Specifics are outside my realm in this case. Sorry.

**Comment by Pinkee** [comment]
Hi cobeliga, thanks for ur reply... lemme find any other way and try..
