### ISSUE TITLE
Add a hook for "onSlideStart", or something like it.

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#41]
There are methods for slideChange, complete, etc. But something that i think was overlooked is slideStart. An event that is fired when the user begins to slide the slider. Implementing this would be a good feature and greatly helpful with my current project. Hopefully it would not cause much lag.

**Comment by iosscripts** [comment]
I had originally planned on adding this and eventually forgot about it, thanks for reminding me :). Shouldn't be too difficult to implement.

**Comment by iosscripts** [comment]
Added it in v1.0.5
