### ISSUE TITLE
Documentation needed for args array.

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#45]
Please list on the website what is actually exposed in the args array for onSlideChange, etc. If i missed it somewhere i apologize, but i do not see any documentation. Thanks.

**Comment by iosscripts** [comment]
It's ok. Kind of hard to see it. Its within the option description of each of the functions on http://www.iosscripts.com/iosslider/

Returned parameter: 'args' (array) { settings, sliderObject, currentSlideObject, currentSlideNumber }

**Comment by ColColonCleaner** [comment]
Ok thanks. And i must say you are consistently dang fast with these responses, it's really nice. :)

**Comment by iosscripts** [comment]
If you're awesome enough to use one of my scripts, I try to be equally awesome and help you make it work :)
