### ISSUE TITLE
Sliders being loaded with width 0

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#47]
The environment that i'm working with is heavily dynamic, and i believe that is messing with some slider functionality as things inside it are being ajax loaded and moved quite often.

I am developing a web app for ipad, and it has two sliders on it so far. One for a top set of tiles, and another for a lower set. Three tiles are shown on screen at a time simply by setting their width to 33.333etc%

When i load the page without initializing slider, the tiles form perfectly as i had them set with css. But if i load the page and initialize slider, the slider loads with width 0. Even if i set it to a pixel width instead of percent (using the standard shown on your site).

Here is a snippet of the code, cant show it all for trade secret reasons but i'll do what i can.

<pre><code>&lt;div id="sliderHolder"&gt;
    &lt;div class="sliderHolder" id="TopSliderHolder"&gt;
        &lt;div id="tileSlider_Top" class='tileSlider_Top'&gt;
            &lt;div class='slider'&gt;
                &lt;div class='sliderTile' id='item1'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item2'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item3'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item4'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    &lt;div class="sliderHolder" id="BottomSliderHolder"&gt;
        &lt;div id="tileSlider_Bottom" class='tileSlider_Bottom'&gt;
            &lt;div class='slider'&gt;
                &lt;div class='sliderTile' id='item1'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item2'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item3'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item4'&gt;
                    &lt;div class='tilePadding'&gt;
                                        &lt;/div&gt;
                &lt;/div&gt;
                &lt;div class='sliderTile' id='item5'&gt;
                    &lt;div class='tilePadding'&gt;&lt;/div&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
</code></pre>

the sliderholder div has its height and width set to pixel dimensions by js on window resize, and the sliders are destroyed/restarted on window resize.

The initialization code is thus:
<pre>
$('#tileSlider_Top').iosSlider({
        snapToChildren: true,
        desktopClickDrag: true,
        navSlideSelector: '#tileSlider_Top .slideSelectors .item',
        onSlideComplete: topSlideComplete,
        onSliderLoaded: topSliderLoaded,
        onSlideChange: topSlideChange,
        frictionCoefficient: '0.96',
        snapFrictionCoefficient: '0.96',
        elasticPullResistance: '.6'
    });
    $('#tileSlider_Bottom').iosSlider({
        snapToChildren: true,
        desktopClickDrag: true,
        frictionCoefficient: '0.96',
        snapFrictionCoefficient: '0.96',
        elasticPullResistance: '.6'
    });
</pre>

great, having trouble showing html code github? one sec man while i fix this...

**Comment by ColColonCleaner** [comment]
Good grief how do you paste html code here? It always renders it instead of just displaying as is...

**Comment by iosscripts** [comment]
First off you have duplicate id's in both of your sliders, that can cause some issues. But you may have just copied and pasted them for this demo so I'll ignore it.

Which slider loads with width 0? Both? Can you give me your css for .tileSlider_Top, .slider, and .sliderTile so I can build a test case?

**Comment by ColColonCleaner** [comment]
I think it was an artifact of the way our project was loaded. We are doing formatting and SJAX calls in document.ready() but their still seems to be a race condition between the slider initialization and our formatting, the formatting sometimes hangs so the slider loads with 0 width. Attempting to find a way to run it all synchronously but no luck so far. i'll keep you posted, i dont think it is cause by your code as of now.

**Comment by iosscripts** [comment]
You can try putting iosSlider in document.load() in stead which is fired later, or you can just put the iosSlider call in the $.ajax success parameter. 

Above you said your width for your slides is set to 33%. Is that still the case in the CSS?

**Comment by ColColonCleaner** [comment]
Yes that is in the CSS. But that was not the issue. The problem turned out to be that we were calling restart sliders on window resize, this event (while existent) is very buggy on the iPad. It was firing 6+ times just from loading the page. This, in combination with the 200ms restart delay for the sliders caused some kind of inconsistency. Changing to the following code fixed it.

Posted it in the other question, but it's more relevant here.

//check if the browser supports orientation change
    var supportsOrientationChange = "onorientationchange" in window,
    //if it does, use orientation change, otherwise use resize
    orientationEvent = supportsOrientationChange ? "orientationchange" : "resize";
    //add listener to check for rotation or resize
    window.addEventListener(orientationEvent, function() {
        //reformat everything
        formatAll();
    }, false);

**Comment by marcwhitbread** [comment]
Are you saying you attached your own event to the window to destroy/init on resize?

**Comment by ColColonCleaner** [comment]
Yes, everything in the formatAll function is called when this is fired. On the tablet it is called when jquery/jquerymobile event "orientationchange" is fired. and on desktop browsers it is fired on window resize. All the event is is a string.

**Comment by ColColonCleaner** [comment]
orientationEvent is just a string. It is assigned to orientationChange when the boolean is true, or resize when it's false. sorry if i was unclear.

**Comment by marcwhitbread** [comment]
No it makes sense. I use a very similar call within the iosSlider script.

``` js
var supportsOrientationChange = 'onorientationchange' in window;
var orientationEvent = supportsOrientationChange ? 'orientationchange' : 'resize';

$(window).bind(orientationEvent + '.iosSliderEvent', function() {       
    if(!init()) return true;
});
```

Where the slider variables/CSS are reinitialized based on window size changes. Could what you are doing be conflicting with that?

**Comment by ColColonCleaner** [comment]
Wow thats almost exactly what i have...and i didn't even know that was a part of your code. what line is that/function name? and wait just one minute, i don't have to reinitialize the sliders on resize? X_X good grief. Trying this out now...

**Comment by ColColonCleaner** [comment]
Ok i have a question on your code. What fires the 'resize.iosSliderEvent' event? Maybe i'm just not familiar with the event syntax, but is the '.' making it a sub-event that fires along with resize?

**Comment by ColColonCleaner** [comment]
Ok yeah i still need to reboot the sliders manually or my formatting goes out the window on resize. The slider tiles expand to 100% of the slider width instead of 33% so i have only 1 tile on screen instead of 3.

**Comment by marcwhitbread** [comment]
The .iosSliderEvent part of an event is know as a namespace. I use this so that I can find and easily unbind the .iosSliderEvent's when a slider is destroyed. 

> Ok yeah i still need to reboot the sliders manually or my formatting goes out the window on resize. The slider tiles expand to 100% of the slider width instead of 33% so i have only 1 tile on screen instead of 3.

This shouldn't be happening. Can you give me the CSS for the slider elements?

**Comment by marcwhitbread** [comment]
> Ok yeah i still need to reboot the sliders manually or my formatting goes out the window on resize. The slider tiles expand to 100% of the slider width instead of 33% so i have only 1 tile on screen instead of 3.

Shit, a bug somehow. I am able to reproduce it with percentage based slides. I will get it working again in a jiffy!

**Comment by ColColonCleaner** [comment]
tileslider_top/bottom are the two sliders

sliderTileThree and sliderTileTwo classes are dynamically applied to the .sliderTile elements depending on the rotation of the screen. two slides for portrait and three for landscape.

#tileSlider_Top,
#tileSlider_Bottom {
    /\* required */
    position: relative;
    top: 0;
    left: 0;
    overflow: hidden;

```
width: 100%;
height: 100% !important;
line-height:100%;
```

}

#tileSlider_Top .slider,
#tileSlider_Bottom .slider{
    /\* required */
    width: 100%;
    height: 100% !important;
}

/_#tileSlider_Top .sliderTile,
#tileSlider_Bottom .sliderTile_/
.sliderTile {
    float: left;
    margin: 0;
    height: 100%;
}

.sliderTileThree{
    width: 33.333%;
}

.sliderTileTwo{
    width: 50%;
}

**Comment by ColColonCleaner** [comment]
Alright cool thanks! :)

**Comment by marcwhitbread** [comment]
Pushed a fix to the master branch. Try it out: https://github.com/iosscripts/iosSlider/blob/master/_src/jquery.iosslider.js

**Comment by ColColonCleaner** [comment]
Man, you rock. It works, thanks, that's a ton fewer timeouts i need to call. :)

**Comment by ColColonCleaner** [comment]
Ah! Hold the phone, it works on PC, but not on iPad. Sorry for the premature burst of joy :(
