### ISSUE TITLE
Double sliding with onSlideChange set

### ISSUE THREAD

**Issue by WickedSeack** [iosscripts/iosslider#49]
I have the last version of IosSlider and I encoutered the following issue :

When sliding the slider was too sensitive, skipping the next  slide and jumping to the next after very easily (even with very light finger swipe).

I tried to troubleshoot this issue and I discovered that unsetting the "onSlideChange"  option fixed this issue, but I couldn't find any relation between the "onSlideChange" and the slider sensitivity.

**Comment by iosscripts** [comment]
There is no relation actually... onSlideChange is just a function that is fired when the slide changes. I will take a look at it though... What are you testing it on?

If you have snapToChildren enabled, the slider is meant to jump to the next/prev slide with high sensitivity. I modeled it after the iPhone/iPad home screen.

**Comment by iosscripts** [comment]
Also, if you have a demo, or some code I could at, that would be great. Just to make sure you aren't doing anything weird.

**Comment by WickedSeack** [comment]
Thanks for your reply,

> What are you testing it on?

I'm developing an iphone app which uses a webview with IosSlider to show some information.

> If you have snapToChildren enabled, the slider is meant to jump to the next/prev slide with high sensitivity. I modeled it >after the iPhone/iPad home screen.

The probleme is that it skips the (next | prev) slide and jumps to the (next | prev) after.

> Also, if you have a demo, or some code I could at, that would be great. Just to make sure you aren't doing anything >weird.

Here is my html code :

``` html
<body>
    <header> </header>
    <div id="fb-root"></div>
        <div id="timeView"><div id="progressBar"></div></div>
    <div id="content-pane" class="swipe">
        <div id="timeline" class="swipe-wrap">
        </div>
    </div>
    <nav>
    <a href='#' class='prev'><em>prev</em></a>
    <a href='#' class='next'><em>next</em></a>
  </nav>
</body>
```

where ".swipe" is the same as ".iosslider" and ".swape-wrap" as ".slider"

I add all my slides with a javascript function because I have a variable number of slide to show, then I initialize my slider with this code : 

``` javascript
$('.swipe').iosSlider({
    snapToChildren: true,
    desktopClickDrag: true,
    navPrevSelector: $('.prev'),
    navNextSelector: $('.next'),
    startAtSlide: this.data.length,
    onSlideStart: function(args) {
    },
    onSliderLoaded: function(args) {
        /* Some code */
    },
    onSlideComplete: function(args) {
       /* Some code */
    }
    });
```

and it works fine but when I change the initialization by : 

``` javascript
$('.swipe').iosSlider({
    snapToChildren: true,
    desktopClickDrag: true,
    navPrevSelector: $('.prev'),
    navNextSelector: $('.next'),
    startAtSlide: this.data.length,
    onSlideStart: function(args) {
    },
    onSliderLoaded: function(args) {
        /* Some code */
    },
    onSlideComplete: function(args) {
       /* Some code */
    },
        onSlideChange : function(args) {
           /* Some code or empty  */
       }
    });
```

the issue appear.

Thanks for your help.

**Comment by iosscripts** [comment]
It's possible that this may have something to do with it being in an app. I am unfamiliar with embedding HTML/JS in an app, does the code run in an iFrame or some sort of HTML wrapper? If so, what are the dimensions of that wrapper.

Can you show me how you are adding the slides?

The CSS for: .swipe, .swape-wrap, and .slide.

I'm trying to build a test case to reproduce it but I've had no luck so far...

**Comment by WickedSeack** [comment]
> It's possible that this may have something to do with it being in an app. I am unfamiliar with embedding HTML/JS >in an app, does the code run in an iFrame or some sort of HTML wrapper? If so, what are the dimensions of that >wrapper.

I'm using a UIWebview, a native feature of IOS, it use webkit in safari to render a webpage.
Concerning the webpage nothing special with it, just some redefinitions of css for the iphone display.

> Can you show me how you are adding the slides? 

``` javascript
$.each(this.data, function(index, leank) {
    var div = jQuery('<div class="wrapper"></div>');
    var wrap = _timeline.createLeank(leank);
    $(div).append(wrap);
    $(_timeline.timeline).append(div);
    if (!index)
        $(div).find('.cornerTop').attr("class", "cornerTopExtremLeft");
    else if (index == _timeline.data.length - 1)
        $(div).find('.cornerTop').attr("class", "cornerTopExtremRight");
    });
```

where "_timeline.timeline" is a reference to ".swipe-wrap"

> The CSS for: .swipe, .swape-wrap, and .slide.

``` css
.swipe {
 position: relative;
    left: 0;
    top: 0;
}
.swipe .swipe-wrap {
    width: 100%;
    height: 100%;
    padding: 15px 10px 10px 10px;
}
.swipe .swipe-wrap .wrapper {
     float: left;

    position: relative;
    top: 40px;
    width: 614px;
}
```

**Comment by iosscripts** [comment]
I'm having some real difficulty reproducing this based on this info. If you want further assistance, I'm going to need you to make a jsfiddle, or put a demo on a web server somewhere that I can look at.

**Comment by WickedSeack** [comment]
I succeed to reproduce the issue on google-chrome, try to test on this url :

http://sd-33870.dedibox.fr/sandbox/

I change the content of the slide with some random images, because i need a lot of stuff for the original content but it's only available at work, I hope it will be enought for you.

**Comment by iosscripts** [comment]
I'm sorry but I'm not seeing any unintentional slide skipping when I click/drag in chrome for desktop. Sure, if you pull on it, it may skip the next slide based on velocity. Is this what you are refering to? 

You can bring down the velocity on release by lowering the frictionCoefficient option.

**Comment by WickedSeack** [comment]
I'm putting a video on youtube, I'll give you the link when it finish to upload.

I used firefox but I have the same on chrome.

> Sure, if you pull on it, it may skip the next slide based on velocity. Is this what you are refering to?

Yes, but it seems that with the same frictionCoefficient using the callback onSlideChange make the slider more sensitive than without the callback.

**Comment by WickedSeack** [comment]
here is the link : http://www.youtube.com/watch?v=HLwjJ90xQ6M

**Comment by iosscripts** [comment]
Thanks for the vod. I will take another look at the script and see if I can isolate it.

**Comment by ghost** [comment]
Hi Guys,
Any luck with this as im having the some problem when onSlideChange set slider has a double slide instead of snapping to next element.

Thanks and great script!

**Comment by iosscripts** [comment]
if you pull hard enough, it is supposed to  slide beyond a single slide.

Are you looking for functionality that limits the snapping to 1 slide maximum?

**Comment by ghost** [comment]
Yes that would be ideal.

**Comment by iosscripts** [comment]
Created issue #92. New option to limit sliding to 1 slide (or width of iosSlider block).
