### ISSUE TITLE
Add vertical slide option

### ISSUE THREAD

**Issue by iosscripts** [iosscripts/iosslider#5]
Ability to toggle vertical/horizontal/both slide directions.

**Comment by laurend** [comment]
This would be really great...

**Comment by brunomonteiro3** [comment]
Totally looking forward for this feature.

**Comment by mstuart** [comment]
Really looking forward to this feature.  Will it be in the next release? :+1:

**Comment by iosscripts** [comment]
Working beta for vertical: https://github.com/iosscripts/iosSlider-vertical. All issues relating to vertical should be moved there.
