### ISSUE TITLE
Should have links to just JS files

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#50]
Just a suggestion that will help those who rely on your plugin updates. On your website you should have 3 links instead of just one. The version with examples, a direct link to the full js file, and a direct link to the minified JS file. I am having to unzip every time just to get the js files out of the example.

Just a convenience thing :)

Thanks for all your work.

**Comment by iosscripts** [comment]
I do it so I can track my downloads through Github. And a zip is just easier. If I get more messages about it I will definitely change it up.
