### ISSUE TITLE
Does not work on Firefox/Opera Mobile (Android)

### ISSUE THREAD

**Issue by dbeinlich** [iosscripts/iosslider#52]
Plugin does not work on Firefox Mobile (Version 14) - testet on Android 4.04.
All three options (slide, pager and nav-slider) are not working.

**Comment by iosscripts** [comment]
I have committed an update to master (v1.0.10) resolving this issue. iOS event conflicts + no css3 translation support was the culprit. Also, first time testing it :). Let me know if you are still experiencing issues.

**Comment by dbeinlich** [comment]
Hi Marc,

thank you very much! Maybe it solves a similar problem on Opera Mobile … i'm going to test it.

Our customer will purchase a license for the project end.

Many greetings,
Dirk

Am 06.07.2012 um 18:13 schrieb Marc Whitbread reply@reply.github.com:

**Comment by iosscripts** [comment]
I'll take a look at opera mobile as well. Thanks for submitting the issue :)

**Comment by iosscripts** [comment]
Opera Mobile seems to be working on android as well now.

**Comment by dbeinlich** [comment]
I have testet it on firefox and opera mobile this morning - both clients works fine! thank you ver much!
