### ISSUE TITLE
method callback for allSlidersloaded?

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#53]
i found i could solve the 0px width problem I had by only letting my webapp continue loading dialogs and other content after the first slider on my page is loaded, using your callback. however that obviously left the other slider just hanging in the breeze, it would be fine if it happend to finish loading at the right time. would you be able to implement a method that is like onsliderload, but is across all sliders on a page? So it only fires once all sliders have completely loaded?

If you cannot, please point me in a direction that i can implement this myself, you obviously have more experience than I. i've never done a 2+ input "and-gate" callback.

One simper way to do this (in my mind anyway), would be to have a constructor that initializes a list of input divs as sliders, and the callback would be fired after the loop ends. Just ideas popping in my head, hope they help, once again thanks for your work.

**Comment by ColColonCleaner** [comment]
Just thought of a solution that is a lot less intensive, calling each slider's init off the previously loaded slider's onsliderloaded callback. The final onsliderloaded callback being the release for the rest of the program. Might take more time to load since this is now pseudo-synchronous, but at least it will be loaded in the correct order.

**Comment by iosscripts** [comment]
Idea: you could load them all asynchronously and onSliderLoaded increase a global variable by 1. Lets say you have 5 sliders. Each one fires and increases the variable by 1. You have a setInterval function which checks the value of this global variable every 10 milliseconds, if the value = 5, do something.

**Comment by ColColonCleaner** [comment]
Ended up using your suggestion. thanks much :), it helped since now i can log all other loaded elements to see where things fail if they do.
