### ISSUE TITLE
current slide

### ISSUE THREAD

**Issue by dwehrmann** [iosscripts/iosslider#54]
Is it possible to add a class to identify the current active slide?

**Comment by DarkHero8** [comment]
find the active indicator may help

**Comment by marcwhitbread** [comment]
Absolutely. Using the onSlideChange function you could do something like so: 

``` js
$('.iosSlider').iosSlider({
     onSlideChange: slideChange
});

function slideChange(args) {
    $('.slides').removeClass('current');
    $(args.currentSlideObject).addClass('current');
}
```

**Comment by ColColonCleaner** [comment]
This works, but you would also need to remove the class from all other slides that aren't the current one. Otherwise once all slides have been scrolled to once, they will all have the 'current' class.

**Comment by marcwhitbread** [comment]
Fixed ^^

**Comment by randomloop** [comment]
Adding a class to identify the current slide and then using that class as a selector to find attributes of other elements within that slide, works, but not consistently for the first slide (infinite slider). Using the currentSlideObject as the selector works all the time.

**Comment by FMVanity** [comment]
Hello, I found this and it helped me a lot, but I have a problem, how can I access the child elements of the currentSlideObject?? 

NVM, I didn't read the comment above, it helped me too :)
