### ISSUE TITLE
Feature Request: Multiple slides on screen at once

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#55]
Right now i am having to use CSS to make the slider show 3 tiles/slides. I just set the width of slide class to 33.33etc% to show 3 slides and 50% to show two.

It operates flawlessly (except for a couple click issues on PC but i think i can get around this), just as expected.

The problem comes when i want to resize the page. If i use your internal resizing code, after resizing the window a little it defaults back to 1 silde on screen. So i have to destroy and restart the sliders all the time during resize or orientation change.

If you just put a setting in your init that just takes how many slides to display on screen that would clear up all my issues.

**Comment by nicooprat** [comment]
+1.

Could you give an example of how you achieved this with only CSS percents please ?

**Comment by ColColonCleaner** [comment]
The structure of the slider is (Slider -> moving stage -> slides) so you need to use his guide for assigning the css overall. Then just change width value on the slide elements to 33% or whatever you wanted. When slider is initialized, it grabs whatever the current width of the slides are and converts it to a pixel value. Should work fine. Experiment with it without starting slider, if it looks the way you want (for the first few slides anyway, or whatever is visible in the stage) chances are it will work once slider is started as well.

**Comment by nicooprat** [comment]
Thanks ! I also just figured that your 10th example shows this. Great work !

---

Nico Prat
nicooprat@gmail.com
