### ISSUE TITLE
ipad performance issues.

### ISSUE THREAD

**Issue by samuelbirch** [iosscripts/iosslider#59]
Within the init function, when i have the webkit css set:

'webkitPerspective': 1000,
'webkitBackfaceVisibility': 'hidden',

i get really bad performance issues on the iPad. It takes a lot longer to actually load the page and then when sliding between items it has a really bad delay the first time and doesn't render the slide. Only once you have tried to view all the slides does it work as expected.

When i remove these couple of lines, it works great!

are these needed? - and if so can we have an option to not use them?

**Comment by iosscripts** [comment]
I might be able to remove them. That is definitely a bit of legacy code that's been sitting around. I believe I used it as a hack to prevent some early screen flicker issues. I'll take a look at removing it permanently.

Good find! :)

**Comment by iosscripts** [comment]
Added to v1.0.20 with issue #60.
