### ISSUE TITLE
How to center the main slide, when slider width is 100%

### ISSUE THREAD

**Issue by evincent** [iosscripts/iosslider#66]
Hi, I set the .iosSlider at 100%. That way I can view 2 or 3 slides at the time (depending on my screen resolution). I would like to set the main slide (first one in the list) to be at the center of the page and other slides on the left and right (I am using infinity feature). How to calculate the offset?

Thank you.

**Comment by iosscripts** [comment]
You can't really achieve this using the plugin. I would say your best bet is to set the slide you would like to see in the middle in the second slide spot. Have your slide width set to 33.3333% and that way the middle slide will always be centred.

**Comment by evincent** [comment]
Thank you for the suggestion. I did make the .slider width set to 33.3333%, but it gets overwritten by the element style. 
The only way I achieved what I desired, was to set the owerflow: visible in the .js file, though that created a bottom scroll bar. 

Any other suggestions?

**Comment by iosscripts** [comment]
Try setting the iosSlider div to width 33.3333% width and then centering that div via margin: 0 auto; You would then need to put overflow-x: visible on the iosSlider and slider divs.

overflow-x: visible should not be showing scrollbars, only overflow-x: scroll does that... I think.

**Comment by evincent** [comment]
Hmm... still didn't do the trick. This is what I am trying to achieve: http://cedar.olemiss.edu/working/erika/umredesign/new/index3.html

The only time I get it working when I set overflow: visible in the jquery.iosslider.js file. But that creates a browser scroll bar. I am running out of the ideas and might just stay with this version.

Please let me know if there is anything else I can do. Thank you

**Comment by iosscripts** [comment]
> Hmm... still didn't do the trick. This is what I am trying to achieve: http://cedar.olemiss.edu/working/erika/umredesign/new/index3.html

This is exactly how I visualized the layout in my head so that's good. I will try and figure out a strategy and throw a demo together for you in the next day or so :). Either way I will keep you posted.

**Comment by evincent** [comment]
Thank you so much for your help!

**Comment by iosscripts** [comment]
Learned something today, if overflow-x is visible and overflow-y is hidden, scrollbars always show. Please download the v1.0.23 zip. In the _demos/_example/7-Centered-Slides/ you will find a demo. I added some new options for overriding the default CSS of the stage and slider. I will update the documentation to reflect these changes at a later time.

Let me know if that helps :)

**Comment by evincent** [comment]
Wow. That looks great!! Thank you, I have been working on it for quite some time, this is very helpful. It even works on IE!

**Comment by iosscripts** [comment]
No problem. I will close this issue for now :).

**Comment by evincent** [comment]
I have noticed that on the iPad and iPhone the vertical bar still appears. I tried media queries to set body overflow-x: hidden, but this didn't do the trick. The only way I was able to hide the vertical bar when using media queries, when I set the container overflow-x: hidden. 

Is there any way to fix that? I would hate to lose the opportunity to display parts of other images on the left and right of the main image.

**Comment by iosscripts** [comment]
iOS seems to be misbehaving... I was able to get it working by adding another div outside the container div in my demo like so: 

``` html
<div class = 'containerOuter'>

    <div class = 'container'>

        <div class = 'iosSliderContainer'>

            <div class = 'iosSlider'>

                <div class = 'slider'>

                    <div class = 'item item1'></div>
                    <div class = 'item item2'></div>
                    <div class = 'item item3'></div>
                    <div class = 'item item4'></div>
                    <div class = 'item item5'></div>

                </div>

            </div>

        </div>

    </div>

</div>
```

And the CSS for thew new containerOuter:

``` css
.containerOuter {
    position: absolute;
    left: 0;
    right: 0;
    background: #aaa;
    height: 200px;
    overflow: hidden;
}
```

Let me know if that helps :)

**Comment by evincent** [comment]
Thank you, that was a great suggestion. I do have some divs under the slide, so will just have to code them properly, but it is great to have many options.
