### ISSUE TITLE
Performance Issues between version 20+ and version 13

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#68]
Something i did not notice before on the iPad (as i have had limited access to one over the last week or so), is upgrading to version 20+ of your script (from version 13) is causing a major performance hit in my app. I am sending you an email with a link describing the problem. Will include issue # in subject.

**Comment by iosscripts** [comment]
Suggestion made in issue #59 may have caused the issue. Test v1.0.24 for possible resolution.

**Comment by ColColonCleaner** [comment]
Ok will do, i'll get back to you soon.

**Comment by ColColonCleaner** [comment]
Confirmed fixed running version 24. Thanks much.

**Comment by iosscripts** [comment]
Fantastic. Sorry about that man. Thanks for your patience. 

I need to be more careful which pull requests I accept from the community going forward :S.
