### ISSUE TITLE
Moving fast on contact with slider causes no visual update

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#70]
On the iPad, moving the finger fast across the screen on contact will cause the no sliding effect. However, the methods called on slideChange are still firing at their correct times. Video sent in email with issue #.

**Comment by iosscripts** [comment]
I have discovered the root of the issue. Basically there is a test that takes place to check if the user is trying to scroll vertically (which locks the slider and then scrolls the page vertically) or horizontally (which locks the page scroll and scrolls the slider). Moving across quickly is actually triggering the y-axis velocity test to lock the slider.

I will look at modifying the velocity trigger to be relative to the x-axis trigger to better identify what is actually an intended y-axis scroll attempt and a very fast x-axis swipe. 

Good find :)

**Comment by iosscripts** [comment]
Fix added in v1.0.32. Thanks again for the video, they really help a lot :)

**Comment by ColColonCleaner** [comment]
No problem, glad to help :)
