### ISSUE TITLE
Keyboard Shortcuts <- & ->

### ISSUE THREAD

**Issue by Osifer** [iosscripts/iosslider#71]
Self explanatory, adding the ability to control the slides with your keyboard arrow buttons would be nice.

**Comment by iosscripts** [comment]
Should be pretty easy to implement. I will add it as a boolean parameter, disabled by default.

**Comment by iosscripts** [comment]
Added keyboardControls (boolean) option in v1.0.31 for left/right keyboard shortcut navigation.
