### ISSUE TITLE
Windows 7 phone swiping is not working

### ISSUE THREAD

**Issue by zaheerabbass** [iosscripts/iosslider#74]
Swiping is not working on windows 7, IE9 browser. What is possible solution for this?

**Comment by iosscripts** [comment]
Windows 7 phone is not supported currently, but IE9 should be. Which version of the script are you using?

**Comment by iosscripts** [comment]
Sorry misread that. IE9 ON windows 7 phone. I havn't done any testing on a windows phone :(. I might need to buy one. Any recommendations?

**Comment by iosscripts** [comment]
I have created issue #76 to track this enhancement.

**Comment by trungwebsite** [comment]
Did you fixed this ? Seems it's still not working on Window phone :S

**Comment by marcwhitbread** [comment]
Windows phone is not supported at this time unfortunately.
