### ISSUE TITLE
Go To Corresponding selected slide

### ISSUE THREAD

**Issue by Pinkee** [iosscripts/iosslider#75]
Hi, I have 3 iosSliders(first page), each have 3 iosSliders(second page)
ie. slide1->slide11, slide12, slide13
      slide2->slide21, slide22, slide23
      slide3-> slide31, slide32, slide33.

If i click "go" button in  slide2, it redirects to second page(it has 3 slides)

In slide21 or slide22 or slide23 when i click previous button, it has to redirect me to the corresponding first page slide(ie. Slide2).

Any suggestions please..

**Comment by ColColonCleaner** [comment]
Ok i don't Think i understand your layout. So you have 3 sliders, each with 3 slides? Only one actual page though, right?

**Comment by Pinkee** [comment]
hi cobeliga... i found the solution... thanks!
