### ISSUE TITLE
Font antialiasing in Safari

### ISSUE THREAD

**Issue by shortcuts-zz** [iosscripts/iosslider#78]
Version v.1.0.28 shows a change in font-anitaliasing with safari – in Version 1.0.20 everything was fine.

**Comment by iosscripts** [comment]
Can I see your slider HTML? I want to see which tags wrap your text.

Most likely has to do with the CSS:

``` js
'webkitPerspective': 1000,
'webkitBackfaceVisibility': 'hidden',
```

The CSS is applied to the slider and offers major performance improvements because is utilizes hardware acceleration. You might want to try explicitly turning it off on the text elements that are acting up.

``` css
-webkit-backface-visibility: none !important;
```

Let me know if that helps.

**Comment by shortcuts-zz** [comment]
Dear Marc,

thank you for your fast reply and your work.

This is the Link with the Page (work in progress) :

http://nextgen.cp-autosport.com/index.php?id=7

When you scroll down and your Browser is so small, that the Slider moves under
the floating menu-element, you can see, that the text changes the antialiasing. (in Safari 6 / 10.8 )

The same thing didn't happen with the older Version of the iosSlider.

Best regards,

Dirk Studzinski

Short Cuts GmbH | Mehringdamm 55 | 10961 Berlin
+49 30 253 912 13 | fax +49 30 253 912 20 | studzinski@short-cuts.de 

Am 08.08.2012 um 15:24 schrieb Marc Whitbread notifications@github.com:

**Comment by iosscripts** [comment]
Can you try putting:

``` css
-webkit-font-smoothing: subpixel-antialiased;
```

on the anchor link in question? Send me a link when it's updated. Let me know if that works. 

In the long term, I will try and find out why this is affecting elements outside the slider.

**Comment by shortcuts-zz** [comment]
I think, that does the trick.

http://nextgen.cp-autosport.com/index.php?id=7

Thank you.

Dirk Studzinski

Short Cuts GmbH | Mehringdamm 55 | 10961 Berlin
+49 30 253 912 13 | fax +49 30 253 912 20 | studzinski@short-cuts.de 

Am 08.08.2012 um 16:38 schrieb Marc Whitbread notifications@github.com:
