### ISSUE TITLE
would like options for autoslide

### ISSUE THREAD

**Issue by mcarswell** [iosscripts/iosslider#79]
I would like to implement this slider with a play button, so that when the slider loads, autoslide is off, but clicking the autoSlideToggleSelector starts it (with no delay on the first slide). currently autoSlideToggleSelector only works if autoslide is set to true, which means the slider is already playing after loading.

**Comment by iosscripts** [comment]
I don't think this is working as intended. If autoSlide is false, you should be able to start it via the autoSlideToggleSelector. In the mean time, you could load the slider with autoslide set to true, and then use JavaScript to click your toggle button immediately, making it appear to never have started.

**Comment by iosscripts** [comment]
> clicking the autoSlideToggleSelector starts it (with no delay on the first slide)

When clicking the toggle, call $('.iosSlider').iosSlider('goToSlide', slideNumber); as well and that should do what you need.

**Comment by mcarswell** [comment]
i figured out the click trigger (added $('#playButton').trigger('click'); right after the slider is loaded) and i'll try the goToSlide bit now. thanks!
