### ISSUE TITLE
RoyalSlider clone

### ISSUE THREAD

**Issue by markfinst** [iosscripts/iosslider#80]
Plugin looks like exact copy of old version popular RoyalSlider, I comapred source code, and even product descriptions match.   Any comments on this?

**Comment by iosscripts** [comment]
Made it from scratch myself. You compared the source code, show me the code overlap?

And who are you exactly?

Sent from Samsung Mobile

-------- Original message --------
Subject: [iosSlider] RoyalSlider clone (#80)

**Comment by markfinst** [comment]
Simple comparing between two pages is more than enough
RoyaSlideshow : http://dimsemenov.com/plugins/royal-slider-wp/
Your slider : http://www.iosscripts.com/iosslider/

Code if refactored, but by taking closer look the logic and all actions are the same.

I'm just the developer and such copying disturbs me, that's why I'm asking you.

**Comment by iosscripts** [comment]
I want to make it clear that I am outright denying that I have ever stolen code from anyone. You are making large claims here sir. 

> Simple comparing between two pages is more than enough

2 executions are the same-ish. OK. How does that mean the plugin is plagiarized though? 

As the person who developed this, if I play around with RoyalSlider, I can tell the code is different without even looking at it. The person who developed that plugin would surely tell you the exact same thing about my implementation.

> Code if refactored, but by taking closer look the logic and all actions are the same.

Code is refactored? How convenient for you. Show me a logic structure in his code that is the same as mine. Somewhere, something to substantiate this claim.

> I'm just the developer and such copying disturbs me, that's why I'm asking you. 

I'm a developer and such accusations without any substantial code proof disturbs me.

**Comment by iosscripts** [comment]
Oh you are THE developer of RoyalSlider? Want to call me? I would love to discuss this with you actually. 

Skype or Phone? Let me know. email contact@iosscripts.com

**Comment by markfinst** [comment]
What makes you think that? Stop being childish.

I sent your plugin link to Royalsldier author, maybe he will join the discussion too.

**Comment by iosscripts** [comment]
> What makes you think that? Stop being childish.

You said "I'm just the developer" so I assumed I misread your message the first time and you were THE RoyalSlider developer. My mistake.

No one is being childish and no one is taking these accusations lightly I assure you. 

> I sent your plugin link to Royalsldier author, maybe he will join the discussion too.

Sounds good. I'll send him an email as well. If he has any objections to my code or my implementation, he can take it up with me.

**Comment by madkrystiank** [comment]
:) algorithms and filosophy can't be patented
