### ISSUE TITLE
iosSlider doesn't work well with templating engines <script> junk

### ISSUE THREAD

**Issue by nicolasembleton** [iosscripts/iosslider#81]
When you use Ember.js/Handlebar.js, you got to get a lot of junk into your DOM being <script></script> surrounding pretty much every "binded" values that the script will need to output. 

If you take a look at this gist: https://gist.github.com/3354451

This gist is exactly 1 of my slider ( I have multiple sliders within a page ). 
When I try to trigger iosSlider using 

``` javascript
$('.iosSlider').iosSlider({ desktopClickDrag: true }); 
```

I get an error:

``` javascript
SyntaxError: Unexpected token ILLEGAL
```

If I remove all the <script> elements, then it's parsing well and the slider works well. 

I believe it is due to the fact that the plugin selects "all" the children nodes of the given selector, and process them as a valid entity or element ( even try to get width of a script ). 
I am not sure what would be the best way to avoid that, but I can think of 2 ways:
1. Automatically sanitize out all "script" nodes from a given selector when processing
2. Allow users to pass either:
   2.1 A list of "blacklisted" elements ( could be useful ) 
   2.2 The precise tag of sub-element to validate. In my case div ( maybe in most cases ). Maybe could be li for others or even ul.

Thanks,
Nicolas.

**Comment by iosscripts** [comment]
I'm not too familiar with these MVC frameworks. But I'll do my best to help you out. 

> I believe it is due to the fact that the plugin selects &quot;all&quot; the children nodes of the given selector, and process them as a valid entity or element ( even try to get width of a script ).
> You are exactly right. Using my site tutorial as an example, the children of the "slider" element are the "slides". The script needs these "slide" nodes to be standard HTML elements. 

I am analyzing your gist, please correct me if my conclusions are incorrect in any way. 

Below is the "slider" node which is a child of the "iosSlider" node, correct? I just want to confirm that you have not included the top level "iosSlider" node in your demo.

``` html
<div id="ember475" class="ember-view slider" style="position: relative; overflow: hidden; cursor: -webkit-grab; -webkit-perspective: 1000px; -webkit-backface-visibility: hidden; width: 2650px; -webkit-transform: matrix(1, 0, 0, 1, 0, 0); ">
```

That would mean that your slides are as follows:

``` html
<script id="metamorph-19-start" type="text/x-placeholder" style="width: 0px; float: left; "></script>
<script id="metamorph-20-start" type="text/x-placeholder" style="width: 0px; float: left; "></script>

<div class="draggable post slide21" id="post21" style="width: 235px; float: left; ">
    ...
</div>

etc...
```

From what I understand, your saying that your page will function correctly if the script skips over these "script" elements? I can modify the script to blacklist all script tags. I think it is perfectly reasonable to assume that you should not be able to use script tags as slide nodes.

**Comment by nicolasembleton** [comment]
You are correct. I forgot the top level iosslider. Sorry for that.

Yes I think just blacklisting the script tags would make it ember.js (mv*?)
compatible. I think. I could confirm you that as soon as you would be done
with it. That would be really really cool.

**Comment by iosscripts** [comment]
It's late here in Toronto. I will do some testing on my end and have something for you in half a day or so.

**Comment by nicolasembleton** [comment]
Yeah sure. No problem. Thanks a lot for the support.

**Comment by iosscripts** [comment]
One quick attempt before I take off. I just pushed v1.0.33 to master with a possible fix. Let me know if it works :)

**Comment by nicolasembleton** [comment]
Hey great. I'm gonna try that right away and send you the feedbacks. :)
Thanks and good night.

2012/8/15 Marc Whitbread notifications@github.com

**Comment by nicolasembleton** [comment]
Yeehaa. Working great.

On the mea culpa side, I also had another issue that was still causing me
"ILLEGAL TOKEN", a malformed onclick event that was crashing when it was
being transferred to jQuery.data() stack. Here's the log of "this" on line 789 and the error following the .data() call:

``` javascript
<a id=​"p-61" onclick=​"javascript:​openHash(\'#id-61\')​;​" style=​"z-index:​1000;​">​shortDesc61​</a>  - jquery.iosslider.js:789
  SyntaxError: Unexpected token ILLEGAL
```

Anyway, onclick events are evil. I should avoid them...

Thanks a lot for the <script> cleanup. :)
