### ISSUE TITLE
Slides with different, unknown widths

### ISSUE THREAD

**Issue by JoseTomasTocino** [iosscripts/iosslider#82]
I have set up a 100%-width slider and it works OK if I use slides with the same width, this being defined in the CSS. However, If those slides have different, dynamic widths, I can't make it work.

Would it be possible for the slider to automatically calculate the width of each slide?

**Comment by iosscripts** [comment]
It should work. Going without a width defined in the CSS of the slides has been known to cause some issues. 

Do you have a demo I can take a look at? or some HTML/CSS/JS to work with?

**Comment by JoseTomasTocino** [comment]
It usually happens when I have one single, wide slide without a defined width. Take a look here: http://www.proyectoego.es/lab/test_1/

I guess it's more of a CSS problem rather than a problem with the library, but It'd be great to have some kind of workaround.

**Comment by iosscripts** [comment]
What are you looking to achieve by having a dynamic width on the slides? Parhaps there is a better way? 

What would you expect the width to be based on if it isn't explicitly defined? The width of the images contained?

**Comment by JoseTomasTocino** [comment]
I'm looking to be able to have any content I want in there, whether it's a single image or more.

Eventually I've achieved it using one slide per element, without defining the width of each slide. That way it works

**Comment by iosscripts** [comment]
I'm glad you found a workaround. :)

Just keep in mind that there will always be outside cases for some content that wont work will with undefined slide widths. If you run into any, I would love to hear about them. 

Thanks again for the feedback.
