### ISSUE TITLE
Feature Request: Create callback from slider update

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#83]
I have position marking dots under the two sliders on screen. The number of slides per slider can change, and the number of slides on screen can change at any time.

Since the position dots are external to slider, there is no way to update them on every event, like after calling remove/add slide. Or when doing a resize on the window that results in changing the number of tiles on screen.

I am already using the onslidechange event to trigger the change when sliding the slider, but this does not cover adding slides, and also doesnt cover changing # slides on screen(planning to manually call update when this happens)

Can you create another callback, this time whenever update is completed?

Thanks man! :)

**Comment by iosscripts** [comment]
Sure. That would be easy. Can't hurt to have more callbacks.

Sent from Samsung Mobile

-------- Original message --------
Subject: [iosSlider] Create callback from slider update (#83)

**Comment by iosscripts** [comment]
The onSliderUpdate callback has been added in 1.0.38. I will update the website for the next stable release.

**Comment by ColColonCleaner** [comment]
Excellent :)
