### ISSUE TITLE
Is there a place i can drop code that might be useful to you?

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#86]
Right now i am just creating issues for them and that seems rather backward. Like with the updates made to add/remove slides. Is there a place for code suggestions or updates?

**Comment by iosscripts** [comment]
Hmmm. If it's pertaining to the iosSlider source, a pull request would work best. If it's for troubleshooting, zipping a demo and emailing it to contact@iosscripts.com referencing an issue # would work fine.

If you have a more efficient method, I'm all ears.

**Comment by ColColonCleaner** [comment]
I am attempting to to a pull request. I already forked the repo and added my changes (just the ones for this update so far, will get to more later).

But i don't see the pull request button o.O, it's just not there. what i am i missing?

EDIT: nevermind, i got it :)
