### ISSUE TITLE
Event error after remove when multiple sliders on screen

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#88]
Working on the add/remove stuff i noticed an event error after a slide has been removed. 
First i thought it was something i did, but then i tested using the vanilla version of your code. 

Scenario to cause the problem: sorry, no video this time :( 

Have two sliders on screen, both referenced by ID (if that matters).
Call remove on any slide in either slider (vanilla, by index).
When the remove is done, slide the other slider. Your cursor will be unable to release the slider.

This is on windows using webkit browser, i am unable to test on iPad at this time.

**Comment by iosscripts** [comment]
Fix applied to v1.0.39.
