### ISSUE TITLE
onSlideChange fires twice randomly

### ISSUE THREAD

**Issue by gregbown** [iosscripts/iosslider#89]
onSlideChange fires twice randomly.
I am updating the page content if a user indexes the slider with the onSlideChange method.  The odd thing is that it is more noticeable when sliding backwards or there is more of a delay.  There are two instances in the plugin where the method can be called and it is the first instance approximately line 111 inside the slowScrollHorizontalInterval method. I suspect the interval is not cleared and fires twice but that is just a guess.

To work around this I remove content in onSlideChange because it occurs before onSlideComplete and then add content in onSlideComplete.

It is a well thought out and great slider.  It would be nice if the onSlideChange  was not buggy though since it fires immediately and is such a convenient event.

Thank you
Greg

**Comment by iosscripts** [comment]
Randomly? Does that mean it fires twice every time you change slides? or at random?

Which version of iosSlider are you running? Are you calling the iosSlider() initialization function more than once, at any time in your JS?

**Comment by gregbown** [comment]
I apologize for any lack of clarity. It fires on slide indexing (not randomly)twice sometimes using navigation controls or mouse/touch. By random I meant it always fires once but sometimes twice. I am only initializing on dom ready by declaring the instance on a container div. I am using the version 1.0.27 according to script but I downloaded  1.0.35. Perhaps the demo folder had an older version

----- Reply message -----

**Comment by iosscripts** [comment]
That's odd. Can you verify that you are testing against the latest version? 1.0.35 should be fine. You can get it here: https://github.com/iosscripts/iosSlider/zipball/master

I know there was a duplication issue in an older version so please confirm with your implementation. Thanks.

**Comment by gregbown** [comment]
I grabbed version 1.0.38 and the issue is still occurring.

Thank you for the prompt responses
Greg

----- Reply message -----

**Comment by iosscripts** [comment]
I believe I have this sorted out in v1.1. I was finally able to reproduce the issue :).

**Comment by martinduparc** [comment]
It seems like the issue is still present when calling "goToSlide".

See this example: http://jsfiddle.net/Vyv27/8/

When going from slide 1 to slide 2, the "onSlideChange" event will fire twice.

Using v1.3.10

**Comment by marcwhitbread** [comment]
@martinduparc Thanks for pointing that out. 

v1.3.11 has the fix.
