### ISSUE TITLE
Get specific slideNumbers

### ISSUE THREAD

**Issue by OwenMelbz** [iosscripts/iosslider#90]
Hi all,

I'm hope that there is a way i can hook into the plugin to create a manual navigation for iosslider.

At current I was hoping to use

$('.iosSlider').iosSlider('goToSlide', args.currentSlideNumber-1); // to go back a slide
$('.iosSlider').iosSlider('goToSlide', args.currentSlideNumber+1); // to go forward a slide

however, If "previous" is clicked when its on the first slide, i want it to go to the last slide.

I envisioned this  to work something like

$('.iosSlider').iosSlider('goToSlide', $('.item').length); // go to last slide.

 $('.item').length returns the correct number of slides, however when i run that slide number, it goes to some random slide.

is there a definitive way that I can send the slider to the last slide?

many thanks

**Comment by ColColonCleaner** [comment]
It seems like your problem would be solved by using the prevNavSelector and nextNavSelector inputs slider allows. And if you want it to loop back around to the back of the slide list just enable infiniteslider at startup.

@iosscripts You might want to think about this though. Enabling a mid point between standard and infinite slider. Where clicking the previous selector when on the first slide will make the slider jump to the last slide. Like infinite slider, but without rearranging slides.

**Comment by iosscripts** [comment]
It would have to implemented as another setup parameter. Some will want it to not advance and others will :S.

I will create a new issue for this feature (even though it is extremely minor).
