### ISSUE TITLE
infinite mode without copying slides

### ISSUE THREAD

**Issue by naltatis** [iosscripts/iosslider#96]
Copying slides makes trouble when you are using id's in your slides.

**Comment by iosscripts** [comment]
You're right, I have been giving this some thought lately. Looking for a better approach that might involve moving slides around instead of duplicating slides.

**Comment by ColColonCleaner** [comment]
Suggest using detach() then append()/appendChild()

Detach keeps all bindings intact while you move the item around.

**Comment by iosscripts** [comment]
That would work, sure. I was also thinking about adding position: relative; and left: XXpx to each slide and then changing the left value to move slides around. That would mean that there is no instance in time where the slide is removed from the DOM. But, I'll have to check and see which method would use less processing.

**Comment by ColColonCleaner** [comment]
Well moving the slide with css is probably a better option than removing and adding again, the only problem is that you will run into the case where the slides are in a different order on screen than in slider's list of nodes. It would be good for performance using that approach too, moving divs with css takes a lot less work than appending.

**Comment by daegloe** [comment]
With this change, when infiniteSlider and autoSlide are both true, will it continue to scroll endlessly in the right-to-left direction?

**Comment by iosscripts** [comment]
It will yes. It does do this currently I believe. I am aiming to maintain all current functionality while still making this change.

**Comment by daegloe** [comment]
Ah yes, you are correct.

**Comment by iosscripts** [comment]
Ok, so I have this working now. Didn't realize I would have to overhaul the entire code base, but this is what I was intending on doing for infinite sliding in the first place. I have gone to v1.1.0 on the master branch and is ready for final testing. Hopefully the bugs are minimal. 

Let me know if you run into any issues and I will try to fix them as quickly as possible.
