### ISSUE TITLE
Blurry fonts in Mobile Safari & Safari

### ISSUE THREAD

**Issue by netmills** [iosscripts/iosslider#97]
I'm using a slider which contains another slider (on the second slide only). The fonts in the inner slider always look blurry (even with a simple demo page).

I can solve this by adding

``` css
-webkit-perspective: 0px !important;
-webkit-backface-visibility: visible !important;
```

to both sliders (like in [Issue #78](https://github.com/iosscripts/iosSlider/issues/78). (Adding it only to the inner slider works with Safari 6, but not with Mobile Safari on iPad 3.)

But then the performance on Mobile Safari (iPad 3, iOS 5) is bad.

Only adding `-webkit-font-smoothing: subpixel-antialiased;` does not help at all.

Is there another solution? Giving perfomance and sharp fonts?

Thanks

**Comment by iosscripts** [comment]
Interesting. I havet been able to nail down a 100% effective solution to the font antiailiasing issues. Do you have a demo i can look at to troubleshoot?
null

**Comment by ColColonCleaner** [comment]
The problem may be due simply to the graphical performance at your disposal. On ipad, and especially iPad 3, rendering for javascript and CSS takes a while when motion is involved, so there may not be a medium to get everything looking exactly as you want it for text. Since text is not a raster, and is instead a vector, if you can find a way to rasterize the text then it would work, but look bad on zoom.

**Comment by netmills** [comment]
I created a simple demo (with the code from your website):
- [with blurry text, standard configuration](http://kunden.netmills.de/other/simple-no-webkit-css.html)
- [no blurry text, with the `-webkit-...`-css](http://kunden.netmills.de/other/simple-webkit-css.html)

On Safari you have to zoom in to actually see the blurry text, on the iPad its always visible.

Here's a demo with real content, where you can see the performance issues on the iPad:
- [blurry text](http://kunden.netmills.de/other/website-no-webkit-css/#en/what/inDetail)
- [no blurry, with `-webkit-...`](http://kunden.netmills.de/other/website-webkit-css/#en/what/inDetail)

**Comment by hz-stevec** [comment]
Why is this closed? it's not fixed...
