### ISSUE TITLE
Using goToSlide does not trigger onslidechange callback

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#99]
Noticed that when calling gotoslide, the onslidechange callback is not fired, is this intended?

**Comment by iosscripts** [comment]
No, it should be. Good find.

**Comment by daegloe** [comment]
+1

We're currently implementing a workaround by triggering arrow keydown events on the document object. Would be great to have this fixed.

**Comment by iosscripts** [comment]
I agree, this is definitely a high priority fix. I am currently working hard on #96, which requires heavy modifications to the script. I will be jumping on this as soon as the new infinite scrolling is released.

**Comment by iosscripts** [comment]
This should be working as of v1.1.7. Let me know if the issue is still showing up.
